### ISSUE TITLE
（質問）デモページでのユーザ登録について

### ISSUE THREAD

**Issue by kobake** [Implem/Implem.Pleasanter#1]
個人メールでデモページ (https://pleasanter.azurewebsites.net/) に登録し使ってみたのですが、
プロフィールページ (https://pleasanter.azurewebsites.net/users/867/edit) を見ると
Tenant48_User1@example.com という覚えのないメールアドレスになっていました。
これはデモユーザ共通で使いまわされるユーザのようなものですか？
（ここのユーザに自分の個人メールアドレスを登録したら他のデモユーザにも見えてしまう？）

**Comment by Implem** [comment]
ご質問ありがとうございます。

デモ環境はマルチテナントで運用されているため、他のテナントのユーザからメールアドレスやその他の情報を閲覧される事はありません。テナントはデモ利用申請毎に新規に作成されます。ご自身のアドレスを登録されても、そのテナントにアクセスできるユーザ以外から見る事はできません。ご不明な点がありましたら、またご連絡ください。

**Comment by kobake** [comment]
りょうかいです、ありがとうございますー
