### ISSUE TITLE
インポート準備がたいへん (元の CSV が横長な場合)

### ISSUE THREAD

**Issue by karoshima** [Implem/Implem.Pleasanter#10]
たいへん横に巨大なエクセルベースの問題管理から、プリザンターに移行したいなと思っています。
ちなみに 100 列を超えてます。さいわい縦にはまだあまり伸びておらず、1MB もありません。
手元には バージョン0.41.1.33578 をインストールしました。

こちら (*1) のインポートの説明では
「インポートするテーブルの項目とヘッダの名前が一致しない場合、その項目はインポートされません」
とあるので、テーブルの項目を設定する必要があるのですが、
これはエディタ管理でひとつづつ100個以上つくる必要がありそうです。
目がまわる…

数多くの項目を一括で作れるようにできないでしょうか。

*1 https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E6%A9%9F%E8%83%BD%EF%BC%9A%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88

**Comment by Implem** [comment]
項目の作成ですが、設定情報をテキストエディタで直接編集する方法があります。設定情報をDBから取り出し、json形式のデータを手動で編集してDBに書き戻すことができます。GUIのように解りやすい手順ではありませんが、こちらをご検討いただければ幸いです。

対象テーブル：Sites
対象レコード：SiteIdが一致するレコード
対象カラム：SiteSettings

jsonの構造としては、Columnsという項目の中に項目を増やしていくカタチになります。以下のような形式です。分類AなどのLabelTextをCSVのヘッダと一致するように作成してください。

"Columns":[{"ColumnName":"ClassA","LabelText":"分類A"},{"ColumnName":"ClassB","LabelText":"分類B"} ...]

尚、項目は分類、数字、日付、説明、チェックの種類があり、各A-Zまでの26種類が限界となっています。DBからのデータの取り出し及び書き込みには、SQL Server Management Studio等をご使用ください。

**Comment by karoshima** [comment]
おおう、力技ですね。
事前にプリザンターをサスペンドしたり、書き換え後に再開させたりという手続きは必要でしょうか。

**Comment by Implem** [comment]
はい、かなりの力技ですが、GUIよりは速くできるとおもいます。サスペンドなどは不要です。リアルタイムに反映可能です。

**Comment by karoshima** [comment]
ありがとうございます！
