### ISSUE TITLE
困っていて

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#108]
データベースさっぱりわからないのでうまく表現できませんが、

１．レスポンスが遅い
　　社内のサーバで立ち上げて使用しています。使用して９ヶ月、随時、アップデータ実施。
　　現在のバージョンは、0.49.65.11622。
　　リンク元の一つをレコードをクリックする８秒くらいかかる。
　　リンク先は７個あり、計２５万レコードくらいあります。
　　リンク先や他のところは問題なく使用できています。
試しに、
　・別のサーバに環境を作り、バックアップをそのサーバに入れました。
　　SQL Server Management Studioを使って、片っ端から手作業でインデックスの再構築を選択して
　　みましたが、改善しませんでした。断片化率は４０％以上超えているもの多かったです。
　・リンク先の７個のリンクを外すと問題ないスピードです。

２．時々、プリザンタが起動しなくなります。その時、サーバとても重く、タスクマネージャーで確認するとIISが
　　CPU100%となります。この時、他のグループウェア等は問題なく使用できています。再起動するとまた使
　　えます。頻度、２日１回くらい。続きときは続きます。OSはWindows10 Pro April 2018 Update。

　使い方の問題やプリザンタ関係ないかと思いますが、どなたかアドバイス頂けるとうれしいです。
　　（データベースて最適化とか必要ですか？）

**Comment by akiyamashino** [comment]
書き漏れました。しばらく使用してなく、プリザンタを使用しようとする時間がかかります。
調べて、自動終了をFALSEにすると時間がかからなくなりました。
この時、再起動やバージョンアップに問題がないか不安なのですが、ご存知の方いますか？

**Comment by akiyamashino** [comment]
0.49.153で使用したら動作が早くなっていました。ありがとうございます。また、データベース圧縮は急ぎでなくなったので時間ができた時にtpで試してみます。何かありましたらまた、投稿します。ありがとうございます。

**Comment by usoma** [comment]
私も同じ事象が発生しています。
ほっておくとCPU使用率が100％となり、戻りません。（IIS再起動で戻る）
バージョンは確認していませんが、今はOS/IISの定期的な再起動を入れて対応しています。

**Comment by akiyamashino** [comment]
お恥ずかしい話ですが、ごみ箱を空っぽにするとすごくレスポンスが改善されました。

また、知らないうちにCPU100％の回数は激減しました。
深夜に電話対応大変なので使用している人にpowershellのコマンドを作成してプロセスの終了やパソコンの再起動を遠隔操作してもらっていました。
