### ISSUE TITLE
マニュアル誤記

### ISSUE THREAD

**Issue by karoshima** [Implem/Implem.Pleasanter#11]
バージョン0.41.1.33578 とマニュアルを見比べて気付いた点を列挙します。

管理機能：エディタ：開始
管理機能：エディタ：完了

- 本体にはありませんでした → エディタの書式の日付と時刻(秒)、 エクスポートの書式

管理機能：エディタ：分類

- 「2.Wikiの連携」の詳細な手順のリンクですが、リンク切れになっているようです (Firefox, GoogleChrome で確認)

**Comment by YasufumiMorii** [comment]
ご連絡ありがとうございます。
該当箇所の修正を行いました。またお気づきの点がありましたらご指摘ください。

**Comment by karoshima** [comment]
見れましたー、ありがとうございます！！
