### ISSUE TITLE
エディタについて

### ISSUE THREAD

**Issue by sh-hirose** [Implem/Implem.Pleasanter#110]
お世話になっております。

プリザンタで脱エクセルを検討しておりますが、
エディタの設定で以下のような動作は可能でしょうか。

■質問1
分類項目で選択リストを作成し、「重複禁止」設定をすれば
同じ値を登録できなくなりますが、新規登録画面のプルダウンでは
既に使用済みの項目も選択でき、作成ボタンを押した段階で初めて
重複禁止のエラーがでます。

そのため、既に使用済みの項目をプルダウンに表示しないように
したいのですが、そのような動作は可能でしょうか。

■質問2
項目の連携について。
例えば社員番号を入力すると自動的に氏名の項目に
該当の社員名が入力されるような動作をさせることは可能でしょうか。

色々試してみたのですが、実現できる方法が分からずご教示いただけると幸いです。
よろしくお願いします。

**Comment by NaokiShiwa** [comment]
Issueありがとうございます。
質問1,2につきまして、残念ながらプリザンターの基本機能では実現することができませんが、
「特定のレコード情報を取得する」といったスクリプトを実装することで期待した動作を実現することは可能です。
（質問1の動作を実現しようとすると、項目数によっては処理時間が長くなる可能性があります）

「特定のレコード情報を取得する」に関しては、プリザンターのAPIを使用することになります。
以下にプリザンターのAPIの使用方法や、実際に使用した例を挙げているサイトのURLをご案内いたします。

プリザンター API機能マニュアル：
https://github.com/Implem/Implem.Pleasanter/wiki/API%E6%A9%9F%E8%83%BD%EF%BC%9A%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E6%93%8D%E4%BD%9C

はてなブログ「新機能「API」をさっくりと試してみた③～解決！！」：
http://pleasanter.hatenablog.jp/entry/2018/04/30/000000
