### ISSUE TITLE
SQL Database のテーブル作成がタイムアウトにより失敗する

### ISSUE THREAD

**Issue by f-sakai** [Implem/Implem.Pleasanter#111]
#100 の続きです。
フルテキスト検索の設定が有効の場合に失敗するとのことでしたが、フルテキスト検索の設定が無効の状態(※1)でも失敗しています。
他に必要な対処を教えてください。

※1 下記手順を参照し、`search.json`の`Provider`パラメータが`null`であることを確認しています。
[パラメータ設定：Search.json](https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E8%A8%AD%E5%AE%9A%EF%BC%9ASearch.json)

**Comment by sato-ha** [comment]
うちの環境の場合は
0.48.1.13579から0.49.4.13382へアップデートしようとした時に、インデックスを無効化してもエラーになったので、手持ちのモジュールで0.48.54.24731へアップデートしました。

別環境で0.48.54.24731から0.49.4.13382へのアップグレードをした時はエラーは出ていないのですが、現在、使用したい機能が0.48.54.24731で利用できている状態なので、0.49へのアップグレードは保留しています。

0.48のあるバージョン以降からでないと0.49へのアップグレーそに失敗するのではないでしょうか？

**Comment by kazuca** [comment]
ちょっと面倒ではあるんですが下記SQLを手動実行したあとにアップグレードを行えば、0.48→0.49のアップグレードは行えます。

ALTER TABLE [Binaries_history] ALTER COLUMN [Size] BIGINT NULL
ALTER TABLE [Binaries_deleted] ALTER COLUMN [Size] BIGINT NULL
ALTER TABLE [Binaries] ALTER COLUMN [Size] BIGINT NULL

**Comment by f-sakai** [comment]
返信遅れまして申し訳ございません。
コメントありがとうございます。

いただいた手順を参考に、テーブル作成に成功しました。
ただ、 #114 と同じ現象が発生したため、結局アップデートは保留にしています。

このチケットとしてはクローズします。
