### ISSUE TITLE
表示でカレンダーを選ぶとアプリケーションで問題が発生

### ISSUE THREAD

**Issue by kirakiraname1** [Implem/Implem.Pleasanter#112]
表示でカレンダーを選ぶとアプリケーションで問題が発生しました。その後、そのテーブルは開くことさえできなくなっていしまいましたが、しばらく時間おいた後、気づくと開けるようになっていまししたが、カレンダーを選ぶと再に同じ問題がおきます。

サーバホストはWINDOWS 2012R2 STD英語版です。インストールのインストラクションは、よく見たつもりなのですが、何か特定のコンポーネントが足りないのでしょうか。全文検索やAD連携は設定してあります。

またエラーログはどこにあるのでしょうか？

**Comment by Implem** [comment]
エラーログですが、SysLogsテーブルに格納されています。SQL Server Management StudioでSysLogsテーブルを開いていただき、[ErrMessage]および[ErrStackTrace]カラムに記録されている情報をご確認ください。

**Comment by kirakiraname1** [comment]
エラーログ保存場所を早速ご教示いただきまして、ありがとうございました。

[ErrMessage]の内容は以下の通りでした。
The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.

datetimeのフォーマットエラーの様です。英語環境のホストにインストールしたので、システムロケールなどが原因かもしれないと推測ができるのですが、もしそうだとしたら、DBテーブルやアプリ側の設定などで対応できるものでしょうか？


--

**Comment by Implem** [comment]
カレンダー表示の処理に不具合がありました。修正版を公開致しました。
