### ISSUE TITLE
Microsoft Teams送信時のProxy設定について

### ISSUE THREAD

**Issue by koikoi0407** [Implem/Implem.Pleasanter#113]
当方、社内事情によりProxy配下のネットワークにプリザンターのサーバを設置しています。
通知でTeamsを利用する場合、Proxy認証を抜ける必要が有るのですが、Proxy関連の設定は有るのでしょうか？お手数ですがご教示願います。

**Comment by Implem** [comment]
Proxy関連の設定は標準機能では対応しておりません。
