### ISSUE TITLE
アップデート後、プリザンターでページが表示されない

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#114]
お世話になっております。

以前、[こちらのissue](https://github.com/Implem/Implem.Pleasanter/issues/20)でご教授いただいた手順で
ClassA1～AXXの項目を増やして利用しているプリザンターをアップデートしたところ、
ClassA1～AXXを利用していたレコードが開かなくなりました。
「アプリケーションで問題が発生しました。」と表示されます。

SQLDBを直接確認すると、ClassA1～AXXがSQLDBに存在せず、
ClassA～Zしか存在しない状態になっておりました。

以前、[こちらのissue](https://github.com/Implem/Implem.Pleasanter/issues/20)でお教えいただいた、分類の数を増やす方法ですが、
ver0.49.97.28691では、利用できなくなっていますでしょうか？
環境はAzureです。

>現状、分類項目はA-Zの26種類です。ソースコードを改変することで項目を増やすことは可能です。手順は以下のとおりです。
>
>ソースコードをダウンロードします。
>Implem.Pleasanter/App_Data/Definitions/definition_Column.xlsmを開きます。
>期限付きテーブル等のClassA～Zの下にClassA1～ClassAXXの行を作成します。（★）
>Excel上でマクロを有効化し、Shift + Ctrl + J と操作します。
>マクロが実行され、データベースのレイアウトを更新します。
>上記のあと、追加した項目に関連するソースコードを自動生成します。
>生成されたソースコードをコンパイルしデプロイします。

ご確認いただけますと幸いです。よろしくお願いいたします。

**Comment by Implem** [comment]
大変もうしわけありませんが、項目を増やす仕組みはオープンソース版でご利用いただけなくなりました。Enterprise Editionのご利用をご検討ください。
