### ISSUE TITLE
Ajax有効時に拡張スタイルが適用されない場合がある

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#116]
レコードの遷移にAjaxを使用にチェックを入れている場合にスタイルが適用されない場合があります。
初回のロード時には適用されていますが、Ajaxでなんらかのリロードがかかった場合に、スタイルが無効化されます。

Var.0.49.101.25845

**Comment by yoshiyuki-sato** [comment]
issuesありがとうございます。
上記の件ですが、スタイルが無効化される場合のCSSのコードを頂くことは可能でしょうか。

**Comment by kazuca** [comment]
`div.title[title^="仮"]
{
     color:grey;
     font-style: italic;
    -webkit-transform: skewX(-15deg);
    -moz-transform: skewX(-15deg);
    -o-transform: skewX(-15deg);
    transform: skewX(-15deg);
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=1, M12=-0.26794919243112214, M21=0, M22=1, SizingMethod='auto expand')";
}

div.title[title^="確"]
{
    font-weight: bold;
}`

こちらになります。カレンダー表示が対象になります。
