### ISSUE TITLE
一覧ソートの挙動がおかしい

### ISSUE THREAD

**Issue by a0z0** [Implem/Implem.Pleasanter#119]
お世話になっております。

一覧のヘッダーをクリックしたときのソートの挙動がおかしいです。
具体的にはデータが多い(複数ページある)と...
・正しくソートされない
・スクロールが固まる
・最後のページまで表示されない
などが発生します。

Pleasanter.0.49.157.29800
Chrome  71.0.3578.98

**Comment by kazuca** [comment]
当方の環境でも発生しています。

Pleasanter 0.49.158.33806
Chrome 72.0.3626.81

**Comment by a0z0** [comment]
Pleasanter.0.49.163.20839
でも発生しています。

**Comment by Implem** [comment]
不具合があったので修正してみました。時間かかってすいません！

**Comment by suteado0928** [comment]
ソートされない、最後のページまで表示されないといった症状は改善されましたが、
ソート後にスクロールして追加読み込みをした項目のソートが効いてないように思います。
全部読み込んで再ソートしても再度読み込まれるので同じ結果です。

Pleasanter 0.49.169.38124
Chrome 72.0.3626.119

**Comment by hoppybeer** [comment]
うちでもおかしいことになってます。
バージョンアップしてから、一覧表示に同じ項目が出てくるようになりました。

動作的には少しスクロールすると、ajaxで追加読み込みをしているようですが、
その際、それまでに読んだ40件？のうち、管理画面のリスト表示行数分だけ重複して
表示されているようです。

#うちだけですかね。。


例(リスト画面でデフォルトの20を設定していた場合)
1
2
3
:
39
40
21   ←重複して表示される
22
:

**Comment by sato0928** [comment]
前回の投稿の訂正です。
追加読み込み分がソートされていないのではなく、hoppybeerさんの指摘の通り重複していました。

**Comment by a0z0** [comment]
更新ありがとうございます。
・スクロールが固まる
・最後のページまで表示されない
というのは解決したように見えますが、正しくソートされないのはもしかしたら仕様なのかも。
ユーザやリンクした項目などは、IDでソートされるのでしょうか...
