### ISSUE TITLE
インストール時にパラメーターの指定と異なるディレクトリ配下の \App_Data\Parameters\Service.json ファイルを参照する場合がある

### ISSUE THREAD

**Issue by Hajime-Sasaki** [Implem/Implem.Pleasanter#12]
https://github.com/Implem/Implem.Pleasanter/wiki/プリザンターのモジュールを手動で配置する（高度な設定）
上記の手順にて、プリザンターを配置するディレクトリと同じ階層に既存のディレクトリがあり、その配下にも \App_Data\Parameters\Service.json ファイルが存在する場合、そちらを参照してインストール処理が続行される場合があります。

具体例：
プリザンターを新規に配置したいディレクトリ c:\wwwroot\inetpub\pleasanter\
参照されるべきファイル c:\wwwroot\inetpub\pleasanter\App_Data\Parameters\Service.json
既存のディレクトリ c:\wwwroot\inetpub\0001\
誤って参照されるファイル c:\wwwroot\inetpub\0001\App_Data\Parameters\Service.json

同一サーバーに複数のプリザンターを配置する場合や、単に同名のファイルがある別のWebサイトが稼働している場合に問題となると思われます。

**Comment by Implem** [comment]
ご指摘ありがとうございます。バグなので、修正いたします。

**Comment by Implem** [comment]
おそくなりましたが、本件修正いたしました。
