### ISSUE TITLE
機能リクエスト：管理機能・リマインダーの詳細設定について

### ISSUE THREAD

**Issue by kenji-tanaka-0123** [Implem/Implem.Pleasanter#121]
おせわになります。
リマインダーでの通知機能について要望を挙げさせていただきます。

１．レコードの関係者宛にメールを通知する設定として、RelatedUsersが用意されているかと思いますが、作成者、更新者、管理者、担当者のいずれかではなく、細かく分けて、別々に指定することはできませんでしょうか。

２．リマインダの開始日を過ぎたものは未完了でも通知しない、という条件を追加いただけませんでしょうか

以上、よろしくお願いします。

**Comment by Implem** [comment]
ご要望ありがとうございます。開発チームで実現可否検討いたします。
