### ISSUE TITLE
機能：環境のエスポート

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#123]
サイトをテンプレートしてエクスポート／インポートできないでしょうか？
 

例えば、A事業所、Ｂ事業所があってほぼ同じ内容。
ＡとＢは物理的にサーバ別。連携の必要ない。
Ａの環境をＢの環境に再現するのが大変。

※　IISがCPU100％なってしまい、拠点間VPNはっても再起動すると他の事業所も巻き込むので。

あと、自分の好きなテンプレートつくれると便利で。

**Comment by Implem** [comment]
現在のところ標準機能ではサイト設定をエクスポート/インポートする機能はございません。
