### ISSUE TITLE
デフォルトの表示について

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#124]
デフォルトの表示を一覧ではなく、カレンダーやガントチャートに固定したいサイトがあります。
管理画面を一通り探してみたのですが、該当の機能は見つけられませんでした。
カレンダーやガントチャートにデフォルトの表示を固定することは可能でしょうか？

**Comment by Implem** [comment]
現在のところ標準機能ではデフォルトの表示をカレンダーやガントチャートに固定する機能はございません。
