### ISSUE TITLE
LDAPのAuthType指定について

### ISSUE THREAD

**Issue by chanrai** [Implem/Implem.Pleasanter#125]
サポートツールにより、LDAP接続がテストした際に、いつも「ユーザ名またパスワードが正しくありません」のエラーが出ています。ネットログが確認したら、接続する際にdigest-md5により接続された原因で、認証が失敗しました。

AuthTypeがsimpleに指定したいですが、Authentication.jsonファイルでは、関連するパラメータがありませんので、AuthTypeの指定する方法が教えていただけますでしょうか。

以上、よろしくお願いします。

**Comment by Implem** [comment]
現在のところ標準機能ではAuthTypeを指定することができません。
