### ISSUE TITLE
一覧でリンクテーブルのフィルタでエラー発生

### ISSUE THREAD

**Issue by a0z0** [Implem/Implem.Pleasanter#127]
Pleasanter.0.49.162.22948 

一覧でリンクテーブルの分類フィルタを選択するとエラーが発生します。
画面上では「アプリケーションで問題が発生しました。」
ログは以下の通り。
`
CreatedTime,SysLogId,Ver,SysLogType,OnAzure,MachineName,ServiceName,TenantName,Application,Class,Method,RequestData,HttpMethod,RequestSize,ResponseSize,Elapsed,ApplicationAge,ApplicationRequestInterval,SessionAge,SessionRequestInterval,WorkingSet64,VirtualMemorySize64,ProcessId,ProcessName,BasePriority,Url,UrlReferer,UserHostName,UserHostAddress,UserLanguage,UserAgent,SessionGuid,ErrMessage,ErrStackTrace,InDebug,AssemblyVersion,Comments,Creator,Updator,UpdatedTime
2019/02/07 9:01:12,25164,1,Execption,False,PLEASANTER,Implem.Pleasanter,,Implem.DefinitionAccessor,items,index,ViewFilters__ClassF%7e595%2cClassC=%5b%22%u30d1%u30bd%u30b3%u30f3%22%5d&ControlId=ViewFilters__ClassF%7e595%2cClassC,,116,0,15.6272,669585.44,140.6201,,376.923,391196672,2208692961280,3160,w3wp,8,http://10.33.30.49/pleasanter/items/597/index,http://10.33.30.49/pleasanter/items/597/index,10.33.2.132,10.33.2.132,ja,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",f504a352ypmjvolh21mvl4cs          ,"マルチパート識別子 ""ClassF~595.ClassC"" をバインドできませんでした。
マルチパート識別子 ""ClassF~595.ClassC"" をバインドできませんでした。","   場所 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   場所 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   場所 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   場所 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   場所 System.Data.SqlClient.SqlDataReader.get_MetaData()
   場所 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   場所 System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   場所 System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   場所 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   場所 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.Try(Action action) 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 168
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteDataSet() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 147
   場所 Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteDataSet(Context context, String connectionString, Boolean transactional, Boolean writeSqlToDebugLog, SqlStatement[] statements) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataSources\Rds.cs:行 211
   場所 Implem.Pleasanter.Libraries.Models.Aggregations..ctor(Context context, SiteSettings ss, View view) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Models\Aggregations.cs:行 22
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlAggregations.<>c__DisplayClass0_0.<Aggregations>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlAggregations.cs:行 22
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 85
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlAggregations.Aggregations(HtmlBuilder hb, Context context, SiteSettings ss, View view) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlAggregations.cs:行 19
   場所 Implem.Pleasanter.Libraries.Responses.ResponseViewModes.ViewMode(ResponseCollection res, Context context, SiteSettings ss, View view, String invoke, Message message, Boolean loadScroll, Boolean bodyOnly, String bodySelector, HtmlBuilder body) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Responses\ResponseViewModes.cs:行 22
   場所 Implem.Pleasanter.Models.ResultUtilities.IndexJson(Context context, SiteSettings ss) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultUtilities.cs:行 129
   場所 Implem.Pleasanter.Controllers.ItemsController.Index(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 26
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)",,0.49.162.22948,,4,4,2019/02/07 9:01:12
`

**Comment by shinki1973** [comment]
0.49.161.18975 でも発生しています。

フィルタにリンク先の項目を指定した場合に発生しているようです。

**Comment by Implem** [comment]
ご連絡ありがとうございます。
不具合を修正し、最新版を公開しました。
https://github.com/Implem/Implem.Pleasanter/commit/002431b837e9b0a29f61c78adaec33230fd7817a

**Comment by a0z0** [comment]
早速対応いただきありがとうございました。
