### ISSUE TITLE
不正なメールアドレスチェックを回避する設定の追加希望

### ISSUE THREAD

**Issue by wolfwood514** [Implem/Implem.Pleasanter#129]
お世話になっております。
現在、オープンソースのPleasanterを使用し、社内イントラ内で構築しており、メールサーバーも社内イントラ内に構築しています。

現状、使用しているメールの形式が「xxxxxxx@xxxxxxx.localdomain」となっているため、メールアドレスの形式チェックで「不正なメールアドレスです。[xxxxxxx@xxxxxxx.localdomain]」と表示され、ユーザーごとのメールアドレス登録ができません。

「通知」設定の「アドレス」には上記の形式でも登録でき、実際にメールも送信されるため、ユーザーごとのメールアドレスの形式チェックも制限を緩和していただくか、回避できるオプション機能の追加を希望します。

画面上で設定できなくても構いません。
（たとえば、Mail.jsonファイルに設定値を設けるなど）

ちなみに、チェックが通る形式で登録した後、データベースの値を変更しても、実際にメールを送信する画面で、また同様のエラーが出てしまうため、修正いただける場合は、そちらも同様に考慮ねがいます。

ご検討のほどよろしくお願いいたします。

**Comment by Implem** [comment]
Mail.jsonにAddressValidationを追加しました。メールアドレスを判定する正規表現をカスタマイズすることが可能になりました。
