### ISSUE TITLE
IISの機能にWebDAVがインストールされていると正しく動作しない

### ISSUE THREAD

**Issue by Hajime-Sasaki** [Implem/Implem.Pleasanter#13]
プリザンターを配置するIISにて、HTTP 共通機能の「WebDAV 発行」がインストールされている場合、随所でエラー「405.0 Method Not Allowed」が発生し、正しく動作しません。

**Comment by Hajime-Sasaki** [comment]
十分に検証してはいませんが、私の手元では、プリザンター内でWebDAVを無効化して動作させています。
Web.configファイルの<system.webServer>要素内を以下のように修正
```diff
  <system.webServer>
    <validation validateIntegratedModeConfiguration="false" />
+   <modules>
+     <remove name="WebDAVModule" />
+   </modules>
    <handlers>
+     <remove name="WebDAV" />
      <remove name="ExtensionlessUrlHandler-Integrated-4.0"/>
      <remove name="OPTIONSVerbHandler"/>
      <remove name="TRACEVerbHandler"/>
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0"/>
    </handlers>
  </system.webServer>
```

**Comment by Implem** [comment]
Issueありがとうございます。
確認しましたところ、WebDAVがインストールされている環境では正しく動作しないようです。
HTTPメソッドのPUTやDELETEがASP.NETで拒否されているのが原因のようです。WebDAVは不要なので、ソースコード上で無効にする方針にしたいとおもいます。

**Comment by Implem** [comment]
最新版で、下記の不具合の対応を行いました。

Bug fixed: WebDAVがインストールされている環境で更新等が行えない問題を解消。
https://github.com/Implem/Implem.Pleasanter/commit/870107342eab0337c92dc2f3ac0947cf3018b9d7

ダウンロードパッケージとして公開していますので、お時間があるときにお試しください。今後ともよろしくおねがいいたします。
https://pleasanter.org/

**Comment by Hajime-Sasaki** [comment]
確認と返信が遅くなりました。
現在のバージョンのプリザンターをWebDAVが有効な上にインストールして、問題なく動作しました。ありがとうございました。
