### ISSUE TITLE
登録後の編集ロック

### ISSUE THREAD

**Issue by ccskazuotanaka** [Implem/Implem.Pleasanter#134]
内部統制上、編集のロックをレコードごとにかけたいと思っています。
レコードを登録後に、ステータスが完了になったらレコードは編集できないようにできますでしょうか？
単にレコード単位でアクセス権をグループに対して読み取りで設定しましたが、うまくできませんでした。

**Comment by Implem** [comment]
標準機能では対応していないため、JavaScriptで更新ボタンを非表示にするなどの対応をご検討ください。
