### ISSUE TITLE
[確認]孫テーブルでのサマリ

### ISSUE THREAD

**Issue by hoppybeer** [Implem/Implem.Pleasanter#136]
親子孫関係のあるテーブルで、孫>子はサマリが有効ですが、孫>子>親へサマリが反映されません。何か使い方を間違っていればご教授ください。

[PC]ID=1 [課]ID=2 [部]ID=3という３つの記録テーブルを作成。

[PC]テーブルの分類Aを【設置課】とし、選択肢一覧に[[2]]と記載。

[課]テーブルの数値Aを【課PC台数】と設定し、読み取り専用に。
[課]テーブルの分類Bを【所属部】とし、選択肢一覧に[[3]]と記載。

[部]テーブルの数値Aを【部PC台数】と設定し、読み取り専用に。

[PC]テーブルのサマリで
データ保存先（サイト＝[課]、項目=【課PC台数】）、リンク（リンク項目=【設置課】、サマリ種別=件数）
と設定

[課]テーブルのサマリで
データ保存先（サイト＝[部]、項目=【部PC台数】）、リンク（リンク項目=【所属部】、サマリ種別=合計、サマリ項目=【課PC台数】）
と設定

ーー
この状態で[PC]を追加すると[課]の【課PC台数】は自動的に反映されますが、[部]の【部PC台数】は自動反映されません。（手動で[課]のサマリを同期すると反映されます）

これを自動で[部]の【部PC台数】へ反映する方法はありませんでしょうか？

**Comment by kazuca** [comment]
私もいろいろ試しましたが、1階層上まででしか到達しないようです。
(コードは未確認)

とりあえず、テーブルに対してTriggerをかけて対応しています。

**Comment by Implem** [comment]
サマリの処理は1階層上まで処理する仕様となっております。2階層以上上のサマリを処理する場合は、孫レコード更新時のスクリプトで子レコードの更新を行う処理を組み込んでください。
