### ISSUE TITLE
ユーザへの表示項目について

### ISSUE THREAD

**Issue by usoma** [Implem/Implem.Pleasanter#137]
作成した項目でユーザ単位に公開を制限することは可能でしょうか？
ナレッジ管理で公開レベルを決める分類を作成し、テーブル全体は表示するが、
その公開レベルに合わせた表示にすることは設定で可能でしょうか？

**Comment by hoppybeer** [comment]
[テーブルの管理]から[項目のアクセス制御]のタブを選択すると、
作成時、読み取り時、更新時それぞれの場合における項目ごとに、
どの権限が可能か設定できます。
確認してみてください。

＃・・このissueですがここの所活発度が下がってますよね・・残念

**Comment by usoma** [comment]
[hoppybeer]さん
回答ありがとうございます！
私の書き方が下手で、うまく伝えられていないのですが、
ナレッジ管理で社内向けの内容を含んだレコードは分類「極秘」とし、
社外公開OKとした内容の項目は分類「公開OK」とします。
外部ユーザを作成し、このユーザは分類「公開OK」のレコードのみ表示させる設定は可能でしょうか？
社内のメンバに配布したユーザはどちらのレコードも表示させます。
