### ISSUE TITLE
[要望]リマインダー機能での宛先、内容について

### ISSUE THREAD

**Issue by hoppybeer** [Implem/Implem.Pleasanter#138]
「通知」機能では宛先に[RelatedUsers]が使えますが、
「リマインダー」機能では宛先に[RelatedUsers]が使えないようです。
宛先もユーザから選択するのではなくメールアドレスを指定する形式ですので、自分が関連する
レコードかどうかの判別もできません。

目的としては、Viewで【自分のみ、未完了、期限超過】というのを作成し、宛先に[RelatedUsers]を
追加することで自分のチケット相当のものに「期限が超過しています」とのメールを
送りたいのです。

**Comment by Implem** [comment]
現在のところ標準機能ではリマインダーの宛先を動的に設定することができません。
