### ISSUE TITLE
[要望]クロス集計時の項目フィルタについて

### ISSUE THREAD

**Issue by hoppybeer** [Implem/Implem.Pleasanter#139]
リレーションを大量に張ったテーブルに於いて、クロス集計時の
行、列で大量の項目が出てきます。
実際に使用する際にはクロス集計的に意味のない項目もあるため、
[テーブルの管理]>[クロス集計]において、項目の有効無効をできるようにならないでしょうか？

**Comment by Implem** [comment]
ご要望ありがとうございます。開発チームで実現可否検討いたします。
