### ISSUE TITLE
機能リクエスト：カレンダー連携

### ISSUE THREAD

**Issue by kolinz** [Implem/Implem.Pleasanter#14]
| Q  | A
| ---| ---
| バグ報告 | 
| 導入相談 |  
| 機能リクエスト |  Yes

タスク管理やプロジェクト管理では、開始日と終了日がありますから、Microsoft Exchange Server や Google カレンダー と、予定を同期する機能は、お考えでしょうか？
あるいは、デスクトップ版のOutlook でも良いかもしれません。デスクトップ版のOutlook であれば、Microsoft ExchangeもGoogleも両方対応しています。

Pleasanterをデモしたところ、タスク管理やプロジェクト管理のようなWebアプリケーションとカレンダー、予定の二重入力が発生することで、エンドユーザーが不便と感じてまして、カレンダー連携が出来ると、Pleasanter が使いやすくなります。

**Comment by Implem** [comment]
たしかに既存のカレンダーツールと連携できると需要が増えるかもしれませんね！
APIをつくる際に検討してみます。
