### ISSUE TITLE
一括削除でエラー発生

### ISSUE THREAD

**Issue by a0z0** [Implem/Implem.Pleasanter#140]
Pleasanter.0.49.167.25769

一覧画面の[一括削除]ボタンでエラーが発生します。
画面上では「アプリケーションで問題が発生しました。」
ログは以下の通り。

マルチパート識別子 "ClassF~595.ClassC" をバインドできませんでした。

   場所 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   場所 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   場所 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   場所 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   場所 System.Data.SqlClient.SqlDataReader.get_MetaData()
   場所 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   場所 System.Data.SqlClient.SqlCommand.ExecuteScalar()
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.<>c__DisplayClass14_0.<ExecuteScalar>b__0() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 120
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.Try(Action action) 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 168
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteScalar() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 122
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteScalar_response() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 222
   場所 Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteScalar_response(Context context, String connectionString, Boolean transactional, Boolean selectIdentity, Boolean writeSqlToDebugLog, SqlStatement[] statements) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataSources\Rds.cs:行 174
   場所 Implem.Pleasanter.Models.ResultUtilities.BulkDelete(Context context, SiteSettings ss, IEnumerable`1 selected, Boolean negative) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultUtilities.cs:行 7726
   場所 Implem.Pleasanter.Models.ResultUtilities.BulkDelete(Context context, SiteSettings ss) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultUtilities.cs:行 7678
   場所 Implem.Pleasanter.Controllers.ItemsController.BulkDelete(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 524
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by chanrai** [comment]
横から失礼いたします。こちらも同じ削除できない現象が発生しております。

原因が調べたいですが、上記のログがどこから取得したか教えて頂けますでしょうか？
WindowsのIISのログでは上記の内容がないので。

よろしくお願いします。

**Comment by a0z0** [comment]
サーバー上で SupportTools フォルダ内の Implem.SupportTools を実行して[SysLogビューア]から表示できます。

**Comment by chanrai** [comment]
ご回答ありがとうございます。

確認できました。こちらは「オブジェクト 'dbo.Items_deleted' には重複するキーを挿入できません。」の原因で削除失敗だそうです。

またよろしくお願いします。

**Comment by a0z0** [comment]
当方でエラーが発生する状況は、
リンクされたテーブルの項目でフィルタした状態で[一括削除]するとエラーになります。

**Comment by a0z0** [comment]
Pleasanter.0.49.177.24642 です。

[一括削除]ボタンでエラーは出なくなりましたが....

リンクしたテーブルでフィルタしている状態で[一括削除]しても「０件削除しました。」と表示されて削除されない(仕様?)ですが、(一覧には表示されており)削除されていないばすのレコードを表示しようとすると、「指定された情報は見つかりませんでした。」とエラーになります。
中途半端な状態で削除されているような気がします。

**Comment by a0z0** [comment]
修正されたようです。
