### ISSUE TITLE
【動作について質問】SycnByLdapによるLDAP同期時の動作について

### ISSUE THREAD

**Issue by kenji-tanaka-0123** [Implem/Implem.Pleasanter#141]
Ｌｄａｐの同期処理を試してみましたところ、
期待していた動作と違いましたので質問させてください。

Authentication.jsonで下記設定をしています。
RejectUnregisteredUser: true
AutoDisable: false
AuteEnable: false
。
【期待していた動作】
RejectUnregisteredUserが有効で、AutoEnableが無効なので、
登録されているユーザの情報をLDAPから同期する。

【実際の動作】
ＡＤに存在している全ユーザをＤＢに追加する。
登録されたユーザは無効化ユーザでなく有効化された状態となる。

ーー
動作及びLdap.csを見ているとRejectUnregisteredUserがSync内に判定記述がなさそうなので
そもそも同期処理時には一切考慮しないのが正解でしょうか。

Ldap.SyncのRds.ExecuteNonQuery自体はAutoDisable,AutoEnableのif文内にあるので、
そもそも動作してしまうのがおかしいでしょうか。

**Comment by Implem** [comment]
RejectUnregisteredUserは、SyncByLdapの処理では使用されていません。RejectUnregisteredUserは、Pleasanterに存在しないユーザでログインを試行した際にLDAPからユーザ情報を取得し、ユーザを自動作成する機能をOffにするフラグです。SyncByLdapで同期するユーザを絞り込みたい場合には、LdapSyncPatternsに検索条件を記述してください。
