### ISSUE TITLE
もう少し深い階層のリンク先項目を確認したい

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#143]
編集画面上で、もう少し深いリンク先の情報を確認したときがあります。
現状、子しか表示させることが出来ませんが、任意に孫やひ孫の項目が表示させられるような設定を追加することは可能でしょうか？

**Comment by Implem** [comment]
標準機能では実現できません。APIを使用して孫レコードの情報を取得し、画面表示する仕組みを開発してください。
