### ISSUE TITLE
レコードが削除できない

### ISSUE THREAD

**Issue by chanrai** [Implem/Implem.Pleasanter#145]
![error](https://user-images.githubusercontent.com/35596645/53776066-3582e500-3f38-11e9-8a9d-ca3f317fcacb.jpg)
APIにより作成したレコードが削除できない場合があります。

添付する画面キャプチャーのように、「一括削除」ボタンをクリックすると、「アプリケーションで問題が発生しました。」というエラーメッセージが表示されて、削除できませんでした。

ログが確認したら、「制約 'Pk_924a1f2e28dc1fdc5bbce20c02ab2f658f5803ad1162ec5d31e846b839bdc6ff' の PRIMARY KEY 違反。オブジェクト 'dbo.Items_deleted' には重複するキーを挿入できません。重複するキーの値は (10398) です。」のエラーになっています。

以上、よろしくお願いします。

**Comment by chanrai** [comment]
一応SQLServer側で'dbo.Items_deleted' にあるIDが直接削除することで、無事にプリザンター側から削除できましたが、そのようなバグが対応してほしいです。

**Comment by akiyamashino** [comment]
再現方法わからず、申し訳ないのですが、削除も一括削除もできません。
0.49.177.24642です。

●運用していて見つけた削除できないレコード２か所。以下、一か所の内容です。
制約 'Pk_924a1f2e28dc1fdc5bbce20c02ab2f658f5803ad1162ec5d31e846b839bdc6ff' の PRIMARY KEY 違反。オブジェクト 'dbo.Items_deleted' には重複するキーを挿入できません。重複するキーの値は (666192) です。

自分、理屈がわかっていないので手動で消せなくて。
どうなような対処をすれば
