### ISSUE TITLE
起動時に、値をNullにすることはできません

### ISSUE THREAD

**Issue by nasi2** [Implem/Implem.Pleasanter#147]
プリザンターのバージョンアップした所、起動時に
『System.ArgumentNullException: 値を Null にすることはできません。』
のエラーが発生してしまいます。対処方法を教えてください。

・0.48.7.20264 → 0.49.173.23021
・[#111](https://github.com/Implem/Implem.Pleasanter/issues/111)のALTER TABLEは、実施済
・フルテキスト検索はしていない
～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～
'/pleasanter' アプリケーションでサーバー エラーが発生しました。

値を Null にすることはできません。
パラメーター名:source 
説明: 現在の Web 要求を実行中に、ハンドルされていない例外が発生しました。エラーに関する詳細および例外の発生場所については、スタック トレースを参照してください。 

例外の詳細: System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:source
ソース エラー: 
現在の Web 要求の実行中にハンドルされていない例外が生成されました。障害の原因および発生場所に関する情報については、下の例外スタック トレースを使って確認できます。 
スタック トレース: 
[ArgumentNullException: 値を Null にすることはできません。
パラメーター名:source]
   System.Linq.Enumerable.Select(IEnumerable`1 source, Func`2 selector) +555
   Implem.Pleasanter.Libraries.Settings.Column.AddUsersToChoiceHash(Context context, Int64 siteId, String settings, IEnumerable`1 searchIndexes) in C:\Implem\Release\Implem.Pleasanter\Libraries\Settings\Column.cs:316
   Implem.Pleasanter.Libraries.Settings.<>c__DisplayClass103_0.<SetChoiceHash>b__2(<>f__AnonymousType15`2 data) in C:\Implem\Release\Implem.Pleasanter\Libraries\Settings\Column.cs:201
   Implem.Libraries.Utilities.Linqs.ForEach(IEnumerable`1 source, Action`1 action) in C:\Implem\Release\Implem.Libraries\Utilities\Linqs.cs:11
   Implem.Pleasanter.Libraries.Settings.Column.SetChoiceHash(Context context, Int64 siteId, Dictionary`2 linkHash, IEnumerable`1 searchIndexes) in C:\Implem\Release\Implem.Pleasanter\Libraries\Settings\Column.cs:208
   Implem.Pleasanter.Libraries.Settings.<>c__DisplayClass217_0.<SetChoiceHash>b__2(Column column) in C:\Implem\Release\Implem.Pleasanter\Libraries\Settings\SiteSettings.cs:2594
   Implem.Libraries.Utilities.Linqs.ForEach(IEnumerable`1 source, Action`1 action) in C:\Implem\Release\Implem.Libraries\Utilities\Linqs.cs:11
   Implem.Pleasanter.Libraries.Settings.<>c__DisplayClass215_0.<SetChoiceHash>b__1(SiteSettings ss) in C:\Implem\Release\Implem.Pleasanter\Libraries\Settings\SiteSettings.cs:2558
   System.Collections.Generic.List`1.ForEach(Action`1 action) +100
   Implem.Pleasanter.Libraries.Settings.SiteSettingsUtilities.ResultsSiteSettings(SiteModel siteModel, Context context, Int64 referenceId, Boolean setSiteIntegration, Boolean setAllChoices, TableTypes tableType) in C:\Implem\Release\Implem.Pleasanter\Libraries\Settings\SiteSettingsUtilities.cs:442
   Implem.Pleasanter.Libraries.Initializers.<>c.<Initialize>b__0_5(DataRow dataRow) in C:\Implem\Release\Implem.Pleasanter\Libraries\Initializers\ItemsInitializer.cs:285
   Implem.Libraries.Utilities.Linqs.ForEach(IEnumerable`1 source, Action`1 action) in C:\Implem\Release\Implem.Libraries\Utilities\Linqs.cs:11
   Implem.Pleasanter.Libraries.Initializers.ItemsInitializer.Initialize(Context context) in C:\Implem\Release\Implem.Pleasanter\Libraries\Initializers\ItemsInitializer.cs:321
   Implem.Pleasanter.MvcApplication.Application_Start() in C:\Implem\Release\Implem.Pleasanter\Global.asax.cs:30
[HttpException (0x80004005): 値を Null にすることはできません。
パラメーター名:source]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +520
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +176
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +165
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +267
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +341
[HttpException (0x80004005): 値を Null にすることはできません。
パラメーター名:source]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +523
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +107
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +688
バージョン情報: Microsoft .NET Framework バージョン:4.0.30319; ASP.NET バージョン:4.7.3282.0

**Comment by a0z0** [comment]
私も同じエラーが出たので、別サーバーに最新バージョンを新規インストールすると動作しました。
Updateに問題があるのではないかと推測されます。

**Comment by nasi2** [comment]
重要なヒントありがとうございました。
新規インストール後にデータ移行することで、なんとか復旧できました。
null文字列をTableに追加している場合に発生するみたいですが、まだ原因は絞り込めていません。

**Comment by nasi2** [comment]
Sitesテーブルが影響していることがわかりました。
SitesテーブルにPublishという項目が、追加されています。
とりあえず、次の手順でLogin画面が出るようになりました。

※旧バージョンのDBが必要です。
①旧サーバのSitesテーブルをCSVにエクスポートする。
　(MDBへのテーブルインポートでも可)
②Pleasanterを新サーバで0.49にUpdateする。
③移行後のSitesテーブルをTruncateする。
④①で保存したcsvにSiteSettings列を空に、Publish列を追加(,)する加工をしてインポートする。
⑤SSMSで、旧DBのSitesテーブルのSiteSettings項目をコピー、ペーストする。(1行づつ)
