### ISSUE TITLE
管理番号による検索

### ISSUE THREAD

**Issue by karoshima** [Implem/Implem.Pleasanter#15]
いつもお世話になってます。

トラブルチケットに管理番号を付与しているのですが、
その管理番号を使った検索がうまくいきません。
どのような指定をすれば良いでしょうか。

状況としては、

- 管理番号のフォーマットは "FF#WW17-0000" (弊社の記号+"#"+顧客の記号+年度+"-"+通番) です。
- 画面右上の検索欄に、ある特定のチケットの管理番号を入れて Enter すると検索結果には全てのチケットが出てきてしまいます。

単一のシートならフィルタで問題ないし、その場合にはうまく検索できるのですが、
ふたつのシートを跨いだ検索がやりたいため、画面右上の検索欄を使いたいなぁと思っているところです。

というわけで、検索欄に管理番号を入力するときの注意について
教えていただけたらと思います。
よろしくお願いします。

**Comment by Implem** [comment]
ご質問ありがとうございます。

プリザンターの検索ですが、SQL Serverのフルテキスト検索機能を有効化することで、精度や速度をあげることができます。もし、こちらを適用されていないようでしたら、お試しください。

https://implem.co.jp/2017/09/06/2182/

上記を適用しても改善しない場合には、入力する管理番号にシャープやハイフンをいれないように調整すると改善する可能性があります。SQL Serverのフルテキスト検索がどのように文字列を分かち書きするか正確に把握できていませんが記号に弱いといった傾向があると認識しております。

**Comment by karoshima** [comment]
ありがとうございます。スキを見て試してみます。

**Comment by Implem** [comment]
よろしくおねがいします！

**Comment by Implem** [comment]
一覧画面での検索でタイトルの前方一致検索という機能を付けました。管理番号がタイトルに設定されている場合、検索の精度を上げることができます。テーブルの管理→検索　から設定してください。

右上の全体を検索する機能には対応しません。
