### ISSUE TITLE
フォルダのコピーについて

### ISSUE THREAD

**Issue by chanrai** [Implem/Implem.Pleasanter#151]
添付する画面キャプチャーのように、「プロジェクト」というフォルダに「プロジェクトA」、「プロジェクトB」と「プロジェクトC」の３つテーブルがあります。

「プロジェクト」フォルダを複製すると、空のフォルダだけ生成されているが、中のテーブルが複製できません。

フォルダの中身も含まれる複製する方法があるでしょうか？

以上、よろしくお願いします。
![fold](https://user-images.githubusercontent.com/35596645/54588559-b678cb00-4a66-11e9-8617-6dc3b259429c.jpg)

**Comment by Implem** [comment]
現在のところ、フォルダ内のテーブルを一括でコピーする機能はございません。
