### ISSUE TITLE
ダークテーマ

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#155]
最近、ダークテーマがはやりなようで運用しているプリザンタでも適応したなと思っています。
(Windows10やEdgeなど設定しています）
適応したい一番の理由が夜勤中に白背景がきつい。DOS世代なもので黒に白文字がよいと言いう理由です。

他力本願なのですが、どなたかこのように設定したよと教えて頂ける方いらしゃいませんか？コピーさせて下さい。
smple.cssを見ましたが無理でした。

**Comment by Ooooooomin365** [comment]
試しに作ってみたのですが、以下はどうでしょうか？
少しでも参考になってもらえれば幸いです！

----------
body{ background-color: #333333;}
.item a{color:white;}
.separator{color:white;}
#ViewFilters{color:white;}
.grid-row{ background-color: #333333; color:white;}
.title a{color:white;}
#ReduceAggregations{color:white;}
.data{color:white;}
.status-new{color:black;}
.grid-row:hover{ background-color: #333333;}
table.grid tr:hover{ background-color: #333333;}
table#Grid tr:hover{ background-color: #333333;}
.grid-row:hover .grid-title-body{ background-color: #333333 !important;}
.svg-work-value {fill: white;}
.field-label{color:white;}
.crosstab-row td{color: white;}
.container-normal{color:white;}
----------

**Comment by akiyamashino** [comment]
今、気がつきました。ありがとうございます。

試して結果報告してみたいと思います。

ご親切にありがとうございます。

**Comment by akiyamashino** [comment]
試してみました。一覧表示がまさしくそれです。
ブログも拝見させて頂きました。

スプリクトの全てを選んでも新規作成や編集画面では適用されないようです。
今は時間が取れないですが、私も頑張ってみたいと思います。

大変ありがとうございました。
