### ISSUE TITLE
Open LDAP とは連携できるのでしょうか？

### ISSUE THREAD

**Issue by sayoko-iwahashi** [Implem/Implem.Pleasanter#158]
マニュアルにはActive Directory等のLDAPサービスと連携できると記載されいますが、Linux上のOpenLDAPにも連携できるのでしょうか？
実装された方はいらっしゃいますか？

**Comment by Implem** [comment]
.NET Frameworkの以下のライブラリを使用しております。他のLDAPとの連携も可能です。
System.DirectoryServices
