### ISSUE TITLE
項目「分類」の数を増やしたが有効にしても表示されない

### ISSUE THREAD

**Issue by kouishi27** [Implem/Implem.Pleasanter#159]
項目「分類」の数を増やしたい
https://github.com/Implem/Implem.Pleasanter/issues/20
を参考にさせて頂き項目A１～Z1を追加を行いました

結果、項目の追加は成功し
「テーブルの管理」→「エディタ」の選択し一覧にも表示されます。
しかし、A1を有効にしても、エディタで表示されません。

「テーブルの管理」→「一覧」で有効にすると一覧上には表示されます。

対応方法があれば教えて頂けませんでしょうか。

**Comment by Implem** [comment]
Enterprise Editionをご利用ください。

https://implem.co.jp/enterprise-edition/
