### ISSUE TITLE
多様なDBで利用できるようにしてほしい

### ISSUE THREAD

**Issue by yuntas** [Implem/Implem.Pleasanter#16]
素晴らしい OSS を提供して頂きありがとうございます。

マニュアルには `SQL Server` を利用した説明があります。

今後は MariaDB や MySQL 等さまざまな DB で利用できるようにしてほしいです。

**Comment by Implem** [comment]
Issueありがとうございます。

たしかにオープンソースのDBで動作できたほうがよいですね。少し時間がかかりそうですが、.NET Core対応と合わせて進めていきたいとおもいます。

**Comment by yang-jiayi** [comment]
yuntas ：一応、SQL Server 2017 on Linux版では動作します。ご参考ください。
