### ISSUE TITLE
情報公開機能の使い方を教えて下さい。

### ISSUE THREAD

**Issue by hatsu1119** [Implem/Implem.Pleasanter#163]
0.49.72で実装された情報公開機能はどのようにして使うのか教えて頂けないでしょうか？

試しにSitesテーブルのPublishカラムをtrueに変更すると，テーブル管理画面の上部に

「このテーブルは公開されています。ログインしていないユーザも閲覧可能です。」

のメッセージフィールドが表示されます．
このメッセージフィールドは，PublishesコントローラのURLにリンクされていて，そこに非ログインユーザでアクセスするとカスタムエラーのBadRequestに遷移して、画面下部に

「要求が不正です」

のエラーメッセージフィールドが表示されます．

**Comment by Implem** [comment]
管理→テナント管理と操作し、テナントレコードを作成します。
その後、データベースの[Tenants]テーブルの[ContractSettings]カラムに下記を登録してください。

```
{"Extensions":{"Publish":true}}
```
