### ISSUE TITLE
リンクされた子テーブルに対してインポートしても紐づかないデータがある

### ISSUE THREAD

**Issue by hiroshimitarai** [Implem/Implem.Pleasanter#165]
親テーブルと子テーブルを文字列「都道府県名(市区町村名)」でリンクしています。
その状態で子テーブルに対して、一覧画面のインポート機能からデータ一括登録を行っても、リンクされる都道府県名(市区町村名)とリンクされない都道府県名(市区町村名)があります。

子テーブルに複数同じ都道府県名(市区町村名)がある場合、全て成功か失敗で、一つの都道府県名(市区町村名)でリンク成功と失敗が混在することはありません。

複数回実行、2019/05/20 12:00の最新バージョン「0.49.236.35366」にしても、子テーブルでリンクが成功・失敗するのは同一になります。UTF8/S-JIS、改行コード未設定/CR+LF設定でも結果は同様です。

データベースを確認したところ、テーブル「Links」のカラム「DestinationId」が更新されておらず、カラム「DestinationId」を手動更新するとリンクが正常に張られます。

また、新規にサイト・テーブルをコピーした場合は、正常に一括登録できますが、既存サイト・テーブルにて解決策はあるのでしょうか？

**Comment by hiroshimitarai** [comment]
親テーブルと子テーブルのデータを全て一括削除して、親テーブル、子テーブルの順番にデータのインポートを行いましたが、リンクが設定される都道府県名(市区町村名)と設定されない都道府県名(市区町村名)はデータ入れ替え前と同一になっています。

**Comment by Implem** [comment]
リンクされた項目のインポート処理に不具合がありました。修正版を公開致しました。
