### ISSUE TITLE
ダイアログで編集no

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#168]
いつも便利に使わせて頂いています。ご報告です。
0.49.245.30151。
クライアント：Windows10 home(1803)、Edge。

一覧のダイアログで編集にチェックを入れて一覧を表示。
そこで編集して更新し一覧へ戻ると表示がずれている。
多分ですが、ビューと一覧とで差異があるとなるようです。

ちなみにレコードの遷移にAjaxを使用のON/OFFは動作に変化なかったです。

**Comment by akiyamashino** [comment]
タイトル入力の途中で送ってしまいました。
ダイヤログで編集の動作です。

**Comment by akiyamashino** [comment]
0.50.13.10721で改善されていること確認しました。ありがとうざいます。

**Comment by Implem** [comment]
ご連絡ありがとうございます。ご指摘のとおりビューによる項目の切り替えに対応できない問題がございましたので、修正いたしました。
