### ISSUE TITLE
Markdownの表記

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#169]
[link](url){:target="_blank"}や</u>が使用できるとよいのですが。

（編集中に参考しながら入力するサイトをタブを切り替えながらしたいなと思いまして）

よろしくお願いいたします。

仕様だと思いますが、ダイヤグラムで編集にチェックを入れると編集ウィンドウにガイドがでないです。

**Comment by Ooooooomin365** [comment]
以下のスクリプトを追加して、出力先を「編集」「一覧」にすると通常通りのMarkdownでも別タブで開いてくれそうです。

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script language="JavaScript">$(document).ready( function(){
$("a[href^='http']").attr('target','_blank');
})
</script>
　　　
参考記事のURL→[Markdown記法でリンクをtarget=”_blank”にする方法](https://decoy284.net/markdown-link-target-blank/)


   もしくは単純にリンクを右クリックして「新しいタブで開く」をクリックするのも良いかと思います（そちらの方が単純かもしれませんが...）。

**Comment by akiyamashino** [comment]
ありがとうございます。今、気がつきました。すみません。

ご親切にありがとうございます。

**Comment by akiyamashino** [comment]
まさしくこれです！！！。ありがとうございます。

Ooooooomin365様、他にもいろいろアドバイスありがとうございます。感謝です。
