### ISSUE TITLE
カレンダー表示が出来ない

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#170]
Ver 0.50.3.18215にてカレンダー表示を行うと、errorsページに自動的にリダイレクトされます。

該当事象発生時のSysLogは下記の通りです。

ログ1
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.HiddenData(HtmlBuilder hb, Context context, SiteSettings ss) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 429
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.<>c__DisplayClass17_0.<Error>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 470
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 84
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.<>c__DisplayClass1_0.<Container>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 85
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 84
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.Container(HtmlBuilder hb, Context context, String body, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 85
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.Error(Context context, ErrorData errorData, String[] messageData) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 467
   場所 Implem.Pleasanter.Controllers.ErrorsController.Index() 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ErrorsController.cs:行 18
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

ログ2
   場所 System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   場所 System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   場所 Implem.Pleasanter.Libraries.DataSources.Rds.ResultsColumn(ResultsColumnCollection self, String columnName, String _as, Functions function) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataSources\Rds.cs:行 90631
   場所 Implem.Pleasanter.Models.ResultUtilities.CalendarDataRows(Context context, SiteSettings ss, View view, Column fromColumn, Column toColumn, DateTime begin, DateTime end) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultUtilities.cs:行 3791
   場所 Implem.Pleasanter.Models.ResultUtilities.Calendar(Context context, SiteSettings ss) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultUtilities.cs:行 3593
   場所 Implem.Pleasanter.Controllers.ItemsController.Calendar(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 60
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by akiyamashino** [comment]
私もです。記録テーブルしか試していませんが。

**Comment by kazuca** [comment]
デバッグしてみました。記録テーブルを読み出す時に、ToDateカラムをNullで返しているようですが、それが原因でContainsKeyがNullExceptionを吐いているようです。

**Comment by kazuca** [comment]
0.50.7.22366での症状が発生しないことを確認出来ました。

**Comment by Implem** [comment]
ご連絡ありがとうございます。ご指摘のとおりnull参照の問題がありましたので、修正いたしました。
