### ISSUE TITLE
更新を行うとエラーが発生する

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#171]
Ver 0.50.3.18215にて更新を行うとエラーが発生し、通知処理が行われません。
更新自体は問題無く行われているようです。

同一のキーを含む項目が既に追加されています。
場所 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   場所 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   場所 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   場所 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   場所 Implem.Pleasanter.Libraries.Models.Summaries.Data(Context context, SiteSettings ss, String destinationColumn, IEnumerable`1 destinations, Int64 sourceSiteId, String sourceReferenceType, String linkColumn, String type, String sourceColumn, View sourceCondition) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Libraries\Models\Summaries.cs:行 415
   場所 Implem.Pleasanter.Libraries.Models.Summaries.SynchronizeResults(Context context, SiteSettings ss, SiteSettings destinationSs, Int64 destinationSiteId, String destinationColumn, View destinationCondition, Boolean setZeroWhenOutOfCondition, Int64 sourceSiteId, String sourceReferenceType, String linkColumn, String type, String sourceColumn, View sourceCondition, Int64 resultId) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Libraries\Models\Summaries.cs:行 304
   場所 Implem.Pleasanter.Libraries.Models.Summaries.Synchronize(Context context, SiteSettings ss, SiteSettings destinationSs, Int64 destinationSiteId, String destinationReferenceType, String destinationColumn, View destinationCondition, Boolean setZeroWhenOutOfCondition, Int64 sourceSiteId, String sourceReferenceType, String linkColumn, String type, String sourceColumn, View sourceCondition, Int64 id) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Libraries\Models\Summaries.cs:行 90
   場所 Implem.Pleasanter.Models.IssueModel.SynchronizeSummary(Context context, SiteSettings ss, Summary summary, Int64 id) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 1848
   場所 Implem.Pleasanter.Models.IssueModel.<>c__DisplayClass66_0.<SynchronizeSummary>b__0(Summary summary) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 1820
   場所 System.Collections.Generic.List`1.ForEach(Action`1 action)
   場所 Implem.Pleasanter.Models.IssueModel.SynchronizeSummary(Context context, SiteSettings ss, Boolean force) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 1812
   場所 Implem.Pleasanter.Models.IssueModel.Update(Context context, SiteSettings ss, IEnumerable`1 permissions, Boolean permissionChanged, Boolean extendedSqls, Boolean synchronizeSummary, Boolean forceSynchronizeSourceSummary, Boolean notice, SqlParamCollection param, List`1 additionalStatements, Boolean otherInitValue, Boolean setBySession, Boolean get) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 1097
   場所 Implem.Pleasanter.Models.IssueUtilities.Update(Context context, SiteSettings ss, Int64 issueId) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 2152
   場所 Implem.Pleasanter.Models.ItemModel.Update(Context context) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Models\Items\ItemModel.cs:行 1394
   場所 Implem.Pleasanter.Controllers.ItemsController.Update(Int64 id) 場所 D:\Implem.Pleasanter\Implem.Pleasanter\Controllers\ItemsController.cs:行 514
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by kazuca** [comment]
0.50.7.22366での症状が発生しないことを確認出来ました。

**Comment by Implem** [comment]
ご連絡ありがとうございます。サマリが設定されているテーブルで更新時にエラーが発生する問題がございましたので修正いたしました。
