### ISSUE TITLE
API経由でレコードの更新が出来ない

### ISSUE THREAD

**Issue by Connie-Wild** [Implem/Implem.Pleasanter#172]
v49.150では正常に更新が出来ましたが、v50.5にアップデートした所
{'Id': 0, 'StatusCode': 500, 'Message': 'この操作を行うための権限がありません。'}
のエラーが表示され、更新不可となりました。
APIキーを発行したユーザはAdminなので権限が足りない事は無いかと思います。
また、getはできるのでupdateのみ不可の様です。
ご確認お願いします。

**Comment by Implem** [comment]
ご連絡ありがとうございます。読み取り専用の項目があるとチェックにひっかかる問題がありましたので、修正いたしました。

**Comment by Connie-Wild** [comment]
ご対応ありがとうございました。

**Comment by Connie-Wild** [comment]
v50.15にアップデートしました。
{'Id': 0, 'StatusCode': 500, 'Message': 'この操作を行うための権限がありません。'}
のエラーは発生しなくなりましたが、代わりに
{"Message":"エラーが発生しました。"}
が発生するようになりました。
更新している項目はDescription、Num、Class、Dateになります。
DBのdbo.Syslogを確認しましたが、エラーの内容が出力されていなく、手がかりがありませんでした。
お手数おかけして申し訳ございませんが、ご確認お願いします。

**Comment by Connie-Wild** [comment]
v50.23にてAPIからレコード更新ができる事を確認しました。
対応ありがとうございました。
