### ISSUE TITLE
新規作成が出来ない

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#173]
Ver 0.50.7.22366にて、管理権限が無いと項目の追加が出来なくなっているテーブルがあります。
該当するテーブルは一覧時の左端のチェックボックスカラムが表示されなくなっています。

**Comment by Implem** [comment]
一覧画面で子テーブルの項目を表示している場合、左端のチェックボックスが無効になります。項目の追加ができないというのは、具体的にどのような動きでしょうか。

**Comment by kazuca** [comment]
「この操作を行うための権限がありません」と表示されます。

作成をクリックするとエラーが表示される
![権限エラー](https://user-images.githubusercontent.com/37392077/59186411-bee82a00-8bad-11e9-91b9-6f9276497a9a.png)

チェックボックスが消えている
![チェックボックスが表示されない](https://user-images.githubusercontent.com/37392077/59186410-be4f9380-8bad-11e9-930d-701b45f458ab.png)

**Comment by kazuca** [comment]
拡張SQLで同一テーブル内のデータを更新させています。

 NumA + DateA → DateB(日付の加算処理を行う)

このとき、DateBを読み取り専用で編集画面内に表示させていました。
この表示を外すと正常にデータの新規作成を行うことが出来ました。

**Comment by Implem** [comment]
ご連絡ありがとうございます。ReadOnly設定で計算式等での書き換えができない問題がありましたので修正いたしました。

**Comment by kazuca** [comment]
0.50.30.31939で解決していることが確認出来ました。
ありがとうございます。
