### ISSUE TITLE
質問：item更新APIによるDateTime型更新について

### ISSUE THREAD

**Issue by hiroshimitarai** [Implem/Implem.Pleasanter#175]
DateTime型に「2019/06/11 00:00:00」が格納されている場合、
item更新APIによる日付更新を行った場合、該当項目に「2019/06/10 16:00:00」がセットされ、
日付「2019/06/10」が表示されます。

APIKeyを使用しているユーザのタイムゾーンは東京ですが、GMTが適用されているように見えます。

「2019/06/11 00:00:00」を文字列変換してAPI更新を行った場合は正常に日付「2019/06/11」が表示されます。

ご確認、よろしくお願いします。

**Comment by Implem** [comment]
ご連絡ありがとうございます。日付項目の時刻ロケールの変換が正しく行われておりませんでしたので、修正いたしました。

**Comment by hiroshimitarai** [comment]
バージョン「0.50.23.28098」で検証しましたが、修正されていないようです。
どのバージョンから修正が反映されますでしょうか。

**Comment by Ooooooomin365** [comment]
バージョン「0.50.49.24829」では反映されていましたよ～！

**Comment by hiroshimitarai** [comment]
@Ooooooomin365 さん
ありがとうございます。

バージョン「0.50.62.15463」で動作確認してみましたが、日付がずれます。
Windowsフォームアプリケーション(.Net)から更新APIにより日付更新しているのですが、
DateTime型、DateTimeOffset型ともに-8時間(GMT+サマータイム)の日時がセットされるようです。

**Comment by hiroshimitarai** [comment]
バージョン「0.50.92.16409」でも時間のずれが発生していますが、
toStringで文字列として扱えば問題ないため、本件クローズします
