### ISSUE TITLE
ファイル保存をDBからストレージに変更すると画像が表示されない

### ISSUE THREAD

**Issue by YoshikiSawada** [Implem/Implem.Pleasanter#177]
BinaryStorage.jsonでファイル保存をDBからストレージに変更すると、
「説明A~Z」に画像を登録しても表示されなくなります。

・登録した添付ファイル、画像ファイルともに指定のフォルダに格納されます。
・登録した添付ファイルはリンクが表示されます。
・登録した画像ファイルはリンク切れの表示になります。

ファイルを登録すると、DBテーブル「Binaries」にレコードが作成されますが、
「ファイル保存をストレージに変更　かつ　画像を登録」した時はレコードが
作成されません。
試しに、手動でレコード追加すると画像が表示されました。

DBサイズの増大を抑制するため、ファイルはストレージ保存にしたいので、
何らかの対処方法がありましたらご教示ください。

**Comment by Implem** [comment]
ローカルストレージを使用する処理に不具合がありました。修正版を公開致しました。

**Comment by YoshikiSawada** [comment]
ありがとうございます。
バージョンアップして、ファイル保存をストレージに変更したところ、
アップロードした画像が表示されることを確認いたしました。
