### ISSUE TITLE
Develop環境で開発したものをMaster環境にデプロイしたい

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#18]
Azureで2つWebAppを立てて、Develop環境用WebAppで構築してうまく試用できたものを
Master環境用WebAppにデプロイして運用する、という開発スタイルを取りたいのですが、
テーブル単体でなくシステム全体のエクスポート、もしくはシステムの（ソースの）Git管理などは可能でしょうか？
可能な場合、どのようにすればいいかご教授いただけますと幸いです。

**Comment by Implem** [comment]
Issueありがとうございます。

プリザンターで設定したテーブルは、SitesテーブルのSiteSettingsという項目にJson形式で格納されています。こちらをDevelopからMaster環境にコピーしていただくことで対応可能と考えております。ただ、テーブルのリンク等を行っている場合には、各テーブルのSiteIdが異なってしまいますので、これを同一にするか、コピーする際にJson内のSiteIdを変換していただくようおねがいします。

**Comment by yyuki23** [comment]
承知いたしました。
できそうとのことで、安心しました。ありがとうございます。
試して、また返信させていただきます。
