### ISSUE TITLE
リンク子テーブルの編集画面で親テーブルの IDが表示される

### ISSUE THREAD

**Issue by alpha21264** [Implem/Implem.Pleasanter#180]
いつも便利に利用させて頂いております。

さて、先日 0.49.246 ⇒ 0.50.23にバージョンアップしてから
リンク 子テーブルの編集画面で 親テーブルの項目【読取専用】に
IDが表示されるようになってしまいました。

一覧表示では問題無く 親テーブルの内容が表示されており、
子テーブルの編集画面で更新を実行すると正しく内容が表示され、
再度、編集画面に戻ると IDの表示に戻ってしまいます。

私の方で 0.49 ⇒ 0.50のバージョンアップ時に
何か手順の間違いがあったのでしょうか？

回答の程よろしくお願い致します。

**Comment by Implem** [comment]
ご連絡ありがとうございます。リンク項目を読み取り専用にした際にご指摘の問題が発生する不具合がございましたので修正いたしました。

**Comment by alpha21264** [comment]
早速の対応ありがとうございました。
0.50.30にて修正されている事を確認致しました。
