### ISSUE TITLE
数値フィールド【書式:通貨】の ￥マークの取り扱い

### ISSUE THREAD

**Issue by alpha21264** [Implem/Implem.Pleasanter#181]
いつも便利に利用させて頂いております。

さて、先日 0.49.246 ⇒ 0.50.23にバージョンアップしてから
数値フィールド【書式：通貨】にて初期表示 "￥0"の状態で、
"￥10"と入力すると エラーと判断され "￥0"に戻ってしまうようです。

"10"と入力すれば "￥10"と正しく表示されますので、
入力チェック時の "￥"の取り扱いが変わったのでしょうか？

お忙しいところ大変申し訳ございませんが、
ご確認の程よろしくお願い致します。

**Comment by Implem** [comment]
ご連絡ありがとうございます。円マークのついた数値の入力が行えない問題がございましたので修正いたしました。

**Comment by alpha21264** [comment]
早速の対応ありがとうございました。
0.50.30にて修正されている事を確認致しました。
