### ISSUE TITLE
トップページとメニューのカスタマイズ

### ISSUE THREAD

**Issue by kno561981** [Implem/Implem.Pleasanter#184]
ログイン画面トップページをカスタマイズしたいです。
ロゴマーク変更、リンク文字、リンク先、ブラウザに表示されるタイトル、
文言の追記など。

それと、ログイン後にユーザー名の下に出てくるメニューも変更したいです。
リンク先を無くすことはできましたが、メニュー自体の表示を削りたいです。
場合によってはメニューを個人的に追記もしたいです。

**Comment by Implem** [comment]
標準機能では対応していないため、JavaScriptやCSSを使用してカスタマイズしてください。
