### ISSUE TITLE
サイト統合先のテーブルでの一覧表示時のタイトル異常

### ISSUE THREAD

**Issue by makotookamura** [Implem/Implem.Pleasanter#186]
いつもお世話になっております。
サイト統合先のテーブルで一覧表示したときに、タイトル名が想定通り表示されません。

元のサイトでは、エディタにてタイトルを複数項目の連結で表示するように設定しており、一覧表示上もそのタイトルが表示されます。
しかし、サイト統合先のサイトでは連結後の項目ではなく、直接入力するタイトル項目を読んでいるようです。
なお、カレンダーやカンバンでは問題なく連結後の項目が表示されます。
ご確認のほどよろしくお願いいたします。

バージョン：0.50.35.34152

**Comment by Ooooooomin365** [comment]
バージョン：0.50.49.15515 にて、「期限付きテーブル+期限付きテーブル」「記録テーブル+記録テーブル」の2パターンで同内容を行ってみましたが（タイトルの項目連結数はそれぞれ2つ）、特に問題はなさそうでしたよ～！

**Comment by makotookamura** [comment]
@Ooooooomin365 
情報共有ありがとうございます！
後ほどバージョンアップ確認してクローズ致します！

**Comment by makotookamura** [comment]
問題の解消を確認致しました。
ありがとうございます。
