### ISSUE TITLE
Create/Update時にExceptionが発生する

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#187]
全てのリンク項目に発生するわけではないのですが、下記の様なエラーが出て、作成・更新を受け付けてくれません。
ClassCに割り当ててあるリンクを解除すると症状が発生しないため、リンクが原因であるようです。

`マルチパート識別子 "ClassC~223662.ClassA" をバインドできませんでした。`

`   場所 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   場所 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   場所 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   場所 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   場所 System.Data.SqlClient.SqlDataReader.get_MetaData()
   場所 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   場所 System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   場所 System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   場所 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   場所 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.Try(Action action) 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 169
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteDataSet() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 130
   場所 Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteDataSet(Context context, String connectionString, Boolean transactional, Boolean writeSqlToDebugLog, SqlStatement[] statements) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataSources\Rds.cs:行 211
   場所 Implem.Pleasanter.Models.IssueModel.GetNotifications(Context context, SiteSettings ss, Boolean notice, Boolean before, TableTypes tableTypes) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 2179
   場所 Implem.Pleasanter.Models.IssueModel.Update(Context context, SiteSettings ss, IEnumerable`1 permissions, Boolean permissionChanged, Boolean extendedSqls, Boolean synchronizeSummary, Boolean forceSynchronizeSourceSummary, Boolean notice, SqlParamCollection param, List`1 additionalStatements, Boolean otherInitValue, Boolean setBySession, Boolean get) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 1053
   場所 Implem.Pleasanter.Models.IssueUtilities.Update(Context context, SiteSettings ss, Int64 issueId) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 2187
   場所 Implem.Pleasanter.Controllers.ItemsController.Update(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 514
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)`

**Comment by kazuca** [comment]
他の分類にリンク項目を移したところ、問題が発生しなくなりました。

**Comment by Implem** [comment]
平均値を求めるサマリの処理に不具合がありました。修正版を公開致しました。
