### ISSUE TITLE
項目「分類」の数を増やしたい

### ISSUE THREAD

**Issue by mitsu716** [Implem/Implem.Pleasanter#188]
#20 にて、同内容が投稿されておりましたが、 2019/06/05のバージョンアップにより、「Implem.Pleasanter/App_Data/Definitions/definition_Column.xlsm」のファイル内にClassA～Zの行がなくなった模様です。

現在のバージョンでは、どのように項目を増やすことができるか、教えていただけませんでしょうか。

**Comment by Ooooooomin365** [comment]
https://pleasanter.net/fs/publishes/378192/edit

こちらに2019年3月時点での回答がありましたが、おそらくEnterprise Editionを利用しないといけない気がします。

**Comment by Implem** [comment]
こちら、Enterprise Editionをご利用ください。
入手方法は下記よりお問い合わせください。

https://implem.co.jp/contact/
