### ISSUE TITLE
新規作成時に「アプリケーションで問題が発生しました。」「値を Null にすることはできません。」

### ISSUE THREAD

**Issue by koikoi0407** [Implem/Implem.Pleasanter#189]
【利用バージョン】
0.50.70.24211
【現象】
新規作成時に「アプリケーションで問題が発生しました。」を表示
尚、データは登録されている。
【切り分け】
・通知を設定していると発生。
・該当通知を無効にすると発生しない。
【Syslog】
ErrMassage:値を Null にすることはできません。パラメーター名:pattern
ErrStackTrace
   場所 System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   場所 System.Text.RegularExpressions.Regex.Matches(String input, String pattern, RegexOptions options)
   場所 Implem.Libraries.Utilities.Regexes.RegexFirst(String self, String pattern, RegexOptions regexOptions) 場所 C:\Implem\Release\Implem.Libraries\Utilities\Regexes.cs:行 12
   場所 Implem.Pleasanter.Libraries.Mails.Addresses.BadAddress(Context context, String addresses) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Mails\Addresses.cs:行 52
   場所 Implem.Pleasanter.Libraries.Settings.Notification.Send(Context context, SiteSettings ss, String title, String url, String body) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Settings\Notification.cs:行 130
   場所 Implem.Pleasanter.Models.IssueModel.<>c__DisplayClass75_0.<Notice>b__0(Notification notification) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 2289
   場所 System.Collections.Generic.List`1.ForEach(Action`1 action)
   場所 Implem.Pleasanter.Models.IssueModel.Notice(Context context, SiteSettings ss, List`1 notifications, String type) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 2290
   場所 Implem.Pleasanter.Models.IssueModel.Create(Context context, SiteSettings ss, TableTypes tableType, SqlParamCollection param, Boolean extendedSqls, Boolean synchronizeSummary, Boolean forceSynchronizeSourceSummary, Boolean notice, Boolean otherInitValue, Boolean get) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueModel.cs:行 951
   場所 Implem.Pleasanter.Models.IssueUtilities.Create(Context context, SiteSettings ss) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 2054
   場所 Implem.Pleasanter.Controllers.ItemsController.Create(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 474
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by kazuca** [comment]
バージョンアップを行ったときにMail.jsonを旧バージョンからコピーして使い回していませんか？
AddressValidationというパラメータが1つ追加されています。そのパラメータを追加する必要があります。

**Comment by koikoi0407** [comment]
早速のアドバイス、ありがとうございます。
バージョンアップを行ったときにMail.jsonを旧バージョンからコピーして使い回していませんか？
⇒その通りでした。
AddressValidationというパラメータが1つ追加されています。そのパラメータを追加する必要があります。
⇒追加したら問題なく新規作成が出来ました。

大変助かりました、ありがとうございました。
