### ISSUE TITLE
スクリプトの使い方を教えてください

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#19]
インシデント管理システムを構築しております。
インシデント発行時に他社サービスのAPIを叩くようなことをしたいのですが、
スクリプト欄の使い方が詳細に書かれているページなどはありますでしょうか？
```
例
レコード新規作成時に、開発チームが利用している別サービスのAPIを叩いて
開発チーム向けに作業チケットを自動で作成したい
```

**Comment by Implem** [comment]
Issueありがとうございます。

現在、スクリプトについて詳細に説明したページが無く、ご不便をおかけしております。基本的には一覧画面、新規作成画面、編集画面に生のJavaScriptを出力する仕様となっていますので、こちらを使用して外部システムとの連携を行ってください。jQueryのメソッドは利用可能です。

**Comment by yyuki23** [comment]
ご返信ありがとうございます。
こちらの方で試行錯誤してみます。
また何かWikiなど進展がありましたらご連絡頂けますと幸いです。
