### ISSUE TITLE
子テーブルの計算式で親テーブルの項目を使う方法

### ISSUE THREAD

**Issue by ryuchan1001** [Implem/Implem.Pleasanter#190]
リンクした子テーブルの数値項目に、子テーブルの数値項目と親テーブルの数値項目を計算した結果を入れたいのですが、方法がわかりません。

計算式にはリンク先の親テーブルの項目を含めることはできないようですが、何か方法があればご教授ください。

**Comment by Implem** [comment]
標準機能では計算式に他のテーブルの項目を含めることができません。
拡張SQLやAPIのご利用をご検討ください。
