### ISSUE TITLE
バージョンアップ時にエラー表示

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#191]
ご報告です。
0.50.83にバージョンアップ時に以下の表示が出ます。

<ERROR> <>c.<Configure>b__0_0: [7613] インデックス 'Pk_9e8dbe0a44efcdbd7a7d5ad98b70012dd0693b1dc10aaa231db1abd7b840dddd' を削除できません。このインデックスにより、テーブルまたはインデックス付きビュー 'Binaries' にフルテキスト キーが設定されています。
制約を削除できませんでした。以前のエラーを調べてください。
<INFO> TablesConfigurator.ConfigureTableSet: Permissions
<INFO> TablesConfigurator.ConfigureTableSet: Issues
<INFO> TablesConfigurator.ConfigureTableSet: Results
<INFO> TablesConfigurator.ConfigureTableSet: Wikis
<SUCCESS> Starter.ConfigureDatabase: Database configuration is complete.
<ERROR> Starter.Main: There were 1 errors. Please check the log file (C:\Users\akis\Downloads\Pleasanter.0.50.83.34131\Pleasanter\logs\Implem.CodeDefiner_20190722_130334.log).
続行するには何かキーを押してください . . .

**Comment by yang-jiayi** [comment]
このIndex(Pk_9e8dbe0a44efcdbd7a7d5ad98b70012dd0693b1dc10aaa231db1abd7b840dddd)は、Binariesテーブルにあるはずで、このBinariesテーブルにFullText Index Keyを構成されたのでしょうか。
もし、構成された場合、一度FullTextを無効にしてから、再度試してみてください。

https://blog.jssug.jp

**Comment by akiyamashino** [comment]
ご親切にありがとうございます。

インデックスを削除して再度、フルテキスト有効化してバージョンアップはエラーなく終了しましたが、検索インデックの再構築をしてもヒットしない項目が多くて常用、出来ませんでした。
解決方法が分からない為、推奨されてないバージョンダウン(83→70)をして使用しています。

**Comment by yang-jiayi** [comment]
> ご親切にありがとうございます。
> インデックスを削除して再度、フルテキスト有効化してバージョンアップはエラーなく終了しましたが、検索インデックの再構築をしてもヒットしない項目が多くて常用、出来ませんでした。
> 解決方法が分からない為、推奨されてないバージョンダウン(83→70)をして使用しています。

削除する必要はあったっけ？無効にすれば、後再度有効に戻したらどうかなと…思いました。

**Comment by akiyamashino** [comment]
少々、お待ち下さい。現在、テスト環境再構築中でして。

　新しく作り直している環境でプリザンタのリストアが出来なくて。ssmsでリストアのバックアップファイルを
選択しようとするとフリーズをしてしまって。まだ、試行錯誤していると途中でSSMSのバージョンダウンなど試しているところです。
以前の環境では問題なく出来ていたので・・・。
（昔、使用していたサーバをOSからクリーンインストールしています。）

**Comment by akiyamashino** [comment]
テスト環境で試そうとしても再現しなくなりました。
（今、本番環境をいじるのは怖いので。）

リストアできなかった原因は、ssmsのバージョンが18.0と18.1はダメで17.9.1はOKでした。

大変、ありがとうございました。クローズします。

**Comment by akiyamashino** [comment]
後日談ですが、本番環境でもssmsを17.9.1にダウングレードしてからプリザンタをアップデートしたら問題なく出来ました。たまたまかもしれませんが。
