### ISSUE TITLE
クラウド版のAPIのエンドポイントについて

### ISSUE THREAD

**Issue by gothedistance** [Implem/Implem.Pleasanter#192]
ドキュメントには、以下のような記載がなされています。

> 下記のURLを使用します。{SiteId}はレコードを作成するテーブルのサイトIDに置換してください。
> http://servername/pleasanter/api/items/{SiteId}/create

これは自分でPlesanterを立てた場合のエンドポイントのようなので、クラウドの版のAPIのエンドポイントについて教えてほしいです。

どうぞよろしくお願い致します。

**Comment by Implem** [comment]
こちらのURLをご利用ください。

https://pleasanter.net/fs/api/items/{SiteId}/create
