### ISSUE TITLE
API更新時にリンクが解除される

### ISSUE THREAD

**Issue by tuggyz** [Implem/Implem.Pleasanter#193]
APIを使って、下記、テーブル２の分類Aを更新した場合、
リンクが設定されず「？項目内容」と表示されます。
これは仕様でしょうか？APIを用いたリンク項目の更新方法はありますか？
（※インポートの場合はリンクOK、APIの場合リンクNG）

API更新前）
リンク関係あり
　親：サイト１、レコードID：１００、タイトル：”０１２３４”
　子：サイト２、レコードID：２００、分類A：”０１２３４”　→　レコードID：１００
API更新）
　サイト２、レコードID：２００、分類A：”０１２３４”の値で更新
API更新後）
　リンクが外れる。分類A：”？０１２３４”となる

**Comment by Implem** [comment]
APIでリンク項目を更新する場合ですが、タイトルではなくレコードIDを渡す必要がございます。上記の例の場合、200を送信するようにしてください。
