### ISSUE TITLE
検索ができない

### ISSUE THREAD

**Issue by mnori0102** [Implem/Implem.Pleasanter#194]
WindowsServer2012
MSSQL2017 exp

上記環境で、OSSのPleasanterを展開したが、検索がうまくいかない。

以下を参考にして、対応したが、何一つ引っかからない。
https://pleasanter.net/fs/publishes/252025

対応策ないでしょうか。

**Comment by a0z0** [comment]
何回か「プリザンターのフルテキスト検索機能を有効化する」手順通りに設定しましたが、
問題に遭遇したことはないです。
SQL Server 2017 Express with Advanced Services のインストールオプションとか間違えてないでしょうか
