### ISSUE TITLE
添付ファイル（一括登録について）

### ISSUE THREAD

**Issue by miyaken55** [Implem/Implem.Pleasanter#195]
使わなくなるシステムのデータをプリザンターに統合する提案を考えてます。
※過去データ参照用に保存したい。サーバーは廃棄。

データの登録はCSV一括登録を考えていましたが、それぞれのデータに添付ファイルも登録されています。
添付ファイルも含めた一括登録の方法があるのでしょうか？
無理な場合、こういうやり方をしているなどのアイディアがあればご教示いただけないでしょうか。

**Comment by Implem** [comment]
標準っ機能にはありませんので、Binariesテーブルに投入するプログラムを作成する必要があります。Binariesテーブルに入れたGUIDはIssuesまたはResultsテーブルのAttachments項目のjsonからリンクすることで利用可能となります。

**Comment by miyaken55** [comment]
ご回答ありがとうございます。確認してみました。
itemsテーブルにも投入は必要ですよね？
それとも一度csvでデータを投入して、添付ファイルに関する部分だけBinaries、Resultsをアップデートする形のほうがよいでしょうか？

また、申し訳ございません。
当該の画像ファイルはどこに格納しておけばよいでしょうか。
