### ISSUE TITLE
機能リクエスト：社内Proxy環境下におけるTeams連携

### ISSUE THREAD

**Issue by junichimurata** [Implem/Implem.Pleasanter#197]
お世話になります。

社内Proxy環境下にてプリザンターを使用させて頂いておりますが、
TeamsをProxy環境下でも送信できるようにご対応頂くことは可能でしょうか？

よろしくお願い致します。

**Comment by Implem** [comment]
ご要望ありがとうございます。開発チームで実現可否検討いたします。
