### ISSUE TITLE
質問：複数取得APIの仕様について

### ISSUE THREAD

**Issue by ghost** [Implem/Implem.Pleasanter#198]
複数取得APIの仕様について何点か質問させてください。

１．ColumnFilterHashでDescriptionA-Zの場合、あいまい検索できますが日本と設定した場合、日付など「日」が入っているものも取得されますが、こちらは仕様でしょうか？

２．ColumnFilterHashでClassA-Zの場合、あいまい検索はできないのでしょうか？

３．ColumnFilterHashでClassA-Zの場合、"ClassA":"[1,2,3,～,n]"と設定した場合、n=1046まではレスポンスコード200で正常に取得できましたが、n=>1047の場合、レスポンスコード500が返却されます。Classの設定値は1046が上限でしょう？

ご確認の程、よろしくお願いいたします。

**Comment by hiroshimitarai** [comment]
一部、確認ができましたので記載します。

１．全文検索に用いるデータベースのインデックス作成等に依存します。

２．ColumnFilterHashでClassA-Zの場合、あいまい検索はできませんが、ClassA-Zの選択肢を手動入力した場合はあいまい検索が可能です。

３．お判りになる方、ご回答お待ちしております。
