### ISSUE TITLE
スクリプト作成。各項目名を教えてください　class=分類　他は？

### ISSUE THREAD

**Issue by suzukihu** [Implem/Implem.Pleasanter#199]
スクリプトを作成する際に、「分類」「数値」「説明」「チェック」「日付」それぞれの名称を教えてください。

分類＝class
これは調べて分かりました。他をご存知の方、お願いいたします。

**Comment by a0z0** [comment]
ブラウザのデバッグツールで該当フィールドのHTMLを探せばわかります。

**Comment by suzukihu** [comment]
a0z0様
ありがとうございます！
