### ISSUE TITLE
特定の検索ワードで検索するとアラートが出る

### ISSUE THREAD

**Issue by kobake** [Implem/Implem.Pleasanter#2]
「予約」で検索したらアラートが出ました。（他の人に試してもらった限りでは再現しませんでした。環境依存？）  
- 「受け取り」の検索でも同様のアラート。
- 「Yoga」の検索ではアラート出ず。
- 「ちゃんと」の検索ではアラート出ず。
### URL

https://pleasanter.azurewebsites.net/items/1176/index
### ユーザID

Tenant49_User13
### スクリーンショット

![7ab47fc82f5ee893c9a7d8037b97b71f](https://cloud.githubusercontent.com/assets/2929454/18049652/96fa6368-6e24-11e6-9fcc-bb32a9a77eea.png)

**Comment by Implem** [comment]
kobakeさんのアカウントでリトライしてみたのですが、いまのところ再現できておりません。
再現方法、もうすこし詳しく教えていただけると助かります。

**Comment by kobake** [comment]
あれ、当時は100%再現してたのですが、自分のほうでも今試しましたが再現しなくなりましたね。。。そのあとの作業でデータ投入とかしているうちに再現条件がなくなってしまったのかもです。。

**Comment by kobake** [comment]
操作は、検索窓に「予約」って入れて、エンター押してただけです。

**Comment by kobake** [comment]
ちなみにこれは別件でIssueにするような話かもですが、今試したところでは、検索ワード入れてエンター押すと、検索結果は表示されるのですが、そのあとブラウザの戻るボタンを押しても元の画面に戻れませんでした

**Comment by kobake** [comment]
↑ブラウザの戻るが効かなくなる問題も、追加データつっこんでるうちに再現しなくなっちゃいました・・・（？）

**Comment by kobake** [comment]
もう1個別件
https://pleasanter.azurewebsites.net/items/1308/index
ここに「漢字」っていう単語を入れたチケットを作ったのですが「漢字」が検索にヒットしないです。検索DB構築の時間差？

**Comment by Implem** [comment]
定期的にバックグラウンドタスクが動いてますので、数分で検索できるようになると思います。

**Comment by kobake** [comment]
数時間経っても反映されてない（？）っぽい感じでした

**Comment by Implem** [comment]
すいません、バックグラウンドタスクを動かし忘れていました。
いま実行中ステータスになりましたので、数分で検索できるようになると思います。

**Comment by Implem** [comment]
検索ができるようになったので、クローズします。

**Comment by kobake** [comment]
👍
