### ISSUE TITLE
項目「分類」の数を増やしたい

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#20]
お世話になっております。

テーブルを設計するにあたって、項目「分類」の数を増やすことは可能でしょうか？
分類A～Zまで全てを使い切ってしまった時に、まだいくつか分類を使いたい。というような状態です。
対処方法がありましたら、教えていただけますと助かります。

申し訳ありませんが、#17 ～ #19 も回答を頂けると幸いです。
以上、どうぞよろしくお願い致します。

**Comment by Implem** [comment]
Issueありがとうございます。

現状、分類項目はA-Zの26種類です。ソースコードを改変することで項目を増やすことは可能です。手順は以下のとおりです。

1. ソースコードをダウンロードします。
2. Implem.Pleasanter/App_Data/Definitions/definition_Column.xlsmを開きます。
3. 期限付きテーブル等のClassA～Zの下にClassA1～ClassAXXの行を作成します。
4. Excel上でマクロを有効化し、Shift + Ctrl + J と操作します。
5. マクロが実行され、データベースのレイアウトを更新します。
6. 上記のあと、追加した項目に関連するソースコードを自動生成します。
7. 生成されたソースコードをコンパイルしデプロイします。

**Comment by yyuki23** [comment]
返信が遅くなり、申し訳ありません。
ご回答ありがとうございます。

現在試しておりますが、以下のエラーが出てコンパイルができない状態でストップしてしまいます。
ちなみに、構築環境はAzureです。
-----
ハンドルされていない例外: System.Data.SqlClient.SqlException: Reference to database and/or server name in 'Implem.Pleasanter.information_schema.columns' is not supported in this version of SQL Server.
-----

一点、確認させてください。
Excelを編集する際、NoやHistoryなどの番号は、分類Z(134)から連番で分類A1(135)、A2(136)…としてよいものでしょうか？
それとも、数値A(135)のまま、分類A1～AXXはそれまで使っていない数字(300以降など)を利用すべきでしょうか？

以上、どうぞよろしくお願いいたします。

**Comment by Implem** [comment]
回答がおそくなり申し訳ありません。
メッセージを確認したところ、Service.jsonのName属性をAzureで作成したdatabaseの名称に変更する必要がある事がわかりました。大変お手数ですが、こちらを変更の上、リトライをお願いいたします。

NoやHistoryなどの番号についてはテーブル単位に連番としてください。全体で一意にする必要はございません。

**Comment by yyuki23** [comment]
ご回答頂き、ありがとうございます。
また、昨日の勉強会でもお世話になりました。

リトライの結果、無事にエラーを解消することができました。
ありがとうございます。
また今後とも、よろしくお願いいたします。

**Comment by tsr-hataya** [comment]
お世話になっております

Azureのプリザンターをアップグレードしようとして「ハンドルされていない例外: System.Data.SqlClient.SqlException:～～」と出て進まなかったので、Google検索したらこのスレッドにたどり着きました。
Azure環境のバージョンアップでは「Service.jsonのName属性をAzureで作成したdatabaseの名称に変更する」は必須の作業のようですね。
ぜひともマニュアル「プリザンターのバージョンアップ Azure編」に反映していただきたいです。

**Comment by pierre3** [comment]
フィードバックありがとうございます。

マニュアルに「Service.jsonのName属性をAzureで作成したdatabaseの名称に変更する」旨を記載いたしました。

https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%97%E3%83%AA%E3%82%B6%E3%83%B3%E3%82%BF%E3%83%BC%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97-Azure%E7%B7%A8

今後ともよろしくお願いいたします。
