### ISSUE TITLE
BinaryStorage

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#202]
0.50.70.24211で試しています。
マニュアルのパラメータ設定のBinaryStorage.jsonを参考にして
写真や添付ファイルをデータベースに含めないやり方を試していますが、
うまくいきません。

他の方のIssuesを見ていると出来ている方もいるようで。

＜変更したこと＞
BinaryStorage.jsonの
　・Providerの項目　→　"Rds"を"Local"へ。
　・Pathの項目　→　null をc:\pripic\へ。(最後の¥マークや"で囲ってもみました)

＜確認方法＞
既存からサイトで写真を貼り付けても指定したフォルダ(c:\pripic\)に画像が保存されない。

＜知っている方＞
すでにデータベースに含まれているファイルを手軽に切り替える方法があるのでしょうか？
データベースサイズがすでに4.9Gなもので。

すみませんがよろしくお願いします。

**Comment by kazuca** [comment]
私もDBからファイルへの切り替えを検討してるのですが、既に取り込んであるものに関しては、自前でプログラムを書いてやる必要があると判断してます。
まとまった時間があれば、作るのですが・・・。

ファイルが保存されない件に関しては、アクセス権の問題だと思われます。
IIS_IUSRSなどIIS側からアクセス可能なアクセス権を付与してやれば大丈夫だと思います。

**Comment by akiyamashino** [comment]
> 私もDBからファイルへの切り替えを検討してるのですが、既に取り込んであるものに関しては、自前でプログラムを書いてやる必要があると判断してます。
> まとまった時間があれば、作るのですが・・・。
  ありがとうございます。現状、諦めます。ハードルが高いよ。今、職種も違うし、
　もう１５年くらい組んでないし、組み込み系でC言語しか経験ないし。(学校ではFortran77,pascal)JAVAやPrealやPHPやPowerShell、スプリクト・・・？無理です。今はバッチファイルやエクセルのマクロくらいを作るくらいです。

> ファイルが保存されない件に関しては、アクセス権の問題だと思われます。
> IIS_IUSRSなどIIS側からアクセス可能なアクセス権を付与してやれば大丈夫だと思います。
　今、退社してしまったので後日、試したいと思います。大変、ありがとうございます。

**Comment by akiyamashino** [comment]
> 私もDBからファイルへの切り替えを検討してるのですが、既に取り込んであるものに関しては、自前でプログラムを書いてやる必要があると判断してます。
ありがとうございます。現状、諦めます。ハードルが高いよ。今、職種も違うし、
もう１５年くらい組んでないし、組み込み系でC言語しか経験ないし。(学校ではFortran77,pascal)
JAVAやPrealやPHPやPowerShell、スプリクト・・・？無理です。
今はバッチファイルやエクセルのマクロくらいを作るくらいです

> まとまった時間があれば、作るのですが・・・。
> ファイルが保存されない件に関しては、アクセス権の問題だと思われます。
> IIS_IUSRSなどIIS側からアクセス可能なアクセス権を付与してやれば大丈夫だと思います。
今、退社してしまったので後日、試したいと思います。大変、ありがとうございます。

**Comment by akiyamashino** [comment]
> 私もDBからファイルへの切り替えを検討してるのですが、既に取り込んであるものに関しては、自前でプログラムを書いてやる必要があると判断してます。
> まとまった時間があれば、作るのですが・・・。

ありがとうございます。現状、諦めます。ハードルが高いよ。今、職種も違うし、
もう１５年くらい組んでないし、組み込み系でC言語しか経験ないし。(学校ではFortran77,pascal)
JAVAやPrealやPHPやPowerShell、スプリクト・・・？無理です。
今はバッチファイルやエクセルのマクロくらいを作るくらいです。

> ファイルが保存されない件に関しては、アクセス権の問題だと思われます。
> IIS_IUSRSなどIIS側からアクセス可能なアクセス権を付与してやれば大丈夫だと思います。

今、退社してしまったので後日、試したいと思います。大変、ありがとうございます。

**Comment by akiyamashino** [comment]
やっと試せました。結果から言いうと私のミスでした。

BinaryStorage.jsonのPathの項目
　null を”c:\pripic”へ変更しましたが、
   ”c:\\pripic”にしないとダメでした。
マニュアルの例でもD:\\と書かれていました。

お騒がしてすみませんでした。

**Comment by YoshikiSawada** [comment]
移行用プログラムを作りました。
・PHP（とSQL Server Drivers for PHP）を使えるようにしておく必要があります。
・プログラムの使用は自己責任でお願いします。

`<?php`
`// BinaryStorage.jsonで指定したフォルダ`
`$folder = "D:\Pleasanter";`

`// SQL Server`
`$serverName = "(local)";`
`$uid = "sa";`
`$pwd = "password"; // saアカウントのパスワード`

`/* ================　処理内容　================`
`SQL Serverに書き込まれたバイナリ（画像、添付ファイル）を`
`ファイルに書き出す`
`1. テーブルBinariesで列Binが空でないレコードを取得`
`2. レコード毎の処理`
`　2.1. レコードのBinaryId, Guid, BinaryType, Binを取得`
`　2.2. 指定のフォルダにBinをバイナリデータとして保存`
`　　（ファイル名はGuid（拡張子なし））`
`　2.3. レコードのBinを空にする`
`　　（BinaryIdをキーにする）`
`================================================*/`


`// SQL Server接続オープン`
`$connInfo = ["UID" => $uid, "PWD" => $pwd, "Database" => "Implem.Pleasanter"];`
`$conn = sqlsrv_connect($serverName, $connInfo);`

`// 1. テーブルBinariesで列Binが空でないレコードを取得`
`$sql = "SELECT * FROM Binaries WHERE Bin IS NOT NULL";`
`//1レコードでテストしてみる`
`//$sql = "SELECT *  FROM Binaries WHERE Guid='857ce1ff4bac4b11b7716192ffd67674'";`
`$stmt = sqlsrv_query( $conn, $sql, array(), array( "Scrollable" => SQLSRV_CURSOR_KEYSET ));`

`// レコード数取得`
`$rec_count = sqlsrv_num_rows($stmt);`
`echo "レコード数: " . $rec_count . "\n";`

`// 2. レコード毎の処理`
`$rec_num = 0;`
`while ($row = sqlsrv_fetch_array($stmt)) {`
`	$rec_num++;`
`	echo "処理開始: " . $rec_num . "/" . $rec_count . "\n";`

`	// 2.1. レコードのBinaryId, Guid, BinaryType, Binを取得`
`	$binaryId = $row["BinaryId"];`
`	$guid = $row["Guid"];`
`	$binaryType = $row["BinaryType"];`
`	$bin = $row["Bin"];`

`	// 2.2. 指定のフォルダにBinをバイナリデータとして保存`
`	// （ファイル名はGuid（拡張子なし））`
`	if($binaryType == "Images"){`
`		file_put_contents($folder . "\\Images\\" . $guid, $bin);`
`	}else{`
`		file_put_contents($folder . "\\Attachments\\" . $guid, $bin);`
`	}`

`	// 2.3. レコードのBinを空にする`
`	// （BinaryIdをキーにする）`
`	$sql = "UPDATE Binaries SET Bin = NULL WHERE BinaryID = ?";`
`	$stmt1 = sqlsrv_query( $conn, $sql, array($binaryId));  `
`	if( $stmt1 === false ){`
`		echo "Statement 1 could not be executed.\n";`
`	}`
`}`

`/* ==== SQL Server接続クローズ ==== */`
`sqlsrv_free_stmt($stmt);`
`sqlsrv_free_stmt($stmt1);`
`sqlsrv_close($conn);`

`?>`

**Comment by akiyamashino** [comment]
時間があるときにがんばってみます。
大変、ありがとうございます。

**Comment by akiyamashino** [comment]
> 移行用プログラムを作りました。
> ・PHP（とSQL Server Drivers for PHP）を使えるようにしておく必要があります。
> ・プログラムの使用は自己責任でお願いします。
> <?php
> // BinaryStorage.jsonで指定したフォルダ
> $folder = "D:\Pleasanter";
> // SQL Server
> $serverName = "(local)";
> $uid = "sa";
> $pwd = "password"; // saアカウントのパスワード
> /* ================　処理内容　================
> SQL Serverに書き込まれたバイナリ（画像、添付ファイル）を
> ファイルに書き出す
> 1. テーブルBinariesで列Binが空でないレコードを取得
> 2. レコード毎の処理
> 　2.1. レコードのBinaryId, Guid, BinaryType, Binを取得
> 　2.2. 指定のフォルダにBinをバイナリデータとして保存
> 　　（ファイル名はGuid（拡張子なし））
> 　2.3. レコードのBinを空にする
> 　　（BinaryIdをキーにする）
> ================================================*/
> // SQL Server接続オープン
> $connInfo = ["UID" => $uid, "PWD" => $pwd, "Database" => "Implem.Pleasanter"];
> $conn = sqlsrv_connect($serverName, $connInfo);
> // 1. テーブルBinariesで列Binが空でないレコードを取得
> $sql = "SELECT * FROM Binaries WHERE Bin IS NOT NULL";
> //1レコードでテストしてみる
> //$sql = "SELECT *  FROM Binaries WHERE Guid='857ce1ff4bac4b11b7716192ffd67674'";
> $stmt = sqlsrv_query( $conn, $sql, array(), array( "Scrollable" => SQLSRV_CURSOR_KEYSET ));
> // レコード数取得
> $rec_count = sqlsrv_num_rows($stmt);
> echo "レコード数: " . $rec_count . "\n";
> // 2. レコード毎の処理
> $rec_num = 0;
> while ($row = sqlsrv_fetch_array($stmt)) {
> 	$rec_num++;
> 	echo "処理開始: " . $rec_num . "/" . $rec_count . "\n";
> 	// 2.1. レコードのBinaryId, Guid, BinaryType, Binを取得
> 	$binaryId = $row["BinaryId"];
> 	$guid = $row["Guid"];
> 	$binaryType = $row["BinaryType"];
> 	$bin = $row["Bin"];
> 	// 2.2. 指定のフォルダにBinをバイナリデータとして保存
> 	// （ファイル名はGuid（拡張子なし））
> 	if($binaryType == "Images"){
> 		file_put_contents($folder . "\\Images\\" . $guid, $bin);
> 	}else{
> 		file_put_contents($folder . "\\Attachments\\" . $guid, $bin);
> 	}
> 	// 2.3. レコードのBinを空にする
> 	// （BinaryIdをキーにする）
> 	$sql = "UPDATE Binaries SET Bin = NULL WHERE BinaryID = ?";
> 	$stmt1 = sqlsrv_query( $conn, $sql, array($binaryId));  
> 	if( $stmt1 === false ){
> 		echo "Statement 1 could not be executed.\n";
> 	}
> }
> /* ==== SQL Server接続クローズ ==== */
> sqlsrv_free_stmt($stmt);
> sqlsrv_free_stmt($stmt1);
> sqlsrv_close($conn);
> ?>

時間があるときにがんばってみます。(もちろんテスト環境で行います)
大変、ありがとうございます。

**Comment by akiyamashino** [comment]
0.50.103.25994で上記のphpで添付ファイルでは成功しました。
php、大変ありがとうございました。（別のことをする時の足掛かりになりそうです）


２点、解決できないことがあります。

　１．画像が表示できない。
　　　→　#177の書き込みを見るとバージョンアップで問題なくなったとあるので別問題？
　２．サイトのアイコンが表示されない。
　　　→　#207の書き込みを見ると"プリザンターのバイナリを削除して、再度展開し直すと解消されました。"とありました。
　　　　　どのような手順ですればよいのか？

どなたかアドバイスを頂けるとありがたいです。（他力本願ですみません）

**Comment by kazuca** [comment]
> 0.50.103.25994で上記のphpで添付ファイルでは成功しました。
> php、大変ありがとうございました。(別のことをする時の足掛かりになりそうです)
> 
> 2点、解決できないことがあります。
> 
> 1.画像が表示できない。
> → #177の書き込みを見るとバージョンアップで問題なくなったとあるので別問題?
> 2.サイトのアイコンが表示されない。
> → #207の書き込みを見ると"プリザンターのバイナリを削除して、再度展開し直すと解消されました。"とありました。
> どのような手順ですればよいのか?
> 
> どなたかアドバイスを頂けるとありがたいです。(他力本願ですみません)

サイトのアイコンに関しては格納されている場所が異なるため、php側に処理を追加するか、再度登録し直すのいずれかになるかと。

**Comment by akiyamashino** [comment]
大変、お恥ずかしいです。またミスてしまいました。ミススペルです。
Imagesのスペルが。

サイトのアイコンは再登録していきます。

無事に移行できそうです。大変ありがとうございました。
