### ISSUE TITLE
管理(組織・グループ・ユーザ)もインポート・エクスポート機能があれば便利

### ISSUE THREAD

**Issue by yuntas** [Implem/Implem.Pleasanter#21]

**Comment by Implem** [comment]
Issueありがとうございます。

現在のプリザンターには組織、グループ、ユーザをCSVからインポートする機能がありません。今後は追加する方向で検討してまいります。

上記とは異なりますが、LDAP連携を行っている場合、下記のURLを開くことで、LDAPのユーザ及びその組織をプリザンターに同期する事が可能です。

http://servername/pleasanter/users/syncbyldap

これをタスクスケジューラ等で定期的に実行するように設定すると、人事異動の結果などを反映することができるようになります。PowerShellで実行する場合には、Invoke-RestMetohdが利用できます。
