### ISSUE TITLE
項目設定

### ISSUE THREAD

**Issue by mnori0102** [Implem/Implem.Pleasanter#214]
項目にプリザンターのグループを表示させ、その設定を利用し、フィルタをかけることはできますか？

**Comment by Ooooooomin365** [comment]
以下の方法とかはどうでしょうか？？

1. 「テーブルの管理」をクリック
2. エディタタブを選択し、選択肢一覧から「分類」を選択
3. 詳細設定から表示名を「グループ」等の任意の名前に変更し、選択肢一覧に[[Depts]]と入力
4. 「変更」ボタンを押し、画面下の「更新」ボタンをクリック
5. それぞれのレコードの「グループ」項目を設定

※一覧画面にも今回作成した「グループ」項目を表示させてフィルタをかけるとより動作が確認しやすくなるかもしれません。

**Comment by Ooooooomin365** [comment]
あ、すみません。これDeptsだと組織でした。ソースコード見た感じだと[[Depts]]と[[Users]]しか対応してなさそうなので、グループはちょっと厳しい気がします...。

**Comment by mnori0102** [comment]
回答ありがとうございます。
Deptであれば、対応可能なんですね。

やりたいことは、各グループごと（組織とは別のチームみたいなもの）があり、
そのグループごとに集計などを実施したいという内容になります。
※1ユーザー複数グループも存在

以下で問い合わせしている内容に紐づくのですが、
上記を利用して、グループに所属する各メンバーへ通知させたいのです。
[https://github.com/Implem/Implem.Pleasanter/issues/213]

**Comment by mnori0102** [comment]
> あ、すみません。これDeptsだと組織でした。ソースコード見た感じだと[[Depts]]と[[Users]]しか対応してなさそうなので、グループはちょっと厳しい気がします...。

回答ありがとうございます。
Deptであれば、対応可能なんですね。

やりたいことは、各グループごと（組織とは別のチームみたいなもの）に、
集計などを実施したいという内容になります。
※1ユーザー複数グループも存在

以下で問い合わせしている内容に紐づくのですが、
上記を利用して、グループに所属する各メンバーへ通知させたいのです。
[https://github.com//issues/213]
