### ISSUE TITLE
ADを使わないでLDAP認証

### ISSUE THREAD

**Issue by Hidetoku** [Implem/Implem.Pleasanter#215]
ADを使わないでLDAP認証を行いたいと思います
https://pleasanter.net/fs/publishes/420041/edit　を基にAuthentication.jsonを編集して実行しようとしましたがなかなかうまくいきません。
うまくいった方はいますか？おられましたら、Authentication.jsonのどの項目に何を設定すればいいかご教示いただけないでしょうか？

**Comment by shoheichikura** [comment]
#224 で対応版をPullRequestして取り込んで頂きました。
https://pleasanter.net/fs/publishes/422361/edit
お試しください。
