### ISSUE TITLE
リンク先情報非表示

### ISSUE THREAD

**Issue by mnori0102** [Implem/Implem.Pleasanter#219]
テーブルでリンク関係を構築している場合、
親テーブルのレコードで子テーブルの情報が出力されます。
こちらのリンク先の情報を非表示としたいのですが、可能でしょうか。

**Comment by YoshikiSawada** [comment]
1. レイアウトを変更したいページのソースを表示させ、非表示にしたい要素を調べる
　`<div id="Links" name="Links" class="links">`
　`　<fieldset class="fieldset cf enclosed"><legend class="legend">リンク</legend>`
　`　...`
　`</div>`
　→ 今回はidがLinksの要素

2. 「テーブルの管理」でスクリプトを新規作成する
　タイトル：　リンク先を非表示にする
　スクリプト：$("#Links").hide();
　出力先：　　編集
　※スタイルでも同じことができる
　　#Links { display:none; }
