### ISSUE TITLE
自分のローカル環境に構築した時もデモのように新規作成のサンプルがほしい

### ISSUE THREAD

**Issue by yuntas** [Implem/Implem.Pleasanter#22]
一から作成することは煩わしい部分と慣れていない部分があるので
サイトを起ち上げる時にサンプルも含めた状態にしてほしい

**Comment by Implem** [comment]
Issueありがとうございます。

以下の手順で、ローカル環境にデモ用のデータを配置できますので、トライしてみてください。
1. c:\inetpub\wwwroot\pleasanter\App_Data\Parameters\Service.jsonを開きます。
1. "Demo": true, に設定し保存します。
1. IISを再起動します。
1. プリザンターのログイン画面を表示すると「デモ環境を見る」という欄が表示されるので、適当なメールアドレス「test@example.com」等を入力し登録ボタンを押します。メールアドレスは存在しないものでかまいません。
1. SSMSでDemosテーブルを開き、Passphraseカラムに記録されている文字列をコピーします。
1. 下記のURLを開きます。passphraseは上記の手順で取得したものに置き換えます。
http://localhost/pleasanter/demos/login?passphrase=_374750567BC1416783710B8AFEE8516D_
1. しばらくするとデモデータが配置された画面が表示されます。

**Comment by yuntas** [comment]
確認できました。
ありがとうございます。
新規作成からひな形のような形で
インポートできれば導入しやすいと感じました。
