### ISSUE TITLE
集計項目の表示が IDで表示されてしまう

### ISSUE THREAD

**Issue by nishiankr** [Implem/Implem.Pleasanter#222]
例えば、デモサイトの「商談管理の例」にて、
「顧客マスタ」テーブルに20~30ケ以上の顧客名を登録し、
「商談」 テーブルで レコードを登録します。
「商談」 テーブルに  集計で "顧客(件数)" を追加します。
「商談」テーブルのエディタの設定にて  "[商談]顧客"の詳細設定で ”検索機能を使う”にチェックしておきます。
すると、 集計で "顧客(件数)"の表示が、顧客名でなく、"？ID" で表示されてしまいます。
![image](https://user-images.githubusercontent.com/56910696/67369070-55444780-f5b3-11e9-9c7e-10162843a1e0.png)

Pleasanter バージョン0.50.86.16849 からそのような症状になることに気づきました。
現状の 0.50.115.34766でも同様です。
こちらで把握している限りでは バージョン0.49.193.23913 までは問題なかったです。

描画速度を向上させるための設計なのかもしれませんが、改善はできませんでしょうか。

**Comment by akiyamashino** [comment]
私の環境でもおきます。(#219)

**Comment by akiyamashino** [comment]
0.50.120.33065でも試してみましたが同じ動作でした。
