### ISSUE TITLE
API機能：レコード操作：複数取得について

### ISSUE THREAD

**Issue by kashozui** [Implem/Implem.Pleasanter#227]
こんにちは、Pleasanterの初心者ですが。
API機能のレコード操作について、RequestBodyのViewに、渡せる引数はView.csの全フィールドですか?
下記添付ファイルのRequestを送ると、システムエラーになってしまう。
何か設定が間違いますか？
Request
[Request.txt](https://github.com/Implem/Implem.Pleasanter/files/3845297/Request.txt)
Response
[Response.txt](https://github.com/Implem/Implem.Pleasanter/files/3845298/Response.txt)
SQL ログ（存在しないテーブルを検索しようとする）
[SQL Log.txt](https://github.com/Implem/Implem.Pleasanter/files/3845299/SQL.Log.txt)

ご教授して頂ければ幸いです。

**Comment by YoshikiSawada** [comment]
API機能の詳細なマニュアルがないので、推測を交えて回答してみます。

Requestの"Search":" Title"行を削除するとエラーは出なくなりました。
が、全件取得されているようでした。
Request.txtから推測するに、レコード全体に対して（複数の文字列カラムに対して）検索をかけたいのだと思いますが、そのような機能はなさそうです。
参考）下記URLの「Items APIで指定できるもの」表
https://imageinformationsystem.hatenablog.com/entry/2018/12/14/170000

代替案として思いつくのは下記２案です。
案１．API Requestでできるだけ条件絞り込みを行ってレコード数を減らし、
　　　APIクライアントのプログラム内でレコード全体に対するフィルタをかける
案２．拡張SQLで検索対象カラムの内容を結合したカラムを追加し、
　　　そのカラムに対してAPI Requestで検索をかける

**Comment by kashozui** [comment]
ご回答ありがとうございます！試してみます。:)

**Comment by Implem** [comment]
APIでViewのSearchを指定するとSQLのエラーが発生する不具合がございました。
最新版にて修正しておりますので、アップデートで解消すると思います。
