### ISSUE TITLE
CSSでのContent:を使った文章表示について

### ISSUE THREAD

**Issue by rbd27** [Implem/Implem.Pleasanter#228]
プリザンター・プログラミングともに初心者です。

テーブル上で一覧表示・カレンダー表示のそれぞれに別の説明文を表示するために、
「テーブル管理」→「スタイル」から
**#Guide:after {content:"カレンダー表示したときの説明文";}**
のようなコードを作成し、出力先を「カレンダー」のみチェックしています。
ですが、一覧表示にもこの説明文が表示されてしまったり、逆に
カレンダー表示にしたときに表示されなかったりして動作が不安定です。
いずれもページ更新をすると想定していた挙動になるのですが・・

CSSもあまり触ったことがなく、プリザンターについても純然たるエンドユーザーなので
ひょっとしたらまずいことをしているのかもしれませんが、
対処法などございましたらご教示いただけると助かります。

**Comment by YoshikiSawada** [comment]
コードは正しいように見えます。
手元の環境で意図通りに動作しました。

なので、原因はコード以外にあるはずです。
あり得そうな原因を推測してみます。

1. Webブラウザのキャッシュが影響している
　昔、IEのキャッシュ設定を「自動的に確認する」から
　「Webサイトを表示するたびに確認する」に変更することで
　正しく表示されるようになった経験があります。
　（今はChromeを使っていて、問題なく動作していますが。。。）

2. 設定を保存していない
　たまにやらかすミスですが、スタイルやスクリプトを追加・変更した後、
　テーブル管理画面の「更新」ボタンをクリックし忘れることがあります。
　「スタイルを変更 > テーブル管理画面で更新 > 該当ページを開く（または
　再読み込みする）」と正しく手順を踏めば良いのですが、更新を忘れて
　訳が分からなくなることがあります。

参考になりましたら幸いです。

**Comment by rbd27** [comment]
コメントありがとうございます。
Chrome・Edge（初めて使いました・・）・IEで試してみましたがやはり表示されたりされなかったりです。設定の保存もできているので、結局原因はよくわからないです・・。
CSSの読み込みタイミングとかも恐らく関連していそうですのでまた検討してみます。
ご助言ありがとうございました。

**Comment by YoshikiSawada** [comment]
「テーブル管理」⇒「スクリプト」で実装すると挙動が変わったりしないですかね。
下記が同じことを実現するスクリプトになります。

var description = 'カレンダーを表示した時の説明文';
var element = document.getElementById("Guide");
element.insertAdjacentHTML('afterend',description);
