### ISSUE TITLE
1つの圧縮ファイルで全体のバックアップを可能に

### ISSUE THREAD

**Issue by yuntas** [Implem/Implem.Pleasanter#23]
テーブル一つ一つをエクスポートするのは不便。

フォルダやテーブル等の情報をまとめて
一つのファイルでエクスポート/インポートできれば
バックアップや復元が便利になると思いました。

**Comment by Implem** [comment]
Issueありがとうございます。

たしかにこれができると便利ですね！
実装の方式を検討してみます。

**Comment by yuntas** [comment]
[Snipe-IT](https://snipeitapp.com/) という OSS の資産管理ツールで実装されており、とても便利でした。

今後の更なる利便性向上に繋がれば幸いです。
