### ISSUE TITLE
Windows統合認証環境でAPIが401となり利用できません。

### ISSUE THREAD

**Issue by shinki1973** [Implem/Implem.Pleasanter#233]
ユーザマニュアルのWindows統合認証によるサインオンを設定したところ。
（https://pleasanter.net/fs/publishes/420162/edit）

今まで利用できていたAPIのリクエストが、すべて「401」を返し利用できなくなりました。
確認のため、統合認証環境から設定を元に戻したところ、再度利用可能となりました。

リクエストはローカルユーザでログインしているWindowsPCで実行しているバッチファイルから
curlコマンドで実行しています。
curlのオプションでユーザID/PWを設定すれば回避できるのは承知しているのですが。
バッチファイル内にID/PWを記載したくありません。

追加設定で対応可能であれば、ユーザマニュアルに設定内容の追記をお願いします。

**Comment by YoshikiSawada** [comment]
RPAで同様のことを行っています。
1. 一般ユーザ ・・・ ADアカウントユーザで、Windows統合認証を使用
2. RPA ・・・ Windowsローカルアカウントユーザで、Pleasanterのログイン画面を使用
　（一般ユーザとRPAは同じPleasanterデータを扱っています）

ご質問のAPIは2の環境を使えば良いと思います。
このような環境を実現するには、1と2のURLを分けます。

1. http://localhost/pleasanter ・・・ Windows統合認証
2. http://localhost/pleasanter-api ・・・ フォーム認証

以下、URLを分ける手順です。
（http://localhost/pleasanter はWindows統合認証になっているものとします）

1. C:\inetpub\wwwroot\pleasanter を C:\inetpub\wwwroot\pleasanter-api にコピー

2. IISマネージャを起動 > ホスト名 > サイト > Default Web Site > pleasanter-apiを右クリック > アプリケーションへの変換

3. http://localhost/pleasanter-api にアクセスできることを確認
　※アクセス権エラーが出た場合は、エクスプローラから該当フォルダに対して必要なアクセス権を設定します

4. pleasanter-api をWindows統合認証からフォーム認証に戻す
　⇒ ログイン画面が表示されればOK

以上です。

ただし、この構成だと拡張クエリ等を二重メンテナンスしなければならないので、
C:\inetpub\wwwroot\pleasanter-api\App_Data\Parameters\ExtendedSqls
を
C:\inetpub\wwwroot\pleasanter\App_Data\Parameters\ExtendedSqls
へのシンボリックリンクに置き換えています。
※シンボリックリンク作成コマンド：mklink
※設定を分ける箇所以外はリンクにしてしまった方がメンテナンス性が良いと思います。

参考になりましたら幸いです。
（残念ながら、中の人ではないのでマニュアルの追記はできません。）

**Comment by shinki1973** [comment]
対応策を教えていただき、ありがとうございます。
Pleasanterを分けるのは盲点でした、環境を作って試してみます。
