### ISSUE TITLE
違うサイト間の項目データ連携

### ISSUE THREAD

**Issue by kashozui** [Implem/Implem.Pleasanter#235]
こんにちは、
Issue表題の通り,
Pleasanterで違うサイト間で、同じ項目のデータ同期方法を教えていただけますでしょうか。
例えば：Aサイト A class とB サイトの A class、同じ値を持ちたい場合、どう設定すればいいでしょうか？（レコード結合条件有り）
ご教授して頂ければ幸いです。

**Comment by YoshikiSawada** [comment]
こんにちは

「レコード結合」とは「リンク」のことですよね？
　Pleasanterユーザマニュアル「テーブル機能：[リンク](https://pleasanter.net/fs/publishes/422232/edit)」

であれば、下記記事が近いことをやっています。
　Pleasanter FAQ「[サンプルコード：親テーブルの項目の値を子テーブルの項目に転記したい](https://pleasanter.net/fs/publishes/326120/edit)」

上記記事のスクリプトを変更することで実現できると思います。
子テーブルのレコードを更新した時に、子から親に同期するものとします。（逆も同様）
・親テーブル、子テーブルにスクリプトをセットする
・取得するイベントを変更する
　$(document).on('change', '#Results_ClassA', function () {}) の代わりに
　$p.events.before_send を使う
　　Plesanterユーザマニュアル「[スクリプト機能](https://pleasanter.net/fs/publishes/418092/index?View=%7b%22Id%22%3a1%2c%22Name%22%3a%22%u6a19%u6e96%22%2c%22ColumnFilterHash%22%3a%7b%22ClassA%22%3a%22%5b%272200%27%5d%22%7d%2c%22ColumnSorterHash%22%3a%7b%22ClassA%22%3a0%2c%22Title%22%3a0%7d%7d)」
・子から親に同期する時はapiUpdateを使う
　　Pleasanterユーザマニュアル「[API機能](https://pleasanter.net/fs/publishes/418092/index?View=%7b%22Id%22%3a1%2c%22Name%22%3a%22%u6a19%u6e96%22%2c%22ColumnFilterHash%22%3a%7b%22ClassA%22%3a%22%5b%272200%27%5d%22%7d%2c%22ColumnSorterHash%22%3a%7b%22ClassA%22%3a0%2c%22Title%22%3a0%7d%7d)」
・親から子に同期する時はapiGetで子のレコードIDを取得して、apiUpdateで書き込む

拡張SQLでも実現できると思います。
　Pleasanterユーザマニュアル「[拡張SQL](https://pleasanter.net/fs/publishes/422350/edit)」
　
参考になりましたら幸いです。

**Comment by kashozui** [comment]
ご回答ありがとうございます:)
