### ISSUE TITLE
日付項目のエディタ書式追加要望

### ISSUE THREAD

**Issue by yuntas** [Implem/Implem.Pleasanter#24]
- 時刻のみ選択できる項目

**Comment by Implem** [comment]
Issueありがとうございます。

日付の形式ですが、内部的にはdatetime型で保存されているので、見た目だけの時刻表示（内部的には日付ももっている）はできるかもしれませんが、どのように実装すべきか悩みどころです。取り急ぎの解決策としては、分類項目の選択肢に00:00～23:59を列挙することで、選択可能にする案もあります。この場合、現行の機能で実現できます。

**Comment by yuntas** [comment]
回答頂きありがとうございます。

分類項目を利用してみます。
