### ISSUE TITLE
クロス集計のエクスポートについて

### ISSUE THREAD

**Issue by mnori0102** [Implem/Implem.Pleasanter#240]
クロス集計で集計したい月の情報を画面出力させた後に、
CSVエクスポートを実施すると、当月分の情報がエクスポートされる。

例：2020年1月に2019年12月分の集計をエクスポートすると
　　2020年1月のデータがエクスポートされる。

**Comment by Implem** [comment]
期間をただしく保持しておけない不具合がありましたので、修正版を公開しました！

**Comment by mnori0102** [comment]
ご対応ありがとうございました！
最新バージョンで改善の認識でよろしいでしょうか。

**Comment by Implem** [comment]
はい、最新バージョンでご確認ください。
