### ISSUE TITLE
分類項目で[[Users]]を設定、更新時のアクセス制御設定でユーザIdが表示される

### ISSUE THREAD

**Issue by koikoi0407** [Implem/Implem.Pleasanter#246]
確認バージョン：0.50.139.32239
発生条件：
１、分類項目の選択肢一覧に[[Users]]を設定
２、該当項目を「項目のアクセス制御」-「更新時のアクセス制御」で特定ユーザを指定
　「作成時のアクセス制御」「読取り時のアクセス制御」は設定しない
３、２で設定したユーザ以外でレコードの詳細画面で分類項目が「?12345」とユーザIDが表示される。
　該当ユーザ、特権ユーザは正しくユーザ名が表示される
４、一覧では該当項目は正しくユーザ名が表示される。

以上、確認をお願いします。

**Comment by shimizzz** [comment]
同様の現象が「作成時のアクセス制御」でも発生しました

- 概要
  - [[Users]]を指定した項目に対して「作成時のアクセス制御」をかけた際、新規作成画面で「この操作を行うための権限がありません。」というシステムエラーが発生し、作成ができない。

- 確認バージョン：0.50.141.32279
- 再現手順
  1. 選択肢[[Users]]の項目作成
  1. 組織 "A" と ”B” を用意、ともに「サイトの権限」にて作成権限を付与
  1. 「作成時のアクセス制御」にて、組織"B"を指定
  1. 組織"A"のユーザで『新規作成』を実施
- 結果
  - 新規作成画面からの作成ができなくなる
    - [[Users]]指定した選択項目はグレーアウトで、書き込みができない状態
    - しかし項目内の値に「? 0」と入っている
    - そのまま保存しようとすると、「この操作を行うための権限がありません。」となり、作成が 不可となる
  - 一覧画面での「編集モード」を使用しての作成/保存は可能だった
    - その際該当項目は、作成時には「(未設定)」と表示され、編集後は空白となっている
