### ISSUE TITLE
スプリクトの実行について

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#247]
いつも便利、使用させて頂いています。
同じ場面（一覧や新規作成など）をチェックBOXで指定して、それぞれに別✕のスプリクトを登録すると実行されません。希望としましては両方、実行されてほしいです。

例えば、
alertで警告画面を出しながら、リンクをクリックした時に新しいタブを開いたり、印刷時のボタンを消すスプリクトを同時に走らせたりたいです。

書き方に決まりがあるのでしょうか？

**Comment by YoshikiSawada** [comment]
スクリプトを分けて登録しても実行されます。
実行されない理由として考えられるのは下記のようなものです。
・alertを閉じなかったため、次のスクリプトが実行されない
・スクリプトでエラーが発生し、次のスクリプトが実行されない

実行される順番についての記事があります。
[新機能の拡張スタイル・スクリプトなどを試してみる](https://pleasanter.hatenablog.jp/entry/%E6%96%B0%E6%A9%9F%E8%83%BD%E3%81%AE%E6%8B%A1%E5%BC%B5%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%83%BB%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E3%81%AA%E3%81%A9%E3%82%92%E8%A9%A6%E3%81%97%E3%81%A6%E3%81%BF#%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E3%82%92%E8%A9%A6%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B)

**Comment by akiyamashino** [comment]
YoshikiSawada様ありがとうございます。

最近、以下のFAQが出たので時間が取れた時に合わせて検証してみたいと思います。
https://pleasanter.net/fs/publishes/1071409
