### ISSUE TITLE
ファイルを添付したいです

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#25]
お世話になっております。

カラムのExcelを見る限り、ファイルの添付ができるように準備されてる気がするのですが、
どのようにすればプリザンターUI上でファイル添付機能が利用できるようになるでしょうか？

方法がありましたら、教えていただけますと助かります。
以上、どうぞよろしくお願い致します。

**Comment by Implem** [comment]
ファイルの添付機能は項目として準備されておりますが、まだ実装できていない状況です。

**Comment by yyuki23** [comment]
ご回答ありがとうございます。
情報共有システムで利用される場合が多いかと思いますので、ファイル添付は需要も高いような気がします。
実装されるのを楽しみにしております。
こちらでも緊急度が上がりましたら、また別途連絡させていただきます。
