### ISSUE TITLE
入力桁数制限ができるようにしてほしい

### ISSUE THREAD

**Issue by NakaishiYoshihiro** [Implem/Implem.Pleasanter#257]
数字項目を入力するときに、何文字以上入力できないように制御したい。
例）口座番号を入力する時には7文字までしか入力させないようにする。

**Comment by takaoyama** [comment]
エディタ＞数値項目の詳細設定にて、コントロール種別をスピナーにすると最小値・最大値が設定できます。

**Comment by NakaishiYoshihiro** [comment]
ありがとうございます。
スピナーにすると、項目幅が狭くなるので、あとはスタイルで設定すればよいのですね。

今回は分類で作ってしまっていたので、以下のスクリプトを入れてみました。

//レコード編集画面の更新ボタン押下後、サーバー送信前のイベント
$p.events.before_send_Update = function (args) {
    var str = $('#Results_ClassG').val();
    if (str.length > 7) {
        $p.clearMessage();
        $p.setMessage('#Message', JSON.stringify({
            Css: 'alert-error',
            Text: '郵便番号は７桁で入力してください。'
        }));
        return false; //falseのときは処理が止まり、更新されない
    } else {
        return true; //trueのときは更新される
    }

}
