### ISSUE TITLE
数字項目フィルタで○番から○番までと範囲指定したい　また、０以外を抽出したい。

### ISSUE THREAD

**Issue by NakaishiYoshihiro** [Implem/Implem.Pleasanter#258]
数字項目のフィルタで、○番から○番までと指定したい。

また、現在は0～1000のようにフィルタする仕様ですが、0番はいりません。
何かしら数字が入っているものを抽出したくてもできない状態です。

**Comment by takaoyama** [comment]
テーブルの管理＞フィルタ＞数値項目の詳細設定にて、モード選択で「規定」から「範囲指定」に変更すればできます。

**Comment by NakaishiYoshihiro** [comment]
ありがとうございます！解決できました！

項目名部分のフィルタにおいても、将来的に範囲指定が実装できるとうれしいです。
