### ISSUE TITLE
Descriptionをつけたい

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#26]
お世話になっております。

新規作成画面や編集画面で、マウスオーバーをすることでDescriptionを表示する。
というようなことは可能でしょうか？
その項目の説明を載せたいと考えております。

ご確認いただけますと幸いです。
以上、どうぞよろしくお願いいたします。

**Comment by Implem** [comment]
現時点でツールチップを表示する機能はございません。今後、実装について検討していきたいとおもいます。

**Comment by yyuki23** [comment]
ひとまずスクリプトで表示させることができることは確認できました。
もしメイン機能として実装いただければ嬉しいです。
