### ISSUE TITLE
画像のリサイズについて

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#260]
画像ライブラリやリンク先項目、一覧などで表示される画像についてです。
現状、アップロードされている画像に表示のみサイズ指定をかけた状態(実体のサイズはそのまま)で表示されていますが、これをリサイズしたものにすることは可能でしょうか？

例）幅200pxにリサイズ、クリックで実サイズで表示される

多数の画像が貼り付けられたサイトを表示する際のデータ転送量の削減と表示レスポンスの改善を期待しています。

アップロード時の画像縮小も検討に入れたのですが、画像の一部を拡大して詳細を確認する必要があるため、実用的ではありませんでした。

**Comment by akiyamashino** [comment]
私も希望します。
現在、画像を多用しています。同じ問題に行きあたり小さくしてアップしています。
拡大表示して詳細知りたい時に解像度が足りなくて不便でした。

可能であれば、場面ごとにサムネイルのサイズが指定できるとありがたいです。

**Comment by kazuca** [comment]
50.172で実装されていることが確認出来ましたので、クローズします。
