### ISSUE TITLE
自分自身をリンクに設定していると「エディタ」の選択肢一覧「リンク」でエラーになる

### ISSUE THREAD

**Issue by tsrs** [Implem/Implem.Pleasanter#264]
**プリザンターバージョン：0.50.161.35994**

分類に自分自身をリンクさせたテーブルの場合、テーブル管理→タブ「エディタ」を開いて選択肢一覧の「リンク」を選択するとアプリケーションエラーが発生します。こちらは仕様となりますでしょうか？

![image](https://user-images.githubusercontent.com/1467673/84270429-9d75a180-ab65-11ea-8151-bceead9bd970.png)

![image](https://user-images.githubusercontent.com/1467673/84270498-ba11d980-ab65-11ea-81cb-afbb7bee4fc6.png)

**ErrMessage**
同一のキーを含む項目が既に追加されています。

**ErrStackTrace**
   場所 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   場所 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   場所 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   場所 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   場所 Implem.Pleasanter.Libraries.Settings.SiteSettings.EditorLinksSelectableOptions(Context context, Boolean enabled) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Settings\SiteSettings.cs:行 1954
   場所 Implem.Pleasanter.Models.SiteUtilities.EditorSourceColumnsResponses(ResponseCollection res, Context context, SiteSettings ss) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Sites\SiteUtilities.cs:行 5350
   場所 Implem.Pleasanter.Models.SiteModel.SetEditorSourceColumnsSelectable(Context context, ResponseCollection res) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Sites\SiteModel.cs:行 2388
   場所 Implem.Pleasanter.Models.SiteModel.SetSiteSettings(Context context, ResponseCollection res) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Sites\SiteModel.cs:行 1553
   場所 Implem.Pleasanter.Models.SiteModel.SetSiteSettings(Context context) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Sites\SiteModel.cs:行 1463
   場所 Implem.Pleasanter.Controllers.ItemsController.SetSiteSettings(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 780
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by uchi-ta** [comment]
ご連絡ありがとうございます。こちらのエラーに対策したものをPleasanter.0.50.164.23381として公開いたしました。
