### ISSUE TITLE
バックグラウンドタスクでのシスログ削除

### ISSUE THREAD

**Issue by takaoyama** [Implem/Implem.Pleasanter#267]
お世話になっております

表題の件、リマインダーのタスクスケジューラ設定を参考にバックグラウンドタスクのタスクを作ってみたのですが、古いシスログが一向に削除されません。
どなたか解決法など教えていただければ幸甚です。

参考情報です。
１．以下のファイルは初期値のままで変更していません。
　BackgroundTask.ps1
　BackgroundTask.json
　SysLog.json
２．同じフォルダに格納しているリマインダー（Reminder.ps1）は正常に動いています。

よろしくお願いいたします。

**Comment by kazuca** [comment]
BackgroundTask.ps1のURLは実際の環境と一致していますか？また、BackgroundTask.jsonのEnableはtrueに変更していますか？
既定では、無効化(Enable:false)されているため、そのままでは動きません。

**Comment by takaoyama** [comment]
返信いただき、ありがとうございます。

指摘いただいた箇所を確認しましたが、設定は問題なしでした。

BackgroundTask.ps1内の?Nolog=1を外して、バックグランドタスクでシスログを作成するようにして状況を確認しました。
しかし、バックグラウンドタスクは動いていましたが、シスログは削除されないという状態は変わらずでした。。。

もうしばらく設定回りと格闘してみます。

**Comment by takaoyama** [comment]
暫定対応として、delete文を発行して削除するようにしました。
