### ISSUE TITLE
説明の枠の大きさを調整したい

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#27]
お世話になっております。

説明の枠の大きさ(高さ)を調整することは可能でしょうか？
必要に応じて大きくor小さくできたらいいなぁと思っています。

以上、どうぞよろしくお願いいたします。

**Comment by Implem** [comment]
カスタムCSSで調整が可能なので、ご面倒ではございますがカスタムCSSでheight等の属性を制御していただくようお願いいたします。

**Comment by yyuki23** [comment]
カスタムCSSで調整可能とのこと、承知いたしました。
ご回答ありがとうございます。
