### ISSUE TITLE
サムネイル機能

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#273]
いつも便利に使用させて頂いています。
Provider=Localでサムネイル機能を使用しています。

写真によっては縦のものが横になってしまったりします。
何か法則性はあるのでしょうか？

また、設定の値を320に設定しても360ピクセルの表示となっています。
設定の値は何を示しているのでしょうか？縦、横、ピクセル？

以上、すませんがよろしくお願いいたします。

**Comment by kazuca** [comment]
EXIFで回転指定をしている場合は、無視されているみたいです。
スマホで縦位置撮影すると、画像自体の向きは横で保存され、縦方向の指定はEXIFで行っていることがほとんどなので、そのような場合は、横向きとなるようです。

**Comment by akiyamashino** [comment]
kazuca様、丁寧に教えて頂きありがとうございます。
今まではリサイズしてからあげていたので問題がなかったのかなと思います。
理由が分かったので使用者には横で写真を撮るようにお願いして対応にしようと思います。
（コンデジ、タブレット、両方で撮っています）

ありがとうございました。
