### ISSUE TITLE
チェックボックスと分類や説明を連動させたい

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#28]
お世話になっております。

チェックボックスにチェックを入れた時のみ、
分類や説明を記入できるようにする。
といったことは可能でしょうか？
もしできるようになれば、いろいろ可能性が広がるなぁと考えております。

以上、どうぞよろしくお願いいたします。

**Comment by Implem** [comment]
GUIでこれらを設定する機能はありませんが、JavaScriptを挿入していただくことで同様の事が可能になるとおもいます。ご面倒ではございますが、JavaScriptで各項目の入力制御にトライしていただければ幸いです。

**Comment by yyuki23** [comment]
こちらもスクリプトで実施可能なことが確認できました。
こちらももしGUIで実装されれば嬉しいです。
