### ISSUE TITLE
ビューの設定のフィルタの挙動について

### ISSUE THREAD

**Issue by sato0928** [Implem/Implem.Pleasanter#280]
ビューの詳細設定でフィルタを追加した際、何らかの項目にチェックを入れないと設定画面を抜けて更新を押してもフィルタが有効化されません。
チェックがオフの状態をデフォルトにするという事ができないのでこれは不具合のような気がするのですがいかがでしょうか。
(仮に全てオフの状態で追加できるようになった場合今度は削除する方法がなくなるのでこれで仕様通りなのかな…？)
バージョン0.50.176.27015

**Comment by kazuca** [comment]
ちょっと面倒なんですが、チェックを入れた状態でフィルタを作って、あとからDBを直接編集すればチェックオフのフィルタが作れます。
SiteテーブルのSiteSettingの中に各種設定がJSONで格納されています。その中にViewsというプロパティがあるのですが、その中にある該当のViewを探して、次の様に書き換えるとOKです。ビューのIDで該当ビューを探して下さい。

```
"ColumnFilterHash": {"CheckB": "true"}
```
たとえば、CheckBがチェックオンであるなら、
```
"ColumnFilterHash": {"CheckB": "false"}
```
こういう感じすれば、チェックオフになります。

出来れば、ソータみたいに、項目を×で消し込めるようになるとこういう面倒な操作は不要になるとは思うのですが、現状の方法だとオフのフィルタを作るにはこういう方法しかなさそうです。

**Comment by sato0928** [comment]
対処方法ありがとうございます。
ひとまずその方法でしのいでみます。

**Comment by sato0928** [comment]
ご対応頂いたようで使いやすくなっていました。
ありがとうございました。
