### ISSUE TITLE
インポート時の特定ワードの挙動について

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#284]
インポートを行う際に`^\[(.)+\]$`という正規表現にマッチする文字列を含んだセルを含むCSVファイルを取り込むと、該当部分がリンクと解釈されるようで正常に取込が行われません。
この部分、マニュアルに記載が無いようですが、正常な挙動でしょうか？

また、リンク項目に数字のみを指定したものを取り込むと自動的にリンクが貼られるという機能があり、便利に使わせて貰っているのですが、この挙動もマニュアルに記載が無いようです。

このあたりの仕様をまとめて、マニュアルに記載して貰うことは可能でしょうか？

**Comment by Seiya-Endo** [comment]
正規表現につきましては調査いたします。

インポート時にレコードIDを使ってもリンクできる件、マニュアルに追記しました！
ご意見ありがとうございます！

**Comment by kazuca** [comment]
リンクを設定した項目に```[未設定]``'などを放り込むと再現します。調査よろしくお願いします。
