### ISSUE TITLE
アクセス制御について

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#29]
お世話になっております。

現状のアクセス制御は、ユーザやグループのサイトへのアクセス制御を設定した上で、
各項目に対してアクセス権の種類を設定する形になっているかと思います。

以下の様なことができないかと考えていますが、可能でしょうか？
各項目に対して、グループやユーザ単位でアクセス制御を実施する。
```
例
承認者の欄は承認者権限を持った人しか更新できないようにする
```

以上、ご検討いただけますと幸いです。
どうぞよろしくお願いいたします。

**Comment by Implem** [comment]
項目単位のアクセス制御ですが、他のアクセス件との組み合わせのみで実施可能です。
たとえば「サイトの管理」権限をもっている人が「状況」を変更できるようになる等です。
グループ単位での実装については今後の検討課題にしたいと思います。
今後とも宜しくお願い致します。

**Comment by yyuki23** [comment]
ご回答頂き、ありがとうございます。
やはりアクセス権の組み合わせでのみ可能ということ、承知いたしました。
現在も既にそのように実施しているため、グループ単位での実装を楽しみにしております。
どうぞよろしくお願いいたします。
