### ISSUE TITLE
APIの利用方法について

### ISSUE THREAD

**Issue by jinjin9527** [Implem/Implem.Pleasanter#290]
① ユーザーを取得するAPIについて、使い方が間違っているでしょうか？
・参照：https://pleasanter.net/fs/publishes/605015/edit
・request：
> $.ajax({
>     type: "POST",
>     url: 'http://192.168.1.17/pleasanter/api/users/get', 
>     data: {
>     "ApiVersion":1.1,
>     "ApiKey": "XXX"
> },
>     success: function(data1){
>         console.log( data1);
>     },
>     async:false,
>     dataType: 'json'
>   });
・response：
Value: "{"Id":"NotFound","Text":"指定された情報は見つかりませんでした。","Css":"alert-error"}"

② APIを呼び出した後に、pleasanterの処理ログはどこに出力していたでしょうか？
DB「Syslogs」は単なる操作履歴を記録したような感じです。

**Comment by kazuca** [comment]
0.50.181でテストしてみましたが正常に取得されますね。

![20200904](https://user-images.githubusercontent.com/37392077/92189626-1d2bb780-ee9a-11ea-8083-ddce45ce6b0d.png)

Syslogですが、ClassフィールドとMethodフィールドを見て貰うと見つかると思います。今回のパターンだとClassがUsersでMethodがgetですね。

![20200904_Log](https://user-images.githubusercontent.com/37392077/92189968-e4401280-ee9a-11ea-8dd7-83b5d3afc8a2.png)

その他の情報は適時フィールド名を見れば推測できるかと思います。

**Comment by hagitako** [comment]
環境によってパスが違うということはないですか？

ちなみにわたしの環境では、**/pleasanter**がついていると404のエラーになります。
> url: 'http://192.168.1.17/pleasanter/api/users/get',
>> url: 'http://192.168.1.17/api/users/get',
といった感じで、**/pleasanter**をとってみても同じようにエラーですかね？
