### ISSUE TITLE
SQLのデータベース

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#295]
最近、データベースの使用量、7.9Gになって少しでも減らせないかなと思っています。

データベースを開くと以下のような項目が増えていきます。
![1](https://user-images.githubusercontent.com/39452628/93657494-610fe680-fa6e-11ea-845e-4f3066da92be.png)

これは削除してもよいものでしょうか？

ご存じの方、いらっしゃいますか？

**Comment by kazuca** [comment]
それらのテーブルに関しては消してしまっても問題ないようです。私の管理している環境では問題ありませんでした。
あとはSysLogの削除ぐらいでしょうか。

**Comment by akiyamashino** [comment]
いつもありがとうございます。

syslogは少し調べてみましたが、復旧モデルを単純に変更すること？。
別件での投稿の結果次第でもっと深く調べてみようと思います。

ありがとうございました。
