### ISSUE TITLE
PostgreSQL、Windows対応

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#296]
データベースの使用量が増えてきまして１０Gの壁が心配となり始めています。
マニュアルにはCentOS7の例は記載されていますが、WIndows版は記載されていません。

どなたかWindows版で試されて移行を成功されてた方いらっしゃいますか？

**Comment by kazuca** [comment]
手持ちの環境で空き環境があったので、トライしてみました。
Windows Server 2019 Datacenterとpgsql12.4の構成で試したところ動作することは確認しました。

![image](https://user-images.githubusercontent.com/37392077/93851847-da683d00-fceb-11ea-9f0c-40fb12f27b56.png)

pgsqlの設定は、プリザンターのマニュアルだと認証方法を変更する様に指示がありますが、こちらは不要です。Windowsだとmd5がデフォルトなので。GDI+のインストールも不要です。pgsqlのExtensionの設定はコマンドベースでも出来ますが、pgAdminから操作した方が楽かもしれません。

IIS回りの設定は[MSのドキュメント](https://docs.microsoft.com/ja-jp/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1)を参照するとわかりやすいかと思います。

あとは、zipの``pleasanter\Implem.Pleasanter``の中身を指定した物理パスに展開すればOKです。500.30のエラーが出る場合は、上記の32ビット固定を確認して問題無ければアプリケーションプールを停止→開始してください。

akiyamashinoさん、確かBinaryStorageをLocalで運用されてましたよね？
一応、当方でもLocalで検証したところぱっと見では問題ありませんでした。ですが、何か障害が出るかもしれません。この部分は要検証でお願いします。

**Comment by akiyamashino** [comment]
kazuca様、いつもありがとうございます。

私もテスト機で時間が確保できたら試してみたいと思います。（兼務のため中々）
（本当の移行は切羽詰まった時にしたいと思います）

出来ると分かって、尚且つこれだけ情報を頂けると感謝感謝で。

大変ありがとうございました。

**Comment by akiyamashino** [comment]
やっと試してみました。
”Windowsで.NET Core版のプリザンターを動かしてみたという書き込みを見つけたので試してみました。”と
いいうホームページを見つけましたのでお手本にしました。（リンクを貼ってよいものか）
テスト起動は確認出来て感動しておりましたが、
IISでアプリケーションの追加をしてもHTTP 500のエラーで

> IIS回りの設定はMSのドキュメントを
  理解することが出来なかったです。


以下、やったことの羅列ですが、
１．Windows版PostgreSQL 12.5をインストールする。
    環境変数に追加
      ・pathにC:\Program Files\PostgreSQL\12\binを追加。
      ・PGDATAを作り、C:\Program Files\PostgreSQL\12\dataを記入。
2.SQL Shell(psql)からPostgreSQL設定。
     データベース作成。
     create database "Implem.Pleasanter";

     全文検索用モジュール（pg_trgm）のインストール（以下のコマンドでエラーは出ていませんでしたが・・・）
     \c "Implem.Pleasanter";
     CREATE EXTENSION pg_trgm;
3.https://dotnet.microsoft.com/download/dotnet-core/3.1 から、SDKの32bit版とHosting Bundleをダウンロード、インストール。
4.プリザンター（.NET Core版）のダウンロード(https://pleasanter.org/dlcenter)
  C:\inetpub\wwwroot\pleasanterに配置。
5.Rds.jsonを編集。
   "Dbms": "PostgreSQL",
   Port=5432;を追加
   パスワードを記入。
6.CodeDefinerを実⾏。
   cd C:\inetpub\wwwroot\pleasanter\Implem.CodeDefiner
   dotnet Implem.CodeDefiner.NetCore.dll _rds
7.プリザンター起動の確認。
   cd ..\Implem.Pleasanter
   dotnet Implem.Pleasanter.NetCore.dll
   
    http://localhost:5000で起動の確認。

8. プリザンターをIISに配置
    HTTP　500のエラーで。
    IIS AppPool\NetCoreAppPoolも共有に追加したのですが。

以上、お付き合いして頂ける方がいらっしゃいましたらアドバイスお願いします。

**Comment by akiyamashino** [comment]
公式マニュアルを見ながら起動までできるようになりました。
ありがとうございました。
