### ISSUE TITLE
環境構築におけるDBエラーについて

### ISSUE THREAD

**Issue by kingkino** [Implem/Implem.Pleasanter#3]
自身のPCのローカル環境にPleasanterを立てようとしているのですがDB作成時に下記のエラーで止まってしまいます。

`{"オブジェクト名 'SysLogs' が無効です。"}`

発行しようとしているSQLは下記の通り。

```
declare @_I bigint;
insert into [SysLogs]([Creator],[Updator],[MachineName],[ServiceName],[Application],[Class],[Method],[InDebug],[AssemblyVersion],[Comments]) values(@_U,@_U,@MachineName_Param,@ServiceName_Param,@Application_Param,@Class_Param,@Method_Param,@InDebug_Param,@AssemblyVersion_Param,@Comments_Param); set @_I = @@identity select @_I;
;
```

環境構築はクローンしたソースをVSから起動して実行してます。
SQLServerへのアクセスはできているようです。
接続文字列は下記のものをRDS.JSONに記載しています。

` Data Source=DESKTOP-I4NEMUH\\PLESANTERDEV;User ID=sa;Password=＊＊＊＊＊;Initial Catalog=pledev;Connect Timeout=15;Encrypt=False;`

他に設定とか必要があればご指摘いただけると助かります。

**Comment by Implem** [comment]
kingkino様

Uchidaです。Issueありがとうございます。

DBの作成に失敗する場合、以下をご確認ください。
・スタートアッププロジェクト
　Implem.CodeDefinerになっているかご確認ください。
・Implem.CodeDefinerのコマンドライン引数
　「_rds」になっているかご確認ください。
・Rds.Jsonの設定
　Azure環境の場合プロバイダとタイムゾーンの設定が以下になっているかご確認ください。
    "Provider": "Azure",
    "TimeZoneInfo": "UTC",
・Rds.Jsonの3つの接続文字列
　下記3つの接続文字列の接続先が正しいかご確認ください。Azure環境の場合には
　SaConnectionString：インスタンスの管理者権限
　OwnerConnectionString：
　　　ローカル環境の場合：作成したDBのオーナー権限（ユーザは自動で作成されます）
　　　Azure環境の場合：SaConnectionStringと同じ設定にします
　UserConnectionString：
　　　ローカル環境の場合：作成したDBのR/W権限（ユーザは自動で作成されます）
　　　Azure環境の場合：SaConnectionStringと同じ設定にします

上記が問題ない場合にはエラー発生時の状態について、もうすこし情報ください。
・DBが作成できているか
・ローカル環境の場合ユーザが作成できているか（OwnerとUserの2つ）
・テーブルが1つ以上作成できているか
・SysLogsテーブルが作成できているか
・スタックトレース（デバッグモードで実行しスタックの内容をコピー＆ペースト）

お手数ですが、よろしくお願い致します。

**Comment by kingkino** [comment]
ローカル環境での構築はとん挫したのでAzureのSqlDatabaseに構築しました。
Azure側はご教示いただいた内容で構築できました。
ありがとうございました。
