### ISSUE TITLE
分類の選択で「指定された情報が見つかりませんでした」のエラー

### ISSUE THREAD

**Issue by kudarisenmon** [Implem/Implem.Pleasanter#30]
分類Aの選択肢一覧を以下のように設定しました。

01,リンゴ,apple
10,ぶどう,grape
20,パイナップル,pineapple

さらに「検索機能を使う」にチェックを付けています。

この状態でレコードの新規作成や既存のレコードの更新で分類Aの「リンゴ」を選択すると「指定された情報が見つかりませんでした」のエラーが出ることがあります。
検索機能を使っていてゼロから始まる選択肢が選ばれた場合でかつブラウザに依存しているようです。

以下のブラウザでは発生します。
Internet Explore 11.1198.14393.0
Microsoft Edge 38.14393.0.0

以下では発生しません。
Firefox 57.0
Google Chrome 62.0.3202.94
![default](https://user-images.githubusercontent.com/2560699/33922709-e773184a-e00f-11e7-9086-c6e2e75d932e.PNG)

**Comment by Implem** [comment]
情報ありがとうございます。ブラウザ依存の何かがありそうですね。こちらでも再現のトライをしてみます。

**Comment by Implem** [comment]
IEやEdgeだと、li要素のvalue属性に01とセットすると1になってしまうようなので、data-value属性に変更することで解消しました。

https://github.com/Implem/Implem.Pleasanter/commit/c6adfa4e87e16f4f33cf2f252719bb03f57b3fd8

**Comment by kudarisenmon** [comment]
バージョン0.45.1.29417で正しく動作するのを確認しました。
