### ISSUE TITLE
API複数レコード取得の検索条件

### ISSUE THREAD

**Issue by YoshikiSawada** [Implem/Implem.Pleasanter#305]
いつも便利に使わせていただいております。

API複数レコード取得の検索条件について質問させてください。
（API複数レコード取得　https://pleasanter.net/fs/publishes/428033/edit）

「分類A」に文字列「abc」を含むレコードを取得したい、という意図で
下記のようなリクエストを送信すると、「aaa」「aab」「aac」もヒットしてしまいます。
```
{
  "ApiKey": "XXXXXXXXXX...",
  "View": {
    "ColumnFilterHash": {
      "ClassA": "[\"abc\"]"
    }
  }
```

SQLで記述すると、意図は`ClassA like '%abc%'`なのですが、実際には`ClassA like '%a%' or '%b%' or '%c%'`
になってしまっているようです。（「a」「b」「c」もヒットしました。）

リクエストの書き方に間違いがあるようでしたらご指摘いただけないでしょうか。

下記バージョンで確認しました。
0.50.121.22343
0.50.191.27206

よろしくお願いいたします。

**Comment by Oooooomin2** [comment]
僕も見てみたのですが、どうやら仕様が以下のようになっているみたいです。

【エディタタブ > 分類項目の詳細設定で選択肢一覧を設定している場合】
→完全一致検索。指定は配列形式

```
"ColumnFilterHash": {
    "ClassA": "[\"abc\"]"
}
```

【エディタタブ > 分類項目の詳細設定で選択肢一覧を設定していない場合】
→部分一致検索。指定は文字列形式

```
"ColumnFilterHash": {
    "ClassA": "abc"
}
```

一覧画面のフィルタと同様のロジックを利用していました。
なので配列形式ではなく、文字列形式でリクエストを投げれば上手くヒットするかもしれません。


なお、現在の最新版(0.50.200.xxxxx)ではフィルタタブの分類、タイトル、内容、説明項目にて検索方法が選択できるようになったようです。

【エディタタブ > 分類項目の詳細設定で選択肢一覧を設定している場合】
→完全一致検索。指定は配列形式

【エディタタブ > 分類項目の詳細設定で選択肢一覧を設定していない場合】
→フィルタタブの検索方法設定にセットした検索方法。指定は文字列形式

**Comment by YoshikiSawada** [comment]
分類項目が一覧設定されて「いる」／「いない」で、
APIの検索文字列の書き方が変わるということなのですね。

仰る通り、配列形式から文字列形式に変更するとを外すと、
部分一致検索になりました。

本番サイト・データでうまくいくか試してみます。
（うまくいかなかったら、最新版を試してみます。）

ありがとうござました！！
