### ISSUE TITLE
ファイルの添付

### ISSUE THREAD

**Issue by mmyykk2424** [Implem/Implem.Pleasanter#31]
お世話になっております。

本ソフトウェアを職場に導入させて頂いており、非常に自由度が高く便利に利用しているところです。
そこで、機能としてファイルの添付が出来ればもっと活用の幅が広がり、ファイルサーバ上にある
ファイルの整理も出来そうなのですが、テーブルに対してファイル添付の欄を付けることは可能でしょうか？

どうぞよろしくお願いいたします。

**Comment by yyuki23** [comment]
私も以前同じ質問をしていましたので、そのURLを共有させていただきます。
https://github.com/Implem/Implem.Pleasanter/issues/25

**Comment by Implem** [comment]
ファイル添付についてはもうしばらくお時間ください。

**Comment by mmyykk2424** [comment]
>yyuki23さん
全く同じ質問でした…。
ありがとう御座います。

> Implemさん
是非ともご検討をお願いします。
