### ISSUE TITLE
フォルダ内のソート

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#313]
フォルダ内でWikiをたくさん作っています。
その表示順番を更新時などフォルダごとに指定できないでしょうか？
（あれば便利だな位のですが。もちろん今の固定レイアウトがなくなると困りますが）

**Comment by kazuca** [comment]
jQueryのsort()を使えば似たようなことが出来ます。
Wikiのみがフォルダに含まれているという条件だと下記のスクリプトを全ての条件で追加すればOKです。

```
$('#SiteMenu > .cf:nth-child(2) > ul.nav-sites').html($('li.nav-site:not(.to-parent)').sort(function (a, b) {
    if ($("a >.conditions > .elapsed-time", a).attr('title') > $("a >.conditions > .elapsed-time", b).attr('title')) {
        return -1;
    } else {
        return 1;
    }
}));
```

更新日が新しい順に並ぶようにしていますが、逆にしたい場合はreturn値を逆にするか、if文中の不等号を反転させて下さい。

**Comment by akiyamashino** [comment]
kazuca様、いつもありがとうございます。
早速、試してみました。作動しました。

> Wikiのみがフォルダに含まれているという条件だと下記のスクリプトを全ての条件で追加すればOKです。
    実はフォルダが一個あります。それはいつも先頭に表示したいのですが・・・。
　実運用は部署のルールがWikiで存在し、過去のルールとなったものはそのフォルダに移動しています。
　（見返すこともあるので。なぜWikiかと言うと１ルール、１アイコンでコメント追加でき視覚的に使いやすいので）

いつも他力本願ですみません。もし気が向きましたらで。（コード見ても・・・。if,returnなどc言語と変わらない部分は分かるのですが・・・。他にも他の方のブログみてコピーして使ってばかりで・・・）

あと、別件の Progate SQLのIssue(Windowsへインストール)の件ありがとうごいざます。１２月に時間が確保出来そうなのでテスト環境で試して来年の４月くらいに移行しようと思います。大変、ありがとうございました。

**Comment by kazuca** [comment]
こんな感じでいかがでしょうか？

```
$('#SiteMenu > .cf:nth-child(2) > ul.nav-sites').html($('li.nav-site:not(.to-parent):not(.wikis)') + $('li.nav-site:not(.to-parent).wikis').sort(function (a, b) {
    if ($("a >.conditions > .elapsed-time", a).attr('title') > $("a >.conditions > .elapsed-time", b).attr('title')) {
        return -1;
    } else {
        return 1;
    }
}));
```

**Comment by akiyamashino** [comment]
ありがとうございます。申し訳ないです。
早速、コピーさせて頂きました。（すみません）
うまく動作させることが出来ませんでした。
Wikiサイト達が表示されず、[object][object]と表示さるだけで・・・。

もう一点ですが、
ソート順ですがサイトアイコン横に表示されている日数でソートでないようです。（内部データ基準？）
サブフォルダに移動してまた、元のフォルダに戻ると上記のような状態になります。

ご報告です。（返信はもし気が向きましたらで）

いつもお力を貸して頂いてありがとうございます。

**Comment by kazuca** [comment]
失礼しました。マージしないといけないですね。

```
$('#SiteMenu > .cf:nth-child(2) > ul.nav-sites').html($.merge($('li.nav-site:not(.to-parent):not(.wikis)'), $('li.nav-site:not(.to-parent).wikis').sort(function(a, b) {
    if ($("a >.conditions > .elapsed-time", a).attr('title') > $("a >.conditions > .elapsed-time", b).attr('title')) {
        return -1;
    } else {
        return 1;
    }
})));
```

こんな感じでいかがでしょうか？

**Comment by akiyamashino** [comment]
ありがとうございます。
早速、コピーさせて頂きました。（すみません）
二つとも問題なさそうです。これから使い込んでいきます。

ありがとうございました。

**Comment by akiyamashino** [comment]
ありがとうございました。
