### ISSUE TITLE
「通知」機能にCCを設定したい

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#32]
お世話になっております。
先日は、勉強会を開催いただきありがとうございました。
すみませんが、また質問をさせてください。

「通知」機能で宛先のメールアドレスを指定することができると思うのですが、
加えて、CCに自分自身を設定する。というようなことは可能でしょうか？

以上、どうぞご確認よろしくお願いいたします。

**Comment by Implem** [comment]
Notification.jsonあたりにスイッチを作って、切り替えできるようにすると良いとおもいます。できればプルリクエストもらえると助かります。
