### ISSUE TITLE
ユーザーの所属組織の初期表示

### ISSUE THREAD

**Issue by takaoyama** [Implem/Implem.Pleasanter#33]
項目「分類」で、ユーザーの所属する組織名を初期表示することは可能でしょうか。

分類の選択肢に[[Depts]]と設定すると、全組織が選択可能ではありますが、
ユーザーの組織を初期表示させておくと便利で入力間違いも減らせると思っています。

**Comment by Implem** [comment]
なるほどこれは良い案ですね。実装は可能なので検討してみます。可能であればプルリクエストいただけると幸いです。

**Comment by takaoyama** [comment]
よろしくお願いいたします。
（プルリクエストもできれば頑張ってみたいと思います。）
