### ISSUE TITLE
分類項目へのスタイルの適用について

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#332]
分類項目に対して、状況と同じようにスタイルを追加して使用していました。
分類項目が複数選択可能になったタイミングから、スタイルが適用されなくなってしました。複数選択に対してチェックを入れていない時は、従来と同じ挙動にすることは可能でしょうか？

**Comment by kazuca** [comment]
出力されているHTMLを確認したところ、設定したスタイル名がセルのタグのどこにも出力されていないようです。

マニュアルに記載済みの方法なので、出来なくなるのは非常に困ります・・・。

https://pleasanter.net/fs/publishes/822069/edit

**Comment by uchi-ta** [comment]
本件、Wikiでマスタを作成している際に同様の問題がございました。修正版を公開いたしましたのでバージョンアップをお願いします。

**Comment by kazuca** [comment]
対応頂きありがとうございます。
しかし、バージョンアップしてみましたが、状況は改善されていません。
エディタ内ではスタイルは適用されていますが、一覧などでも反映されていません。

**Comment by uchi-ta** [comment]
ご指摘のように一覧画面でp要素が出力されない問題がございました。修正版を公開いたしましたので、最新バージョンでご確認ください。

**Comment by kazuca** [comment]
対応ありがとうございます。
0.50.218で解消されていることが確認出来ました。
