### ISSUE TITLE
PostgreSQL利用時は検索すると大文字小文字が区別されます。

### ISSUE THREAD

**Issue by noyome123** [Implem/Implem.Pleasanter#334]
テーブルに「Abc」という文字列がある場合。
検索ワードで「abc」「ABC」「aBC」だとヒットしません。
検索ワードが「Abc」だとヒットします。

SQLServerだと「abc」でも「ABC」でも「aBC」でも「Abc」でもヒットします。

PostgreSQLの仕様といえば仕様なのですが・・・。
それとも私だけでしょうか？

**Comment by kazuca** [comment]
私の環境でもPostgreSQL環境だと大文字、小文字は区別されます。
生成されるクエリで``ILIKE``を使っていないようなので、こればかりは仕方が無いかなと思います。

**Comment by noyome123** [comment]
やはりそうですか。
検索部分でなかなか導入に踏み出せない状況です。大人しくSQL Serverを利用するようにいたします。
対応していただけたらありがたいですね。

**Comment by uchi-ta** [comment]
PostgreSQLを使用する際はILIKEを使用してSQL Serverと同様に大文字、小文字を区別しないようにしました。最新バージョン Pleasanter.NetCore_1.1.14.0 でお試しください。

**Comment by noyome123** [comment]
最新バージョンにて検索がSQL Serverと同様に大文字、小文字が区別されないことを確認いたしました。
ご対応ありがとうございます。

**Comment by uchi-ta** [comment]
早々のご確認ありがとうございます。
