### ISSUE TITLE
他サイトの数値項目を一覧に追加するとアプリケーションエラーが発生する

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#337]
他サイトの数値項目を一覧に追加するとアプリケーションエラーが発生することがあります。

NumDを追加していた場合
``
列 'NumD' はテーブル Main に属していません。
``

``
  場所 System.Data.DataRow.GetDataColumn(String columnName)
   場所 System.Data.DataRow.get_Item(String columnName)
   場所 Implem.Pleasanter.Libraries.DataTypes.Num..ctor(DataRow dataRow, String name) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataTypes\Num.cs:行 31
   場所 Implem.Pleasanter.Models.ResultModel.Set(Context context, SiteSettings ss, DataRow dataRow, String tableAlias) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultModel.cs:行 2546
   場所 Implem.Pleasanter.Models.ResultModel..ctor(Context context, SiteSettings ss, DataRow dataRow, Dictionary`2 formData, String tableAlias) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultModel.cs:行 615
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlGrids.<>c__DisplayClass5_0.<Tr>b__7(Column column) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlGrids.cs:行 473
   場所 Implem.Libraries.Utilities.Linqs.ForEach[T](IEnumerable`1 source, Action`1 action) 場所 C:\Implem\Release\Implem.Libraries\Utilities\Linqs.cs:行 11
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlGrids.<>c__DisplayClass5_0.<Tr>b__2() 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlGrids.cs:行 312
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.Tr(HtmlBuilder hb, String id, String css, HtmlAttributes attributes, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 269
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlGrids.Tr(HtmlBuilder hb, Context context, SiteSettings ss, DataRow dataRow, IEnumerable`1 columns, Boolean editRow, Boolean checkRow, String idColumn, RecordSelector recordSelector, FormDataSet formDataSet) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlGrids.cs:行 267
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlGrids.<>c__DisplayClass4_0.<GridRows>b__0(DataRow dataRow) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlGrids.cs:行 185
   場所 Implem.Libraries.Utilities.Linqs.ForEach[T](IEnumerable`1 source, Action`1 action) 場所 C:\Implem\Release\Implem.Libraries\Utilities\Linqs.cs:行 11
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlGrids.GridRows(HtmlBuilder hb, Context context, SiteSettings ss, IEnumerable`1 columns, EnumerableRowCollection`1 dataRows, FormDataSet formDataSet, RecordSelector recordSelector, Boolean editRow, Boolean checkRow) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlGrids.cs:行 184
   場所 Implem.Pleasanter.Models.IssueUtilities.<>c__DisplayClass6_0.<GridRows>b__1() 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 404
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.TBody(HtmlBuilder hb, String id, String css, HtmlAttributes attributes, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 233
   場所 Implem.Pleasanter.Models.IssueUtilities.GridRows(HtmlBuilder hb, Context context, SiteSettings ss, GridData gridData, List`1 columns, View view, IssueModel issueModel, Boolean editRow, Int64 newRowId, Int32 offset, Boolean clearCheck, String action) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 391
   場所 Implem.Pleasanter.Models.IssueUtilities.<>c__DisplayClass4_0.<Grid>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 224
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.Table(HtmlBuilder hb, String id, String css, HtmlAttributes attributes, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 160
   場所 Implem.Pleasanter.Models.IssueUtilities.Grid(HtmlBuilder hb, Context context, SiteSettings ss, GridData gridData, View view, String action) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 216
   場所 Implem.Pleasanter.Models.IssueUtilities.<>c__DisplayClass0_0.<Index>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 48
   場所 Implem.Pleasanter.Models.IssueUtilities.<>c__DisplayClass1_0.<ViewModeTemplate>b__3() 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 123
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.Div(HtmlBuilder hb, String id, String css, HtmlAttributes attributes, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 342
   場所 Implem.Pleasanter.Models.IssueUtilities.<>c__DisplayClass1_0.<ViewModeTemplate>b__1() 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 98
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 81
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.Form(HtmlBuilder hb, HtmlAttributes attributes, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 609
   場所 Implem.Pleasanter.Models.IssueUtilities.<>c__DisplayClass1_0.<ViewModeTemplate>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 89
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.<>c__DisplayClass7_0.<Content>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 294
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.Div(HtmlBuilder hb, String id, String css, HtmlAttributes attributes, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 342
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.Content(HtmlBuilder hb, Context context, SiteSettings ss, View view, Types errorType, String[] messageData, Int64 siteId, String title, Boolean useBreadcrumb, Boolean useTitle, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 272
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.<>c__DisplayClass6_0.<MainContainer>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 229
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.Div(HtmlBuilder hb, String id, String css, HtmlAttributes attributes, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 342
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.MainContainer(HtmlBuilder hb, Context context, SiteSettings ss, View view, VerTypes verType, MethodTypes methodType, Int64 siteId, Int64 parentId, String referenceType, String siteReferenceType, String title, Types errorType, String[] messageData, Boolean useBreadcrumb, Boolean useTitle, Boolean useSearch, Boolean useNavigationMenu, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 229
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.<>c__DisplayClass0_0.<Template>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 47
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 81
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.Body(HtmlBuilder hb, String style, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 89
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.<>c__DisplayClass1_0.<Container>b__0() 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 103
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, String id, String css, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 99
   場所 Implem.Pleasanter.Libraries.Html.HtmlBuilder.Append(String tag, HtmlAttributes attributes, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\Html\HtmlBuilder.cs:行 81
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTags.Html(HtmlBuilder hb, String lang, Boolean _using, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTags.cs:行 15
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.Container(HtmlBuilder hb, Context context, SiteSettings ss, String body, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 101
   場所 Implem.Pleasanter.Libraries.HtmlParts.HtmlTemplates.Template(HtmlBuilder hb, Context context, SiteSettings ss, View view, VerTypes verType, MethodTypes methodType, Int64 siteId, Int64 parentId, String referenceType, String siteReferenceType, String title, String body, Boolean useBreadcrumb, Boolean useTitle, Boolean useSearch, Boolean useNavigationMenu, String script, String userScript, String userStyle, ServerScriptModelRow scriptValues, Action action) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\HtmlParts\HtmlTemplates.cs:行 43
   場所 Implem.Pleasanter.Models.IssueUtilities.ViewModeTemplate(HtmlBuilder hb, Context context, SiteSettings ss, View view, String viewMode, Action viewModeBody) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 76
   場所 Implem.Pleasanter.Models.IssueUtilities.Index(Context context, SiteSettings ss) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 43
   場所 Implem.Pleasanter.Models.ItemModel.Index(Context context) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Items\ItemModel.cs:行 375
   場所 Implem.Pleasanter.Controllers.ItemsController.Index(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 19
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
``

Ver. 0.50.221.24005

**Comment by uchi-ta** [comment]
ご連絡ありがとうございます。修正版 Pleasanter.0.50.222.21064 を提供いたしました。

**Comment by kazuca** [comment]
対応ありがとうございます。0.50.222で現象が発生しないことが確認出来ました。
