### ISSUE TITLE
〈急〉ビューをエクスポートすると、表示されている一覧ではなく全件がエクスポートされます。

### ISSUE THREAD

**Issue by NakaishiYoshihiro** [Implem/Implem.Pleasanter#338]
バージョンアップしたところ、ビューをエクスポートすると、表示されている一覧ではなく全件がエクスポートされます。
ビューで対象を絞ってエクスポート→処理をおこなっていたので困っています。

ビューの状態がエクスポートされるようにする方法はありますか？

**Comment by sato-ha** [comment]
ビューを使用していない状態でフィルタを使って条件を絞り込んでも同様に全件がエクスポートされるようです。
