### ISSUE TITLE
サイト画像設定：透過PNGで透過部分が黒く表示されます

### ISSUE THREAD

**Issue by yuchi78** [Implem/Implem.Pleasanter#34]
フォルダやサイトの「サイト画像」設定で、透過部分のあるPNG画像を設定したところ透過部分が黒く表示されてしまいます。
バージョン 0.44.1.26783
※画像を表示するだけのhtmlページを作成して確認してみましたが、そちらでは表示に問題なさそうでした（透過部分は黒くならずに表示されました）

**Comment by Implem** [comment]
たしかに、透過GIFでやると黒くなってしまいますね。.NETのライブラリをつかっていて私も対処法を知らないのですが、知見のある方がいたらおしえてください。
