### ISSUE TITLE
数値項目を一括変更しようとするとエラーが発生する

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#340]
数値項目を一括変更しようとするとエラーが発生します。

Ver. 0.50.222.21064

``
オブジェクトの型 Implem.Pleasanter.Libraries.DataTypes.Num から既知のマネージ プロバイダーのネイティブ型へのマップがありません。
``

``
   場所 System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   場所 System.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   場所 System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   場所 System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters, Boolean includeReturnValue)
   場所 System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   場所 System.Data.SqlClient.SqlCommand.ExecuteScalar()
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.<>c__DisplayClass13_0.<ExecuteScalar>b__0() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 111
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.Try(Action action) 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 179
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteScalar() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 113
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteScalar_response() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 244
   場所 Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteScalar_response(Context context, String connectionString, Boolean transactional, Boolean selectIdentity, Boolean writeSqlToDebugLog, SqlStatement[] statements) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataSources\Rds.cs:行 190
   場所 Implem.Pleasanter.Libraries.DataSources.Repository.ExecuteScalar_response(Context context, String connectionString, Boolean transactional, Boolean selectIdentity, Boolean writeSqlToDebugLog, SqlStatement[] statements) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataSources\Repository.cs:行 18
   場所 Implem.Pleasanter.Models.ResultUtilities.BulkUpdate(Context context, SiteSettings ss, SqlWhereCollection where) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultUtilities.cs:行 3081
   場所 Implem.Pleasanter.Models.ResultUtilities.BulkUpdate(Context context, SiteSettings ss) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Results\ResultUtilities.cs:行 2933
   場所 Implem.Pleasanter.Models.ItemModel.BulkUpdate(Context context) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Items\ItemModel.cs:行 1984
   場所 Implem.Pleasanter.Controllers.ItemsController.BulkUpdate(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 590
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
``

**Comment by uchi-ta** [comment]
ご連絡ありがとうございます。修正版 Pleasanter.0.50.223.37086 を提供いたしました。

**Comment by kazuca** [comment]
対応ありがとうございます。修正されていることが確認できました。
