### ISSUE TITLE
フィルタで「自分」を選択時に、フィルタされた項目の編集画面に遷移できない

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#342]
フィルタで「自分」を選択時に、フィルタされた項目の編集画面に遷移できないという現象が発生しています。

Ver.0.50.224.33629

``
変数名 '@_U' は既に宣言されています。変数名は、クエリ バッチまたはストアド プロシージャ内で一意にしてください。
``

``
   場所 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   場所 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   場所 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   場所 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   場所 System.Data.SqlClient.SqlDataReader.get_MetaData()
   場所 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   場所 System.Data.SqlClient.SqlCommand.ExecuteScalar()
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.<>c__DisplayClass13_0.<ExecuteScalar>b__0() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 118
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.Try(Action action) 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 197
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteScalar() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 120
   場所 Implem.Libraries.DataSources.SqlServer.SqlIo.ExecuteScalar_int() 場所 C:\Implem\Release\Implem.Libraries\DataSources\SqlServer\SqlIo.cs:行 221
   場所 Implem.Pleasanter.Libraries.DataSources.Rds.ExecuteScalar_int(Context context, String connectionString, Boolean transactional, Boolean writeSqlToDebugLog, SqlStatement[] statements) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataSources\Rds.cs:行 74
   場所 Implem.Pleasanter.Libraries.DataSources.Repository.ExecuteScalar_int(Context context, String connectionString, Boolean transactional, SqlStatement[] statements) 場所 C:\Implem\Release\Implem.Pleasanter\Libraries\DataSources\Repository.cs:行 61
   場所 Implem.Pleasanter.Models.IssueUtilities.GetSwitchTargets(Context context, SiteSettings ss, Int64 issueId, Int64 siteId) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 2274
   場所 Implem.Pleasanter.Models.IssueUtilities.Editor(Context context, SiteSettings ss, Int64 issueId, Boolean clearSessions) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:行 1317
   場所 Implem.Pleasanter.Models.ItemModel.Editor(Context context) 場所 C:\Implem\Release\Implem.Pleasanter\Models\Items\ItemModel.cs:行 930
   場所 Implem.Pleasanter.Controllers.ItemsController.Edit(Int64 id) 場所 C:\Implem\Release\Implem.Pleasanter\Controllers\ItemsController.cs:行 259
   場所 lambda_method(Closure , ControllerBase , Object[] )
   場所 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   場所 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   場所 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   場所 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
``

**Comment by uchi-ta** [comment]
ご不便おかけしました。本件、SQLの不具合がございましたので修正いたしました。

**Comment by kazuca** [comment]
対応頂きありがとうございます。問題が解消されていることが確認出来ました。
