### ISSUE TITLE
サイト画像設定「なし」の状態に戻したい

### ISSUE THREAD

**Issue by yuchi78** [Implem/Implem.Pleasanter#35]
一旦サイト画像を設定したあと、やっぱりサイト画像なしでテキストのみの表示に戻したい場合、
何か設定方法等はあるでしょうか？
（ヘルプページでは、サイト画像設定すると変更はできるが削除はできないと記載がありましたのでやはり無理でしょうか・・）
 バージョン 0.44.1.26783

**Comment by Implem** [comment]
SQL Server Management Studio等で、Binariesテーブルの内容をクリアしていただくと画像の削除が可能です。今後は削除機能を提供する予定です。

**Comment by yuchi78** [comment]
回答ありがとうございます。教えていただいた方法で削除してみます！
削除機能も追加される予定とのことですので、楽しみに待ちたいと思います＾＾
