### ISSUE TITLE
レスポンシブモードのステータス取得について

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#350]
プリザンター側でレスポンシブモードになっているかどうかをスクリプト側などで判断することが出来るメソッドを追加することは可能でしょうか？
現状、自前でレスポンシブ対応させているところがあるのですが、それはスクリーンサイズのみで判断させています。もし可能なら、プリザンター側の挙動を合わせてしましたいと考えています。
jsライブラリを使えば、モバイル判定は同等のものが行えるのですが、それだとレスポンシブをメニューから無効にしたときやパラメータ、サイト設定から判別が出来ないため、メソッドの追加をお願いしたいです。

**Comment by uchi-ta** [comment]
$p.responsive() で取得できるようにしました。

**Comment by kazuca** [comment]
対応頂きありがとうございます。
0.50.247.20221にて確認出来ましたので、クローズします。
