### ISSUE TITLE
見出しについて

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#353]
編集画面で、項目のレイアウトを整える目的で見出しを使っています。
現状、表示名が空の状態では保存出来ないのですが、可能にすることは出来ますでしょうか？
単純にセパレータとして使用することを想定しています。

現状、SiteSettingsを直接編集して変更しているのですが、可能ならGUIから出来るようにしていただけると助かります。

**Comment by uchi-ta** [comment]
GUIから設定可能としました。

**Comment by kazuca** [comment]
対応頂きありがとうございます。
0.50.247.20221にて確認出来ましたので、クローズします。
