### ISSUE TITLE
一括更新から項目が選択出来ない

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#354]
一括更新から項目が選択出来ない現象が発生しています。

Ver. 0.50.246.27157

**Comment by kazuca** [comment]
その他にも管理->ビュー-(新規・編集)->フィルタでもアイテムが選択出来ない現象も確認出来ました。

**Comment by uchi-ta** [comment]
ご不便おかけしてすみません。修正版を公開いたしました。

**Comment by kazuca** [comment]
0.50.247.20221にて現象が修正されていることが確認出来ましたので、クローズします。
