### ISSUE TITLE
保存先をファイルにするとサイト画像がリンク切れ

### ISSUE THREAD

**Issue by sts00455** [Implem/Implem.Pleasanter#355]
BinaryStorage.jsonを後述のように変更（＝保存先をDBからファイルへ変更）すると、サイト画像（アイコン）で設定した画像がアップロードは正常終了するのに、フォルダメニュー上のアイコンではリンク切れ（イメージリンク切れのｘイメージ）となり表示されない。添付ファイルは問題なく利用できており、フォルダ「SiteImage」「Images」「Attachments」はIIS_USRSへ権限付与済み。

【変更前】
　”Provider": ”Rds”,
　"Path": null,
　↓
【変更後】
　”Provider": ”Local”,
　"Path": "C:\\",

**Comment by kazuca** [comment]
設定ファイルがJSONなので、\はエスケープが必要です。エスケープ(\→\\)はされていますか？

**Comment by sts00455** [comment]
※個人情報保護のため、宛先を非表示（ＢＣＣ）にて送信しています。
-----------------------------------------------------


すみません。投稿時の入力ミスで
"Path": "C:\",ではなく
"Path": "C:\\",と設定し、エスケープしております。

添付ファイルは問題なく指定パスCに保存できています。
アイコン画像だけが、リンク切れになります。

**Comment by kazuca** [comment]
もし可能なら、バージョンと使用されているブラウザを教えていただけませんでしょうか？
当方の環境もLocalなのですが、同じ現象が再現できません。

当方の環境は、0.50.246 + (Chrome/IE/Edge/Firefox)です。

**Comment by kazuca** [comment]
現象再現できました。IEだと0.50.246でもダメですね。
画像をダウンロードしてみたところCMYKのビットマップとなっていました。IEの場合ビットマップはRGBでないとデコード出来ないので、そこが原因のようです。この部分は不具合のfix待ちになるかと思います。
