### ISSUE TITLE
選択肢：項目連携

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#357]
項目連携を使用しいるのですが、そこで出来たらよいなと言うことがります。
分類にリンクして選択肢を表示していますが、その順序を指定できないでしょうか？
現在、文字コード順だと思いますが、よく使う選択肢を上の方に持っていきたいです。
（選択肢の先頭に数字を付加するとよいのですがすでに３０万件あまり登録されてありまして）

以上、よろしくお願いいたします。

**Comment by kazuca** [comment]
https://pleasanter.org/manual/table-editor-choice-json

これで対応出来ませんか？
よく使う選択肢を上に上げるなら、サマリを使って適当な数値項目に件数を出しておいて、それを降順でソートするという対応は出来るかと思います。

**Comment by akiyamashino** [comment]
kazuca様、いつもありがとうございます。
簡単に出来ました。
項目連携の先に優先度と言う数値をセットで登録するようにして用意して
 以下のように記述すると希望の動作となりました。
（よく使う項目を自動で上の方にあげるのでなく登録者が指定したかっただけなので）

[
    {
        "SiteId": 879697,
        "View": {
            "ColumnSorterHash": {
                "NumA": "asc"
            }
        }
    }
]

以上、大変ありがとうございました。
