### ISSUE TITLE
リンクした項目で規定値を設定する方法

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#359]
ご存じの方、いらしゃいませんか？

実は、項目連携（複数選択可）した項目で新規作成時に初期値として２個を選択させた状態で次の選択をさせたいです。

以上、お手数をお掛けしますがよろしくお願いいたします。

**Comment by kazuca** [comment]
複数項目の場合の初期値は、次の様な設定でいけると思います。

```
["822804","822802"]
```

**Comment by akiyamashino** [comment]
毎度、毎度、ありがとうございます。
無事にいけました。（文字列でないのですね）

以上、大変ありがとうございます。
