### ISSUE TITLE
拡張SQL（インポート時、1件毎のUPDATE）

### ISSUE THREAD

**Issue by takaoyama** [Implem/Implem.Pleasanter#36]
お世話になっております。

インポートする際に1件毎に拡張SQLでUPDATEしたいのですが
現在はインポートが完了した後にUPDATE文が走る仕様とは別に
1レコードごとにUPDATEできるようにはできないでしょうか。

具体的には、月ごとにに１から連番を振りたいためです。
1レコードごとにある日付で範囲指定して取得した最大値に
「＋1」した値をセットしたいです。

よろしくお願いいたします。

**Comment by Implem** [comment]
T-SQLのカーソルを使っていただくと、インポートしたレコードをループして同様の事ができるとおもいます。ご検討ください！

**Comment by takaoyama** [comment]
承知しました。
カーソルで記述してみます。

ありがとうございました。
