### ISSUE TITLE
リンクされている先のレコード数が多いと表示に時間がかかる。

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#361]
0.50.248.22801で作成しています。
以下、表現がうまくいかないのですが

Aサイト（親）　　　　　ーーー　　　Bサイト（子）、Cサイト（子）・・・・
　・ステータス　　　　　　　　　　　　項目連連携でステータスを選択して名前入力
　・名前

ステータのスサイト
　選択肢：利用中、入院、退所・・・

子のサイトのレコード数が多いのでAサイトの編集画面に入る時に時間がかかります。
Bサイトのビューでリンクのビューのソータで日付で今年だけにして数を絞ると改善されます。
ここで問題なのですが、日付のソータで過去一年などの指定できないでしょうか？今年だけだと１月など少ししか表示されないので。
それか１００件分など指定する方法はないでしょうか？

以上、よろしくお願いします。

**Comment by kazuca** [comment]
ビューの条件にTakeが設定出来ると良いってことですよね。現状、見当たらない機能なので、私も欲しいです。
リンク項目の表示部分のテーブルに対して個別のビューを設定可能になって、Take、出来ればOffsetも設定可能になるとGoodというところですかね。
