### ISSUE TITLE
リンクした分類の子からのビューのソータで選択肢が表示されない。

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#362]
0.50.248.22801で作成しています。
以下、表現がうまくいかないのですが

Aサイト（親）　　　　　ーーー　　　Bサイト（子）、Cサイト（子）・・・・
　・ステータス　　　　　　　　　　　　項目連連携でステータスを選択して名前入力
　・名前

ステータのスサイト
　選択肢：利用中、入院、退所・・・

ここでBサイトでビューのソータでステータスを指定しても選択肢が表示されない。
現在、回避策でAサイトでステータスを変更時に別の分類にもテキストを保存するスプリクトを記述し
Bサイト等はソータする際はその分類を参照するように変更しています。

以上、何とかうまい方法はないでしょうか？

**Comment by kazuca** [comment]
私の環境でもView設定した選択肢で選択肢が表示されないという現象が出ています。
項目連携でA,Bとしているとき、AにViewを使っているという同じ設定なので、もしやと思って、項目連携を解除してみましたが、問題は解消せず・・・。

**Comment by akiyamashino** [comment]
Pleasanter.0.50.258.30459のバージョンで修正されていること確認しました。
