### ISSUE TITLE
分類の選択時のポップアップの位置

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#363]
0.50.248.22801で作成しています。
以前はそのようなことはなかったのですが、
分類を入力しようとして選択するとポップアップ画面が下の方に隠れてしまって
”選択”、”キャンセル”のボタンを押すためには毎回、ドラックしないといけない。
他のパソコンから操作しても同様でした。
何かよい解決方法はないでしょうか？
（どっかで位置を記録している？他の分類では隠れることがなかったので）

以上、よろしくお願いいたします。

**Comment by kazuca** [comment]
これ、私も気になってました。他のダイアログ(管理画面内の編集など)に関しては以前と挙動が変わらないので、複数選択肢の時に何か変わった？と思ってます。
コードを読んでもダイアログのトップの座標を計算している場所を見つけられなかったので、次のようなスクリプトを書いて対応しています。

```
$.('body').change(function () {
    var dialogHeightSetter = setInterval(function () {
        $(".ui-dialog").each(function () {
            if ($(this).attr('aria-describedby') === 'DropDownSearchDialog') {
                console.log('発火')
                $(this).css('top', ($(window).scrollTop() + ($(window).height() / 2) - ($(this).height() / 2)));
                clearInterval(dialogHeightSetter);
            }
        });
    }, 300);
});
```
スクリプトに新規・編集の条件で追加してもらえば動くと思います。
拡張スクリプトで一括設定することも可能ですが、イベントを発火させない条件をいくつか追加する必要があります。

**Comment by kazuca** [comment]
> 拡張スクリプトで一括設定することも可能ですが、イベントを発火させない条件をいくつか追加する必要があります。
って書いておきながら、「だろう」だったので、手持ち環境でやってみました。
さらっと調べた限りは問題なさそうです。

**Comment by akiyamashino** [comment]
いつもありがとうございます。

**Comment by kazuca** [comment]
typoがあったので、数カ所修正しています。

**Comment by akiyamashino** [comment]
0.50.249.31384で修正されていること確認。
