### ISSUE TITLE
ビューでソータの設定が消える

### ISSUE THREAD

**Issue by akiyamashino** [Implem/Implem.Pleasanter#369]
0.50.255.14710使用中です。

私の運用環境ではビューで絞り込めないことで発覚いたしました。

親サイトから子サイトの分類Aを選んでビューのソータをかけていました。
（ここ数か月、ビューの設定をいじっていない）
ソータの設定がなくなっていました。
　１．再度、設定しようにも分類Aが表示されません。
　２．一旦、ビューを消して再度、登録する際は表示れていて設定できますが、
　　　一度ビューで絞り込み、２度目を行うと絞り込めなくなります。
　　　１．と同じ状態です。

以上、よろしくお願いします。

**Comment by kazuca** [comment]
子サイトの項目だとフィルターもかけれられない状態になってます。
こちらは設定済みのものが設定から消える＆設定を保存しても消えるという現象も発生しています。

**Comment by uchi-ta** [comment]
ご不便おかけしました。下記のバージョンで修正いたしました。
Pleasanter.0.50.258.30459

**Comment by akiyamashino** [comment]
ソートではなくフィルタの表記の間違いでした。すみません。

Pleasanter.0.50.258.30459のバージョンで修正されていること確認しました。

ただし、ビューのすべてを見直し設定が消えている箇所は再設定が必要でした。他の方のご参考までに。
