### ISSUE TITLE
APIの利用方法について

### ISSUE THREAD

**Issue by Connie-Wild** [Implem/Implem.Pleasanter#37]
APIの実装ありがとうございます！
pleasanterを基盤として、各種連携が実現出来そうで大変うれしいです。

APIのリクエスト方法について教えて下さい。
UTF-8でリクエストを送っていますが、
{"Id":0,"StatusCode":401,"Message":"認証できませんでした。"}
と表示されます。
APIキーはAPI設定から生成されたものを利用しています。
下記のcurlコマンドを利用しているのですが、抜けているパラメータ等ありますでしょうか。

curl -H 'Content-Type:application/json' -d "{"ApiKey":"....."}" http://serverip/pleasanter/api_items/8220/get
※8220 : GetしたいレコードID

**Comment by Implem** [comment]
リクエストで必要なデータはAPIキーのみなので、問題が無いように思います。Content-Typeの指定は不要です。

401が発生する原因は、下記の2つです。
・Jsonのパースに失敗（Jsonのカッコの対応が正しくない、文字コードが正しく読めなかった等）
・ApiKeyの文字列をキーにユーザがselectできない（ユーザが無効か文字列が完全一致していない等）

ここのコードでチェックしています。
https://github.com/Implem/Implem.Pleasanter/blob/master/Implem.Pleasanter/Filters/CheckApiAuthentication.cs

なにかわかったらおしえてください。

**Comment by yyuki23** [comment]
-d '{"ApiKey":"hogehoge"}'
で取得できました。シングルクォートですね。

**Comment by Connie-Wild** [comment]
@yyuki23 さん
ありがとうございます！助かりました。

**Comment by Implem** [comment]
yyuki23さん、ありがとうございます！

**Comment by Connie-Wild** [comment]
headerが下記を含んでいないとエラーになりますね。
'Content-Type': 'application/x-www-form-urlencoded'

同じように詰まった人のためにnode.jsのサンプルコードを置いておきます。
```js
var request = require('request');
var options = {
  uri: "http://servername/pleasanter/api_items/{SiteId}/create",
  method: 'POST',
  encoding: 'utf8',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded'
  },
  json: {
    "ApiKey": "hogehoge",
    "Title": "TEST"
  }
};
request.post(options, function (error, response, body) {　　　
  console.log(body);
});
```
