### ISSUE TITLE
レコードの復元のご質問でございます。

### ISSUE THREAD

**Issue by titoigawa** [Implem/Implem.Pleasanter#371]
お世話になります、

今までクラウドの無料版を使用させて頂いておりまして、この度、AWSのEC2により独自環境を立ち上げました。
現時点では殆どの機能は使えておりますが、レコードの復元機能において以下のエラーが出ております。
再読み込みをしても、変わらない状況でございます。
もちろん、私しか使っておりません。

{0} さんが先に更新したため更新できません。再読み込みしてください。

環境について
・WinServer2019

どうぞ、よろしくお願いいたします。

**Comment by titoigawa** [comment]
追伸
Linux環境でも同じく、復元ができませんでした。
ご連絡、お待ちしております。

**Comment by uchi-ta** [comment]
ご不便おかけしました。下記のバージョンで修正いたしました。
Pleasanter.0.50.259
Pleasanter.NetCore.1.1.35

**Comment by titoigawa** [comment]
どうも、ありがとうございました。
正常に動く様になりました！

**Comment by uchi-ta** [comment]
ご確認ありがとうございます！
