### ISSUE TITLE
メール送信履歴の運用について

### ISSUE THREAD

**Issue by noyome123** [Implem/Implem.Pleasanter#379]
エディタからメールを送信した際に、送信履歴がエディタの下部に表示される仕様となっているかと思います。
https://pleasanter.org/manual/mail

「全般」「サイト画像」等、タブを切り替えても下部に送信履歴が表示されることに違和感があります。
例えば「メール履歴」タブを設けて、そこに一覧表示させてはどうでしょうか。

また、現状は送信履歴の削除機能がないかと思いますが、皆さん特に不要なんでしょうか。

**Comment by HireSake** [comment]
私もメール送信履歴を消せないのは不便だと思います。
うかつにテスト送信できません。
代替案として、コメント機能のようにメール送信履歴の表示を「項目」で管理できれば便利かと思います。
