### ISSUE TITLE
取得APIで時間を日本時間にしたい

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#38]
お世話になっております。
APIの公開ありがとうございます！！

レコードを取得するAPIを実行したところ、時間がUTCで取得されるようなのですが、
これを最初からJSTで取得させる方法はありますでしょうか？
同様に、作成APIを実行する際にJSTで作成させることは可能でしょうか？
（そもそもデプロイする時に、Rds.jsonのTimeZoneInfoをJapan standard timeとすればいい話でしょうか？）

ご確認よろしくお願いいたします。

**Comment by Implem** [comment]
Issueありがとうございます。バグとして修正しましたので、最新のソースでお試しください。
https://github.com/Implem/Implem.Pleasanter/commit/301a22787132d9d01d90a632753eaf11f0cf1dbd

**Comment by yyuki23** [comment]
返信が遅くなってすみません！
ご対応ありがとうございます！確認いたしました。
