### ISSUE TITLE
一覧表示にてコメントが表示されない。

### ISSUE THREAD

**Issue by re7git** [Implem/Implem.Pleasanter#380]
お世話になっております。

.netframework版バージョン0.50.183.19273からバージョン1.2.2.1にアップグレードしたところ、
テーブルの一覧表示でコメントが表示されなくなりました。
レコードを開くとコメントは存在しているのが確認できました。

よろしくお願いいたします。

**Comment by noyome123** [comment]
NetCore版を以前利用していた際はその不具合があり
1.1.14.0 → 1.1.35.0にアップデートし、事象が改善された覚えがあります。

先ほど、統合版の1.2.0.0 → 1.2.2.1にアップデートしましたが
特にコメントが表示されないとの不具合は再現されませんでした。

アップデート前の1.2.0.0も同様にコメントは表示されていました。

![Pleasant](https://user-images.githubusercontent.com/48504965/130023622-9c2b97eb-b9c1-4a8b-95f4-0199fd306590.PNG)

**Comment by uchi-ta** [comment]
https://github.com/Implem/Implem.Pleasanter/blob/master/Implem.Pleasanter/App_Data/Parameters/General.json

上記のパラメータに下記の設定があるかご確認ください。旧バージョンのパラメータで上書きすると設定がうしなわれていることがあります。

    "CommentDisplayLimitHistories": 1,
    "CommentDisplayLimit": 3,

**Comment by re7git** [comment]
ご解答ありがとうございます。
確認したところ、
旧バージョンのパラメーターと合わせた際にそちらの記述を削除しておりました。
パラメーターを追加してコメントが表示されるようになりました。
