### ISSUE TITLE
フィルタで「自分」を選択していると項目の詳細を表示できない。

### ISSUE THREAD

**Issue by re7git** [Implem/Implem.Pleasanter#381]
いつもお世話になっております。
先日プリザンターを.netframework版バージョン0.50.183.19273からバージョン1.2.2.1にアップグレードしたところ、
フィルターの自分の項目を選択していると、その項目の詳細画面に偏移する際に
アプリケーションで問題が発生しました。とでます。
以上、よろしくお願いいたします。

**Comment by kazuca** [comment]
私の環境でも同じ症状が出ています。チェックを入れるとそれ以降全ての画面(カンバンやカレンダーなど)で、症状が出ています。

**Comment by re7git** [comment]
お世話になっております。
1.2.7.0のアップデートでバグの解消がされたため、クローズとします。

**Comment by uchi-ta** [comment]
長らくご不便おかけしました。
