### ISSUE TITLE
文字数制限について

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#39]
お世話になっております。
「分類」「説明」について、それぞれ文字数制限や文字種制限のようなものはありますでしょうか？
（もし、まとまっているページがあったらすみません）
どうぞ、よろしくお願いいたします。

**Comment by Implem** [comment]
テーブル定義書が役に立つとおもいます。下記のパスにある「definition_Column.xlsm」をご参照ください。

https://github.com/Implem/Implem.Pleasanter/tree/master/Implem.Pleasanter/App_Data/Definitions

**Comment by yyuki23** [comment]
ありがとうございます。確認できました。
