### ISSUE TITLE
一覧画面のフィルタを初期状態で閉じて表示したい

### ISSUE THREAD

**Issue by hori-guchi** [Implem/Implem.Pleasanter#390]
お世話になっております。

"一覧"画面にフィルタと集計が初期状態で表示されていますが、項目数が増えると画面を占有してしまうため、初期状態で"集計"と"フィルタ"を閉じた状態で表示したいです。
ViewFilters をキーに css や js の各ファイルを確認したのですが、View.cs の記載を見てスタイルでの変更は無理なように見えました。
そのため、初期状態で"一覧", "フィルタ"を閉じた表示にできる機能を要望させていただきます。
よろしくお願いいたします。

**Comment by sato0928** [comment]
ビューの詳細設定でそのように設定可能です

**Comment by hori-guchi** [comment]
sato0928 様

コメントいただきましてありがとうございました。

"テーブルの管理""一覧"の下部にある"既定のビュー"に設定しているビューに対して、
"テーブルの管理""ビュー""詳細設定"の各タブを確認したのですが、該当する設定
項目を見つけることができませんでした。

該当する設定項目をご教示いただけますと助かります。

動作環境は
.NET Core版Pleasanter
バージョン1.1.27.0
となります。

**Comment by kazuca** [comment]
まずは、リリース情報を確認してみて下さい。

https://pleasanter.org/manual/release-notes-core-history
https://pleasanter.org/manual/release-notes-core

該当の機能が仕様できるのは、1.2.10.0からなので、アップデートが必要です。

> フィルタと集計の折り畳みをビューで設定する機能を追加。

**Comment by hori-guchi** [comment]
kazuca 様

コメントいただきましてありがとうございました。
アップデートを検討いたします。
今後もリリース情報を確認したいと思います。
