### ISSUE TITLE
画像の透過部分が真っ黒になる。

### ISSUE THREAD

**Issue by kingkino** [Implem/Implem.Pleasanter#4]
プロジェクトアイコン設定の部分で画像の透過部分が黒くなる。

![image](https://cloud.githubusercontent.com/assets/4032491/20452700/e1d7e896-ae53-11e6-9b17-b95e21064492.png)

**Comment by Implem** [comment]
Bug fixed: サイト画像の透明部分が黒く表示される問題を解消しました。
ご報告ありがとうございます。
https://github.com/Implem/Implem.Pleasanter/commit/1f6c5d387b276aad420a5120684532404efe2805
