### ISSUE TITLE
「リンクしたアイテムの作成」で開いた作成画面で読み込まれるスクリプトが、呼び出し元のエディタ画面スクリプトになってしまう

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#40]
お世話になっております。
以下の件について、ご確認をいただければ幸いです。

-----
[前提]
サイト1: リンク元、サイト2: リンク先、の関係
サイト種別は記録テーブル

[再現手順]
1. サイト2 のレコードを編集用で開く
2. 編集画面で、「リンクしたアイテムの作成」から[+ サイト1] ボタンで新規作成画面を開く
3. サイト1 の新規作成画面に、サイト2 のエディタ画面スクリプトが読み込まれている

[期待される動作]
サイト1 の新規作成画面には、サイト1 の新規画面スクリプトが読み込まれる

[発生環境]
Plesanter バージョン0.44.14.37259 (Azure上にデプロイ)
Chrome バージョン: 63.0.3239.132
IE11: バージョン: 11.0.9600.18894

**Comment by Implem** [comment]
ご報告ありがとうございます。バグのようなので、修正いたします。

**Comment by yyuki23** [comment]
ありがとうございます。よろしくお願い致します。
対応完了しましたらお知らせください。

**Comment by Implem** [comment]
リンク先レコード作成時にスタイル及びスクリプトが正しく動作しない問題を解消しました。
https://github.com/Implem/Implem.Pleasanter/commit/d0baf1e420e4dc407c658fd21ee8c99d28b7eb56
