### ISSUE TITLE
カラムを追加している場合のアップデート方法について

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#41]
お世話になっております。  

以前に、記録テーブルの「項目」の数を26個以上に増やしたい。という質問をさせていただいたかと思います。  
現在、「項目」を70個くらいに増やしているのですが、その際のシステムのアップデート方法について質問させてください。  

---
1. ソースコードをダウンロードします。
2. Implem.Pleasanter/App_Data/Definitions/definition_Column.xlsmを開きます。
3. 期限付きテーブル等のClassA～Zの下にClassA1～ClassAXXの行を作成します。
4. Excel上でマクロを有効化し、Shift + Ctrl + J と操作します。
5. マクロが実行され、データベースのレイアウトを更新します。
6. 上記のあと、追加した項目に関連するソースコードを自動生成します。
7. 生成されたソースコードをコンパイルしデプロイします。
---

上記が、以前に教えていただいた手順になります。
この手順で4番をいきなり実施するとexeファイルがないよというエラーが出てきます。
そこで、手順1の後にソースコードを一度コンパイルしてexeファイルを作成し、その後手順2以降を実施しようとしたのですが、
そうするとデータベースのレイアウトが「項目26個」の状態で一度更新されてしまい、項目27以降にあった中のデータが消えてしまいます。

この状態を解消したい（項目70個のままアップデートをしたい）と考えているのですが、
どのようにアップデートをすべきでしょうか？
申し訳ありませんが、手順をお教えいただけますと幸いです。
どうぞ、よろしくお願い致します。

**Comment by yang-jiayi** [comment]
yyuki23 さん
カスタマイズしたままでアップデートの正式な回答は内田さんの回答を待とうとして、
すでにカスタマイズした70カラムのテーブルを一度別テーブル名で、コピーし、通常のアップデートを行ってから、データを戻せばいいと思います。あくまで回避方法の一つです。

Yangjiayi

**Comment by yyuki23** [comment]
Yangjiayiさん
アドバイスありがとうございます。
確かに、他のテーブルとして一時保存しておけば回避は可能ですね。

Implemさん
他に正式なやり方がありましたらご教授いただけますと幸いです。

**Comment by Implem** [comment]
カラムの追加についてですが、ソースコードの更新をともなってしまいますので、基本的にはバージョンアップは不可となります。

どうしてもバージョンアップを行いたい場合には、最新版のソースで、同様にカラム追加の操作をしてからアップデートをかけるしかないのですが、こちらの手順を永続的にサポートする事はむずかしいと考えています。データの破損などの危険性がありますので、現時点でもあまりおすすめできません。

先日のアップデートで、説明項目も分類項目のフリー入力欄のように使うことができるようになりましたので、できるだけカラムを追加しない方向でお使いいただければ幸いです。

**Comment by yyuki23** [comment]
ご返信ありがとうございます。
まずは、説明項目がどのように変わっているか試してみたいと思います。
また追記します。

**Comment by yyuki23** [comment]
説明項目が分類項目のフリー入力欄のように使えることを確認しました。
欲を言えば、説明項目が分類項目の選択肢の形でも使えると嬉しいですが、
ひとまずissueとしてはcloseさせていただきます。
