### ISSUE TITLE
APIによるレコード更新時の通知について

### ISSUE THREAD

**Issue by Connie-Wild** [Implem/Implem.Pleasanter#42]
利用Ver 0.45.1.29417
APIによりレコードの作成、更新、削除を行った場合は通知の対象になっていないでしょうか。
可能であれば通知の対象に含めて頂けますと助かります。

**Comment by Implem** [comment]
通知の対象のフラグがオンになっていなかったので、オンに変更しました。
https://github.com/Implem/Implem.Pleasanter/commit/31f46ae3fccff5f12fb22ace72a0580ed48064af

**Comment by Connie-Wild** [comment]
ありがとうございました！
通知が有効になっている事を確認できました。

通知関連で、実装をお願いできたら嬉しい物がありまして
更新時は監視項目のみを通知してくれますが、新規作成時は全ての項目を通知するため、Slack等に出力すると項目数が多いとログが流れてしまい少々見辛い状況となってます。
新規作成も通知は監視項目のみに絞れるようにならないでしょうか。

**Comment by Implem** [comment]
どちらか選択出来るようなスイッチを追加するように出来ればと思います。可能であればプルリクエストいただけますと助かります。
