### ISSUE TITLE
APIによるレコード作成について

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#43]
お世話になっております。
いくつもissueをあげてしまい、申し訳ありません。

APIによるレコード作成時の既定値について質問です。
現在、request bodyに既定値を付与してcreateAPIを叩かないと、既定値がレコードに入らないかと思います。
bodyに付与せずとも、プリザンター側で既定値を自動で付与してレコードを作成することはできないでしょうか？

**Comment by Implem** [comment]
ありがとうございます。確かに既定値をいれたいですね。実装を検討します。

**Comment by yyuki23** [comment]
ご返信ありがとうございます。
もし実装が完了しましたら、本issueにご連絡いただけますと幸いです。

**Comment by Implem** [comment]
省略した場合に既定値がセットされるように修正しました。

https://github.com/Implem/Implem.Pleasanter/commit/4aeced36d1264abbe24a5ce22006144550607d2c

**Comment by yyuki23** [comment]
ご対応いただきありがとうございます！
遅くなりましたが、確認させていただきます！
