### ISSUE TITLE
レコード更新時のチェックボックスについて

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#44]
お世話になっております。

レコードを更新する際、更新ボタンを押した後にチェックボックス全てに勝手にチェックが入ってしまう現象が発生しております。
更新後にページをリロードすると元のチェックが入っていない状態に戻るのですが、連続で更新する際などにミスの元になるかと思います。
動作をご確認いただけますと幸いです。

どうぞよろしくお願い致します。

**Comment by Implem** [comment]
ご指摘ありがとうございます。
更新時のチェックボックスのレスポンスにバグがありましたので、プログラムを修正しました。
https://github.com/Implem/Implem.Pleasanter/commit/59eee7dabe71f01b53fc22a136939962a4a562a0

**Comment by yyuki23** [comment]
確認しました。
ご対応ありがとうございます。
