### ISSUE TITLE
インストール手順でインストールさせるべきなのは.NET SDKではなくASP.NET Coreランタイム

### ISSUE THREAD

**Issue by tats-u** [Implem/Implem.Pleasanter#446]
[CentOS 7へのインストール手順](https://pleasanter.org/manual/getting-started-pleasanter-centos)で、`dotnet-sdk-6.0`をインストールさせる手順がありますが、`aspnetcore-runtime-6.0`を代わりにインストールしても動きました。他のOSでも同様だと思います。
SDKには開発にしか使わない余計なファイルが数多く含まれているので、SDKではなくこちらのランタイムをインストールさせる手順にしてはいかがでしょうか。それとも、SDKでなければいけない理由はあるのでしょうか？

https://learn.microsoft.com/ja-jp/dotnet/core/install/linux-centos#install-the-runtime

**Comment by uchi-ta** [comment]
たしかにSDKである必要はありませんので、そのほうが良さそうです。マニュアルの修正を検討します。

**Comment by uchi-ta** [comment]
CentOS 7へのインストール手順を修正しました。他OSへのインストールについても見直し中です。

**Comment by tats-u** [comment]
@uchi-ta 確認しました。ご対応ありがとうございます。
