### ISSUE TITLE
一度テーブルの各項目の表示名を変更すると対応するアルファベットが二度とわからない

### ISSUE THREAD

**Issue by tats-u** [Implem/Implem.Pleasanter#450]
現在のバージョンでは、各項目に対応するアルファベット（説明A/DescriptionAのAなど）が初期（変更前）の表示名以外わからないようになっています。
後からAPIを叩きたいときや、一覧とエディタの表示名変更を同時に行わなかったときに、どのアルファベットがどの項目なのかを手探りで見つける羽目になります。
各項目の詳細設定ダイアログなどで表示することを解決策の1つとして提案します。

**Comment by uchi-ta** [comment]
貢献ありがとうございます。少々わかりにくいのですが、詳細ダイアログの左上の部分に分類Bなどが記載されます。
![image](https://user-images.githubusercontent.com/63937957/210504960-37a4d2e8-8d9a-45d7-b524-c35e99e03382.png)

また、項目の一覧をマウスオーバーすることで、分類Bなどがツールチップで表示されます。

**Comment by tats-u** [comment]
該当手順で表示できることを確認しました。余計なご対応をさせてしまい申し訳ありません。APIの利用ガイドでこの手順でアルファベットを確認することが書かれていると、利用者が助かります。

**Comment by uchi-ta** [comment]
とんでもございません。こちらこそ、ご指摘ありがとうございます。
