### ISSUE TITLE
テーブル管理の一覧・エディタタブの「選択肢一覧」で、目当ての種類の項目候補を探すのが大変

### ISSUE THREAD

**Issue by tats-u** [Implem/Implem.Pleasanter#451]
テーブル管理画面の「一覧」「エディタ」タブで、未追加の項目一覧である「選択肢一覧」のセレクトボックスで、たくさんある候補の中から追加したい項目（例：説明A）を探すのが大変です。
現状では、「分類」「数値」「日付」「説明」「チェック」×A～Z = 計130個 + 「作成者」など単一のもの10個ほど の候補が、縦1列に並んでおり、その中からお目当ての種類とアルファベットの項目を探し当てなければなりません。
「分類A～Z」「数値A～Z」などは、それぞれ1つの大分類に折りたたみができると目当ての項目を探し出すのが簡単になると思われます。

**Comment by uchi-ta** [comment]
貢献ありがとうございます。折り畳みや検索など探しやすくする工夫を検討いたします。

**Comment by tats-u** [comment]
not stale

**Comment by tats-u** [comment]
あげ

**Comment by tats-u** [comment]
保守

**Comment by tats-u** [comment]
保守

**Comment by pierre3** [comment]
お待たせいたしました。
バージョン1.4.1.0にてエディタの選択肢一覧のUI改善を行いました。
詳細は下記マニュアルにてご確認ください。
https://pleasanter.org/manual/table-management-editor-columns
