### ISSUE TITLE
jQuery-UIにおける脆弱性

### ISSUE THREAD

**Issue by nimani76** [Implem/Implem.Pleasanter#452]
Implem/Implem.Pleasanter/tree/main/Implem.Pleasanter/wwwroot/scripts/plugins/jquery-file-upload/js/vendor/
にて、[https://jvndb.jvn.jp/ja/contents/2021/JVNDB-2021-014043.html]などの脆弱性が報告されているjQuery UI - v1.12.1が使用されておりますので、できればこちらの対策についてご検討頂ければと思います。

**Comment by uchi-ta** [comment]
貢献ありがとうございます。こちら、該当ファイルを最新バージョンに置き換えました。
