### ISSUE TITLE
1.3.29.2 にバージョンアップしたら、Export がエラーになる。

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#455]
昨日、1.3.25.3　から1.3.29.2 にバージョンアップしたところ、データのExport がエラーになるようになってしまいました。
エラーメッセージはブラウザの画面に一行出力されます。

`不正なリクエストが送信されました。`

Export方式をメールにすると正常に出来るようです。

**Comment by uchi-ta** [comment]
貢献ありがとうございます。Security.jsonのTokenCheck: trueの環境で問題があり修正版 1.3.30.0 をリリースしました。
