### ISSUE TITLE
Firefoxでチェックボックス項目のラベルがずれて表示される

### ISSUE THREAD

**Issue by fr-sudachi** [Implem/Implem.Pleasanter#456]
Firefoxで、チェックボックス項目のラベルがずれて表示されます。

* Firefoxの場合
![image](https://user-images.githubusercontent.com/79742156/221771272-a6aaa8f9-9361-495b-b26d-c8f2986e30c5.png)

* Chromeの場合
![image](https://user-images.githubusercontent.com/79742156/221771386-3ba6b6cb-a3e5-4606-b729-53aeb1a511d0.png)

下に他の項目がある場合、ラベルが隠れてしまうことがあります。

![image](https://user-images.githubusercontent.com/79742156/221771662-4cef43d0-5835-43cc-b893-eef41c62985b.png)

**Comment by uchi-ta** [comment]
貢献ありがとうございます。バージョン 1.3.36.0 で表示がずれる問題を修正しました。
