### ISSUE TITLE
APIからユーザ情報を取得すると、各ハッシュ情報が取得できない

### ISSUE THREAD

**Issue by shoheichikura** [Implem/Implem.Pleasanter#457]
https://pleasanter.org/manual/api-user
によれば、ユーザ情報にはクラスハッシュ、数値ハッシュ、説明ハッシュ、チェックハッシュ、添付ハッシュの情報が含まれるとのことですが、
https://pleasanter.org/manual/api-user-get
に従い、ユーザ情報を取得すると、当該データが取得できないようです。（各ハッシュは空で返ってきます。）

データベース上には
https://pleasanter.org/manual/authentication-json
を参考にLdapExtendedAttributesで取得した情報が格納されている事は確認しております。

修正頂けると幸いです。

**Comment by nagamune-implem** [comment]
貢献ありがとうございます。マニュアルが親切でなく申し訳ございません。

- APIからユーザ情報を取得する際の出力に特定カラムを含めたい場合は、[拡張機能：拡張項目](https://pleasanter.org/manual/extended-column)にて、該当カラムを追記していただきますようお願いいたします。その際に「GridEnabled」「EditorEnabled」パラメータの一つもしくは両方に"1"を指定してください。

あわせてマニュアルも修正いたしました。
