### ISSUE TITLE
Group管理、作成の抑止が出来ない。

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#459]
以前は制限されていたはず？のトップフォルダに、フォルダやテーブル作れますよとユーザに言われて動作確認したところ、
user.json で抑止出来ることが分かりこれはドキュメント通り抑止することができました。

ついでにグループの作成も抑止しようと、user.json の設定を変更し IISを再起動していますが、ユーザ管理のページにマニュアルに記載されている「グループの管理を許可」、「グループの作成を許可」のチェックボックスが現れません。
また、その状態で一般ユーザでグループの作成が出来てしまいます。

よろしくお願いします。

Server: Windows2019, MS-SQL2019
Pleasanter Ver.1.3.34.0

user.json
```
{
    "DisableTopSiteCreation": true,
    "DisableGroupAdmin": true,
    "DisableGroupCreation": true,
    "DisableApi": false,
    "SelectorToolTip": "LoginId",
    "Theme": "sunny"
}
```

![user](https://user-images.githubusercontent.com/17542768/227175053-d6760c7f-28ff-40b9-950e-7e63546e7c71.PNG)
![user json](https://user-images.githubusercontent.com/17542768/227175082-c1326d23-c3ca-4add-8584-b2b34b80bdb4.PNG)

**Comment by uchi-ta** [comment]
貢献ありがとうございます。こちらでは現象を再現することができませんでした。以下をご確認ください。

・正しい設定ファイルを編集しているか（動作しているものと違うディレクトリ）
・再起動が正しくおこなわれているか（再起動が行われるとSysLogsテーブルのMethod列にApplication_Startと記録されます）
・他の環境に新規に環境を立てた場合でも再現するか

追加の再現手順などがあれば、ご教示ください。

**Comment by nozoe** [comment]
結果的としては、再起動が正しく行われていなかった様です。
先ほど数日ぶりにログインして確認したところ、チェックボックスが表示されている事確認できました。
(Topフォルダの制限と同じ手順で変更、再起動を実施していたのですが…)
お手数をおかけいたしました。

![image](https://user-images.githubusercontent.com/17542768/228113649-a82039f3-49d1-42d8-bbdf-5f50a5f15104.png)
