### ISSUE TITLE
作成したAPIキーの有効期限について

### ISSUE THREAD

**Issue by Connie-Wild** [Implem/Implem.Pleasanter#46]
すみません教えて下さい。
APIキーの作成後、作成したキーを利用してレコードの操作を確認した後、全くアクセスしない状況で1,2日経過すると`{ Id: 0, StatusCode: 400, Message: 'Request is invalid.' }`が返ってくる状況となっています。

作成したAPIキーには有効期限があるのでしょうか。
または、アクセスが発生してないのでセッションタイムアウトと同時にAPIキーも無効化されるのでしょうか。

**Comment by Implem** [comment]
APIキーは特に有効期限などの制限をかけていないのです。UsersテーブルのApiKeyに入っているものと照合するロジックです。認証部分ではないような気がするのですが、もう少し切り分けてもらえると助かります。

https://github.com/Implem/Implem.Pleasanter/blob/master/Implem.Pleasanter/Filters/CheckApiAuthentication.cs

**Comment by Connie-Wild** [comment]
詳細ありがとうございます。調べてみます。

**Comment by kudarisenmon** [comment]
同じ現象に遭遇しました。

1. しばらくアクセスせずに放置する
2. APIからアクセスすると Request is invalid が返る
3. Webブラウザからログイン
4. APIからアクセスしても問題ない

手順１はWebブラウザからもAPIからもアクセスしない期間が2日間です。
手順２は何度やっても同じ結果になります。
手順３はAPIで使っているユーザと異なるユーザでも同じユーザでも結果は同じです。
手順４は何度実行しても同じです。
このあと2日間放置するのはまだ試してません。
もちろん途中でAPIキーは変更していません。

**Comment by Implem** [comment]
2日というと、Web.configのセッションタイムアウトの既定値でした。そのあたりを踏まえて調査してみます。

Web.config
<sessionState timeout="2880"/>

**Comment by Implem** [comment]
上記のAPIは読取り（/get）でしょうか？ また、ブラウザからのアクセスでしょうか。もし、そうだとするとApiKeyではなく、ログインしたセッションでアクセスしていて、ApiKeyを読むほうにいっていないかもしれません。ApiKeyのjsonが正しくサーバに届いていないとこのような状況になる可能性はあります。

下記のコードで説明すると
https://github.com/Implem/Implem.Pleasanter/blob/master/Implem.Pleasanter/Filters/CheckApiAuthentication.cs

LINE 15  ApiKeyを含んだjsonがデシリアライズできたかチェック
LINE 40  ログイン中のセッションかチェック（ApiKeyが無くても操作を許可）

という動きになっています。そのため、まずLINE 15が通っていないのではないかと考えています。LINE 15が通っていなくても、/getは可能です。ただ、/createや/updateはjsonが正しくデシリアライズできないと動作できないため、そのあたりをご確認いただければ幸いです。

的外れな内容でしたらすいません。

**Comment by kudarisenmon** [comment]
情報が足りませんでした。手順２と手順４で使っているAPIは /get のみです。
以下の例のようにLinuxシェルからcurl を使っています。

$ curl 'http://hogesvr.local/pleasanter/api_items/5963/get' -d '{"ApiKey": "9ace45a25d9012fe33ff0fee41b763fc065b0fd4d22b14b6a8a0c2f285714a0ef3131232afacd50a45f31e3b36d1628ec071bc8fg179b6a44eb3f6ccd668e28c", "Offset": 0}'

次回発生時は /createや/update も調べられるように準備してみます。

**Comment by pierre3** [comment]
私も同様の現象に遭遇しました。

Masterブランチ(Version 0.45.8.39113)をビルドしてAzure App Service（Free plan)にデプロイしています。
- この環境では、アクセスしていない期間が1時間程度で問題が発生します。
- やはり、Webブラウザでログインすると正常に動作します。
- 使用したAPIはGETです。

デバッグの結果、以下の様に動作していることが分かりました。
- CheckApiAuthentication.csの29行目でContract.Api()がFalseを返しています。
- Api()の中では、ContractHashが空となっていてContractHash.ContainsKey(tenantId)がFalseを返します。
- ログイン後はContractHashにはtenantId(=1)で値が入っていてContract.Api()はTrueを返します。

**Comment by Implem** [comment]
Contract.Api()のチェックでstatic変数をチェックしていたため、アプリケーションのリサイクル後に使用できなくなっていました。こちらContract.Api()の前にstatic変数を復元する処理を行う仕様に変更しました。皆様、調査ご協力ありがとうございます。

https://github.com/Implem/Implem.Pleasanter/commit/1c48c4ad7dc247aa6d669b18d101bb94e991a243
