### ISSUE TITLE
[1.3.35.1][更新時のアクセス制御]にて[管理者／担当者]の[権限設定]後、更新ボタンを押下するだけで「この操作を行うための権限がありません」が発生

### ISSUE THREAD

**Issue by tatsuyasenbom** [Implem/Implem.Pleasanter#460]
# 環境
* Pleasanter 1.3.35.1 x Windows Server 2016 x SQL Server 2017

# 現象
1. `項目のアクセス制御` ＞ `更新時のアクセス制御` ＞ `管理者`／`担当者` ＞ [詳細設定]
    * ![image](https://user-images.githubusercontent.com/87968771/229417804-f0cdb958-83f9-4231-bc06-9a7ca0ee5750.png)
2. `権限設定`に任意`組織`を指定
    * ![image](https://user-images.githubusercontent.com/87968771/229418133-bc9d2de6-0e81-4009-8c2d-2fb618eca22a.png)
3. 上記2の`組織`に属さない`ユーザ`でログインし直し当該サイトの任意レコードにて、レコードの各項目は編集せず（`管理者`／`担当者`以外の項目を編集したとしても同じ）に、`更新`ボタンを押下
    * ![image](https://user-images.githubusercontent.com/87968771/229418660-1dd5b50e-a33b-4c1f-9d7b-55ef1e2cd8e0.png)
4. 上記3の`ユーザ`を、上記2の`組織`に所属させると、上記3の症状は発生しない。

**Comment by uchi-ta** [comment]
貢献ありがとうございます。こちらは、以下の条件で発生する不具合がございました。

・対象の項目の更新時のアクセス制御により項目の更新権限が無いユーザでレコードを更新
・対象の項目に既定値がある
・対象の項目が編集画面で有効化されていない

1.3.38.0 にて修正されていますので、バージョンアップの上、ご確認ください。

**Comment by tatsuyasenbom** [comment]
ご確認&共有ありがとうございます！動作が改善した事を確認しました！

**Comment by uchi-ta** [comment]
確認ありがとうございます。1.3.38.0 ですが、作成時に既定値が保存できない問題が発見されました。ご面倒おかけしますが、1.3.38.1 へのアップデートをお願いします。

**Comment by tatsuyasenbom** [comment]
> 確認ありがとうございます。1.3.38.0 ですが、作成時に既定値が保存できない問題が発見されました。ご面倒おかけしますが、1.3.38.1 へのアップデートをお願いします。

ご丁寧にありがとうございます。承知いたしました。
