### ISSUE TITLE
SAML連携の設定を入れるとloginページを表示する時に異常終了する。

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#463]
テスト環境を構築し、SAML連携の設定を入れてテストをしているのですが、中々うまくいきません。

DB内のsyslog を見るとinternal server error で異常終了している様です。

一応、設定ファイルAuthentication.json は何度も見直しているのですが、何等かの設定が足りないために
落ちているのかイマイチ落ちる原因が分かりません。(必要なところは記述したつもりです)
一応、ソースコードを読もうとはしているのですが、SAML連携に詳しくないので難解です。
よろしくお願いします。

環境としては、
  Windows2022 Server
  MS-SQL2022
  Pleasanter-1.3.36.0

Authentication.jsonとsyslog の該当レコードを添付します。
[SAML連携エラー.txt](https://github.com/Implem/Implem.Pleasanter/files/11350629/SAML.txt)
[Authentication.json.txt](https://github.com/Implem/Implem.Pleasanter/files/11350650/Authentication.json.txt)

**Comment by yohshiro-711** [comment]
idpの証明書が証明書ストアから取得できていないようです。
Authentication.jsonを確認したところ、
SamlParameters.IdentityProviders.SigningCertificate.StoreLocationの指定が"CurrentUser"になっていますが
環境がWindows2022 ServerになっているのでIISだと証明書がヒットしないと思われます。

StoreLocationを"LocalMachine"にし、idpの証明書をインストールする際の保存場所をローカルコンピュータにしてみてはいかがでしょうか？

**Comment by nozoe** [comment]
返信ありがとうございます。

StoreLoacation をLocalMachine に変更してみましたが、状況に変化はない様です。

前回までの環境では、連携証明書のインポートが漏れていることに気付き
(確認する証明書を勘違いしていました)
連携証明書をローカルマシンの環境にインポート(ローカルマシン、自動配置)し、
その証明書のハッシュ値に書き直してIIS再起動してみましたが状況に変化は見られ
ません。

ハッシュ値で検索すると証明書がヒットする事は確認しました。
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/f4915d8e-ce1a-4d9e-8538-3e656b5d026d)
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/6b41aa10-6f1e-4ba5-9187-7e5cf793205c)

**Comment by yohshiro-711** [comment]
Authentication.jsonのStoreNameにMy(個人ストア)が指定されていますが、
証明書が中間証明機関ストアにインストールされているためヒットしていないと思われます。
証明書を自動配置せず、個人ストアにインストールしてみてはいかがでしょうか。

**Comment by nozoe** [comment]
ありがとうございます。
個人ストアに再インストールしたら、ログイン画面表示されました。
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/21dd8fec-6b13-48ec-98a3-0fc3ac4776a9)
[SSOログイン]クリックで、ここまできました。
(IDP側の設定見直し等々)
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/8eb0de23-b7a3-4d23-b966-264d864d9092)
この時のWebServerのログがこんな感じです。
`xxx.xxx.xx.xxx - - [10/May/2023:13:55:04 +0900] "GET /pleasanter/ HTTP/2" 302 0

xxx.xxx.xx.xxx - - [10/May/2023:13:55:04 +0900] "GET /pleasanter/users/login?ReturnUrl=%2Fpleasanter%2F HTTP/2" 200 3219

xxx.xxx.xx.xxx - - [10/May/2023:13:55:08 +0900] "GET /pleasanter/users/challenge?ReturnUrl=%2fpleasanter%2f HTTP/2" 200 1314

xxx.xxx.xx.xxx - - [10/May/2023:13:55:08 +0900] "POST /pleasanter/Saml2/Acs HTTP/2" 500 5487
`
この時のsyslog に記録されたエラーの内容です。
[Syslog.txt](https://github.com/Implem/Implem.Pleasanter/files/11438191/Syslog.txt)
受け渡しのパラメータかとおもいましたが、それはここを通過した後の様です。

**Comment by nozoe** [comment]
自己解決しました。
想定、IDP側の担当者から聞いていた**EntityId**とは異なるURLがAcsのパラメータに乗って返ってきて来ている事が原因でした。
Syslog に記録されていたURLに書き換えたところ、無事にログイン出来ました。

これで多分大丈夫だと思います。
もうちょっと動作確認してみますが、色々ありがとうございました。

**Comment by nozoe** [comment]
すみません、関連で一つ確認したいことがありました。
Pleasanter のログイン画面をSSOログインボタンだけにすることは、簡単にできますか？
基本は、認証ポータルを通ったユーザにしか使えない環境を構築したいのです。

**Comment by nozoe** [comment]
後、幾つか確認ですが

1. SAML連携するとメールアドレスを書き換えてしまいますが、これを抑止することはできませんか？
      ひょっとしてこのパラメータの定義を消せば良いのでしょうか？
3. 抑止出来ない場合、現状のAuthentication.json のSamlParamater 内のMailAddress のところの記述が
          `"MailAddress": "{NameId}"`
　となっていたのでここを、IDPから送られてくる属性を確認して
    (これに結構苦労しました。アプリケーション毎に新しいタブを生成するので、F12を押すタイミングが。。。。)
          `MailAddress": "{Email}`
    にしたら、全く登録処理がなされない状況でした。
　他の変数は、{}で括られてないのに？と思い{} を外して単に"Email"としたら上手くいきました。
          `"MailAddress": "Email"`   
　この辺の違いがいまいちわかりません。
