### ISSUE TITLE
レスポンシブ表示での画面下にでる"お知らせ"の表示位置

### ISSUE THREAD

**Issue by ebessan** [Implem/Implem.Pleasanter#469]
作成や更新ボタンを押したときに画面下部にでる緑色のバナー？お知らせ表示がもともとある下部に配置されているボタンと被って表示されてしまいます。レスポンシブをオフにしていると重ならないんですが、私だけでしょうか？

iphone12 16.4.1(a)
pleasanter 1.3.31.0
centos 7.9.2009
postgres14.5

**Comment by pierre3** [comment]
Issueありがとうございます。
確認いたしますのでお待ちいただけますでしょうか

**Comment by nagamune-implem** [comment]
下記のリリースにて対応いたしました。
バージョン：Pleasanter_1.3.44.0
最新版でご確認頂きたく、よろしくお願いいたします。
