### ISSUE TITLE
バージョンアップ後に項目アクセス制御できない

### ISSUE THREAD

**Issue by takaoyama** [Implem/Implem.Pleasanter#47]
お世話になっております。

バージョン0.45.19.33326へアップしたところ
以下の事象が発生しました。

・項目アクセス制御の詳細設定ボタンを押すと
　アプリケーションエラー発生のメッセージが出ます。

・アクセス制御をしている項目が
　新規作成時に表示されなくなりました。

前バージョン（0.45.4.42346）へ戻すと
事象は解消されました。

ご確認よろしくお願いいたします。

**Comment by Implem** [comment]
項目単位のアクセス制御が設定できない問題を解消しました。
https://github.com/Implem/Implem.Pleasanter/commit/c04525dcf210528a5e2ca306afc9858cc54c3ff9

**Comment by Implem** [comment]
読み取り専用の項目が新規作成画面に表示できなくなっていたので修正しました。

https://github.com/Implem/Implem.Pleasanter/commit/51b60e7c0ac66f075b4fbd8f16d3409274a6bdcc

**Comment by takaoyama** [comment]
ありがとうございました。
事象は解消いたしました。
