### ISSUE TITLE
一覧画面の編集モードで新規行のLookup項目が反映されない

### ISSUE THREAD

**Issue by makotookamura** [Implem/Implem.Pleasanter#470]
一覧画面の編集モードで新規作成または既存行のコピーをしてリンク項目を選択すると、Lookup機能がうまく動かず、値が反映されません。
また、更新ボタンを押した後に再度リンク項目を変更した場合、別の選択項目を選択するとLookupが動きましたが、元の選択項目に戻すと値が反映されませんでした。

現状では、正しい指定をするためには以下の操作が必要です。
1. 行を新規作成する
2. リンク項目に選択したい値以外の値を設定する
3. 一度更新する
4. リンク項目を選択したい値に変更する

**Comment by pierre3** [comment]
Issueありがとうございます
確認いたしますのでお待ちいただけますでしょうか

**Comment by pierre3** [comment]
上記現象が再現することを確認いたしました。
修正方法について検討いたします。
