### ISSUE TITLE
AD同期最中のログイン操作

### ISSUE THREAD

**Issue by sts00455** [Implem/Implem.Pleasanter#471]
pleasanterのAD同期の最中にpleasanterへのログイン操作を行うとそのユーザが無効化されます。AutoDisableはtrueのままこれを防ぐ方法を教えてください。

**Comment by pierre3** [comment]
Issueありがとうございます。
確認いたしますのでお待ちいただけますでしょうか

**Comment by sts00455** [comment]
ありがとうございます。
お待ち申し上げております。
ぜひよろしくおねがいいたしますｍｍ

**Comment by pierre3** [comment]
こちら、弊社の環境で再現を試みましたが、再現できませんでした。

本事象について、下記の認識で相違ありませんでしょうか。
1. Authentication.json で　"AutoDisable": true　を設定
2. syncbyldapによりADを同期処理を開始
3. 同期処理中にユーザA（AD/Pleasanter共に有効なユーザ) でログイン
4. ユーザAがPleasanter側で無効化されてしまう。

また、AutoDisable以外の条件などありましたら共有ください。
よろしくお願いいたします。

**Comment by sts00455** [comment]
ご認識に相違ありません。
関係するか分かりませんが投稿当時、以下の環境下にて発生していた事象です。
　・同期ユーザ数が多く、AD同期処理開始から終了まで30分ほどかかる。
　・OS:windowsServer 2016
　・DB:SQL Server 2017 Standard Express
　・Pleasanter Ver 0.50.236　※

　　※現在は、サーバ環境はそのまま
　　　Pleasanterは Ver 1.3.29.1へバージョンアップ済み。
　　　バージョンアップ後の同事象の再発はないが、再現テストをしていないので
　　　たまたまなのか、バージョンアップにて解消したかは不明。

**Comment by pierre3** [comment]
情報ありがとうございます。
Pleasanter Ver 0.50.236（.NetFramework版）での現象との事承知いたしました。
現在のバージョンで同様の現象が再現いたしましたらご連絡いただけますでしょうか。
