### ISSUE TITLE
レコードを直接開いた場合、別タブ(変更履歴等)をクリックすると、「要求が不正です」とポップアップが表示される

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#475]
Pleasanter のレコードを直接開くURL(例えば、https:/xxxxx.xxxx.xxx/pleasanter/items/259850)をクリックし、「**全般**」タブを開いている状態で別の「**変更履歴**」タブや「**レコードのアクセス制御**」タブをクリックすると、”**要求が不正です**”というメッセージがポップアップで表示される。
一度**F5キー**等でリロードすると正常動作するようになる。

![Pleasanter20230602_2](https://github.com/Implem/Implem.Pleasanter/assets/17542768/5a4ca197-d844-4496-ae2a-e48de1c9d5a4)

環境
　　Server: Windows 2019 Server + MS-SQL2019 
　　Pleasanter 1.3.38.2
　　クライアント側: Windows10+ Edge

**Comment by pierre3** [comment]
Issueありがとうございます。
本現象ですが、手元の環境では再現することができておりません。

原因究明のために、下記をご確認いただけますでしょうか
- ブラウザの開発者モードを開いた状態で（F12キー押下）現象を再現し、コンソール画面にエラーログが表示されていないか。

どうぞよろしくお願いいたします。

**Comment by nozoe** [comment]
1.3.41.0で試しましたが、正常に動作するようになってますね。
更に、検証環境に1.3.38.2の環境を再構築して試しましたが再現しませんでした。

この事象を投稿した際には複数の端末で再現することを確認したのですが。。。

環境的にはPCも変わってしまったので、今となっては何がわるかったのかわかりません。。。

**Comment by pierre3** [comment]
ご確認ありがとうございます。
現象が再現いたしましたらご連絡をお願いいたします。
