### ISSUE TITLE
Lookupと項目連携が連動しない

### ISSUE THREAD

**Issue by ebessan** [Implem/Implem.Pleasanter#477]
ClassAでLookupでClassBとClassCに転記します。
ClassBとClassCを項目連携しておきます。

ClassAを選択してLookupを動かすと、ClassCが連携した選択肢になりません。

ClassBを選択しなおすとClassCは連携した選択肢になります。

**Comment by pierre3** [comment]
Issueありがとうございます。
本動作について確認いたしますのでお待ちいただけますでしょうか。

**Comment by pierre3** [comment]
本動作について、手元の環境で再現することを確認いたしました。
項目連携が設定されている項目では、Lookupの転記が動作しないようです。

対処方法ですが、下記の設定をお試しいただけますでしょうか。

下記の様にLookup設定で OverwriteformをtrueとすることでLookupの転記を強制することができます。

```json
[{
  "SiteId":12345,
  "Lookups":[
    {
      "From":"ClassA",
      "To":"ClassB",
      "Type": 0,
      "OverwriteForm":true
    },
    {
      "From":"ClassB",
      "To":"ClassC",
      "Type": 0,
      "OverwriteForm":true
    }
  ]
}]
```
