### ISSUE TITLE
記録テーブルの内容にイメージを添付したテーブルをデータ付きで正しくエクスポートしたい。

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#478]
記録テーブルの一番シンプルなパターンでテーブルを作成し、
その内容にイメージを貼り付けたレコードを作成した場合、エクスポートしたデータを別環境でインポートした場合
正常に動作しない。
そもそも、データを含めるにしても、貼り付けた画像データがjson ファイルに含まれない。(添付ファイルはデータベースに保存)

例えば、pleasanter のアクセスパスを　https://FQDN/pleasanter/ とした場合、export したjson ファイル中にパスが含まれてしまい
異なる環境に持っていった場合正常に動作しないのでは？

`   "ItemTitle": 
          },
          "Body": "![image](/pleasanter/binaries/09dd7e2973d44cb5924fdcdb09015f0d/show)\n![image](**/pleasanter/binaries/68dc4872ab0b45d99518716ed2214368/show)![image](/pleasanter**/binaries/bb35b6199c084adb9020566db28fa329/show)",
          "Status": {
            "Value": 100
          },
`

それとこのjsonファイルの中にイメージデータが吐かれないとと結局export して持っていっても使えないです。

テーブル単位、フォルダ単位でエクスポートしたデータが移行先で正常にインポートして利用出来る様にしてほしい。

**Comment by pierre3** [comment]
Issueありがとうございます。

画像や添付データが移行できない問題につきまして、課題として認識しております。
解決する方法について、検討いたします。
