### ISSUE TITLE
情報共有 application起動速度の改善

### ISSUE THREAD

**Issue by Connie-Wild** [Implem/Implem.Pleasanter#48]
Win Server 2012 R2/IIS 8.5のデフォルトの設定では、一定時間アイドル状態（アクセスのない状態）になったワーカープロセスは、タイムアウトされプロセスが停止しています。
これにより、頻繁にアクセスのないWebサイトに関してはメモリの消費を抑えられるというメリットがあります。
しかし、その分、タイムアウトされた後に来た最初のリクエストに関してはワーカープロセスを起動し直す分、応答に時間がかかっています。

IISマネージャーの［アプリケーション プール］を開き、設定したいアプリケーションプールの［詳細設定］を開くき、プロセスモデルの［アイドル タイムアウトの操作］を「Terminated」から「Suspend」に変更する事で、ワーカープロセスを停止する代わりに、ディスク上からページアウトする動作に変更になります。
これによりメモリの消費を減らしつつ、ページアウト状態からの復帰にかかる時間を短縮する事ができます。

![06](https://user-images.githubusercontent.com/34596022/35599547-8ab6ef90-066c-11e8-910f-a9449b609b97.png)
https://www.buildinsider.net/web/iis8/06

**Comment by Implem** [comment]
この設定いいですね！サーバつくる際に参考にします。
