### ISSUE TITLE
検索機能のあるフィルタの、有効化した項目の全無効化

### ISSUE THREAD

**Issue by TakutoOsugi** [Implem/Implem.Pleasanter#485]
検索時の複数フィルタを解除する際、一つずつ解除するしかない状態なので、まとめて解除できるようにしたい

**Comment by nozoe** [comment]
このボタンで出来ませんか？
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/72609c60-6fd9-449e-b41e-5d70f70b36f9)

**Comment by TakutoOsugi** [comment]
![image](https://github.com/Implem/Implem.Pleasanter/assets/131846367/e323c487-ceca-4907-82a4-f1edeeaa0482)
申し訳ありません、私の理解不足かつ、書き方が大変悪かったです。
「検索機能を使う」項目をフィルタとして使う際、そのフィルタだけ無効化したい場合、ひとつずつ無効化していくしかないため、これをまとめて解除するボタンを設置するなどしたい、というものです

**Comment by nozoe** [comment]
連続した並びなら一つクリックしそのまま、マウスを下に動かせば複数選択状態になる様に見えますよ。
飛び飛びの場合は、コントロール押しながらクリックで。

**Comment by TakutoOsugi** [comment]
承知いたしました。
それでは、こちらはクローズさせていただきます。
