### ISSUE TITLE
レコードの削除をするとレコードのアクセス制御が変わる？

### ISSUE THREAD

**Issue by ebessan** [Implem/Implem.Pleasanter#486]
レコードの削除を押すと、当該レコードは削除されるが他のアクセス制御で権限のないはずのレコードのアクセス制御が削除したユーザになってしまいます。しかも権限を変更しようとしても「レコードのアクセス制御」タブの「権限削除」、「権限追加」ボタンがグレーになっており、ボタンが押せなくなってしまいました。

chromeのデベロッパーツールを見てもとくにエラーは出てないと思うのですが、なんでしょうか？？？

バージョン：1.3.45.0
os：centos7
DB：postgres14
ブラウザ：google chrome

**Comment by ebessan** [comment]
レコードのアクセス制御の設定で「作成時の制御」欄には「担当者」、「更新時の制御」欄には「ユーザ」と設定していましたが、「更新時の制御」欄を削除して空欄にしたところ、「権限削除」、「権限追加」ボタンが押せるようになり思惑通りのアクセス制御の動きがするようになりました。

ただ、他の「担当者」（本来はアクセス権限のないはずのユーザ）が自分のレコードを更新したときに本来のアクセス権限のないレコードのアクセス権限まで変更になったのは、同一パソコンでログイン、ログアウトでユーザを切り替えて捜査していたのでブラウザ（chrome）のキャッシュの問題だったのか、よくわかりませんでした。。。

ひとまず動くようになりました。。。

**Comment by pierre3** [comment]
Issueありがとうございます。
同様の現象が再度発生いたしましたら、発生条件・手順など詳細な情報を記載のうえ、ご連絡いただけますでしょうか。

**Comment by ebessan** [comment]
現状の設定状況をお知らせします。

親テーブル：siteID : 1
子テーブル：siteID : 2

としたときに子テーブルの分類Aに

[
    {
        "SiteId": 1,
        "LinkActions": [
            {
                "Type": "DeleteWithLinks"
            }
        ]
    }
]

を設定

「親テーブル操作」
レコードのアクセス権限で「ユーザ」（書き込みからメール送信を無し）を設定
いくつかレコードを複数のユーザで作成
子テーブルを親テーブルの編集画面のリンクボタンから作成
作成したレコードをロックしたものとロックしていない物を作成

「子テーブル操作」
レコードのアクセス権限で「入力者」（書き込みメール送信を無し）を設定

親テーブルでどれかのレコードを編集画面から削除すると、アクセス権限のないレコードまで更新されます。
※ただし、よくわかりませんが、更新されないレコードもあります。
レコードの違いは
ロックの有無　→　こちらの環境では　ロック有で更新されます。
状況が900以上、未満　→　こちらの環境では　900以上で更新されます。

一覧画面からチェックで一括削除だと該当レコードのみ削除、更新されます。

**Comment by ebessan** [comment]
現状、子テーブルの分類Aの

[
{
"SiteId": 1,
"LinkActions": [
{
"Type": "DeleteWithLinks"
}
]
}
]

を

[[1]]

のみにして"LinkActions"を無しにすると問題は解消されました。

**Comment by pierre3** [comment]
返答が遅くなり申し訳ございません。
ご連絡いただいた設定でこちらでも試してみましたが、現象を再現できておりません。

よろしければ、問題のサイトのサイトパッケージを添付いただけますでしょうか。
可能であれば関連するサイトを含むフォルダ単位でエクスポートをお願いいたします。

※また、個人情報や業務情報などが含まれる場合は、削除やマスクしたうえでご提供ください。
