### ISSUE TITLE
サーバスクリプトの発火タイミング

### ISSUE THREAD

**Issue by ebessan** [Implem/Implem.Pleasanter#487]
Pleasanter_1.3.44.0からPleasanter_1.3.45.0にアップデートしたところ、サーバスクリプトの「作成前」、「作成後」のチェックで動いていたスクリプトが動かなくなりました。発火タイミングに「計算式の前」と「計算式の後」にチェックを入れると動きます。

動作タイミングの設定の仕方が変更になったのでしょうか？？？

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

こちらで確認してみたのですが、再現が出来ませんでした。
何か条件等が不足している場合はご教授いただけますと幸いです。

●調べたこと
◎目的
・サーバスクリプトの発火タイミングの確認
　→ バージョン毎に差異があるか？

◎サーバスクリプトの設定。
・条件
![image](https://github.com/Implem/Implem.Pleasanter/assets/84897126/c1153cc9-ee4d-4a33-ba98-7def48df5d44)
・スクリプトの内容
-- 作成前
context.Log("create befoer");
-- 作成後
context.Log("create after");
-- 計算式の前
context.Log("calc befoer");
-- 計算式の後
context.Log("calc after");

◎結果
・「Pleasanter_1.3.44.0」と「Pleasanter_1.3.45.0」で同じものが出力された。
※）デバッグコンソールに出力結果
〇Pleasanter_1.3.44.0
・画面上部の「＋新規作成」リンク押下後
calc befoer
calc after
・編集画面株の「作成」ボタン押下時
calc befoer
calc after
create befoer
create after

〇Pleasanter_1.3.45.0
・画面上部の「＋新規作成」リンク押下後
calc befoer
calc after
・編集画面株の「作成」ボタン押下時
calc befoer
calc after
create befoer
create after


◎確認した動作環境
・Windows11
・SQLServer16.0.105

**Comment by ebessan** [comment]
ご対応ありがとうございます。

こんな状況です。
（パターン１動きます）
![2](https://github.com/Implem/Implem.Pleasanter/assets/90179776/b41250e5-713d-4c50-8748-644fcfe20339)
![1](https://github.com/Implem/Implem.Pleasanter/assets/90179776/4555d047-74e6-4d2f-b18c-3e3d0787fb9e)
![2](https://github.com/Implem/Implem.Pleasanter/assets/90179776/0a58f340-595b-480f-ae66-e494b45ae2ce)
![3](https://github.com/Implem/Implem.Pleasanter/assets/90179776/93ceeb72-dfad-45a8-9571-ce1c0ed8b74b)

（パターン２動きません）
![5](https://github.com/Implem/Implem.Pleasanter/assets/90179776/e3f718dc-af4b-4b21-b991-f417f609a723)
![4](https://github.com/Implem/Implem.Pleasanter/assets/90179776/4c804ae9-0b8a-43ed-a525-1c30afcea4e6)
![6](https://github.com/Implem/Implem.Pleasanter/assets/90179776/bf4c8a07-2db4-4662-8d60-9db0017e11ed)
![7](https://github.com/Implem/Implem.Pleasanter/assets/90179776/2a5030a6-d515-4db8-8439-aa7ddf0ddbc9)

1.3.44.0では問題なく動いていたのですが、アップデートしたところ動かなくなったのでちょっと変更しました。（もともとはコメントアウトしている部分のみでした）

◎確認した動作環境
・Windows11
・postgres14

**Comment by nagamune-implem** [comment]
コメントありがとうございます。

先の私の[コメント](https://github.com/Implem/Implem.Pleasanter/issues/487#issuecomment-1698662006)が伝わりずらい書き方で申し訳ございません。


> 動作タイミングの設定の仕方が変更になったのでしょうか？？？

上記に関してですが、
**「Pleasanter_1.3.44.0」と「Pleasanter_1.3.45.0」の間で**
**サーバスクリプトの**条件「作成前」「作成後」「計算式の前」「計算式の後」の
**発火タイミングに仕様変更はありません**。
また実際の動作を確認しましたが、該当バージョン間の差異は見つかりませんでした。


サーバスクリプトの発火タイミングは下記となり、両バージョンとも同じタイミングで発火している事は確認いたしました。
| No | 条件 | 説明 |
----|---- |---- 
| 4 | 計算式の前 | 計算式の実行前に項目の内容を変更する際に使用します。 |
| 5 | 計算式の後 | 計算式の実行後に項目の内容を変更する際に使用します。 |
| 6 | 作成前 | 「レコード」が作成される前に実行します。 |
| 7 | 作成後 | 「レコード」が作成された後に実行します。 |

※）[マニュアル](https://www.pleasanter.org/manual/server-script-conditions) 「開発者向け機能：サーバスクリプト：条件」より
https://www.pleasanter.org/manual/server-script-conditions


---

08/30に頂いた[コメント](https://github.com/Implem/Implem.Pleasanter/issues/487#issuecomment-1698816802)はすべて「Pleasanter_1.3.45.0」での画面キャプチャとの認識でよろしいでしょうか？
「Pleasanter_1.3.44.0」との比較で無いと問題点の洗い出し(他の要因で発生しているかなど)が難しいと考えております。
とは言え、「Pleasanter_1.3.44.0」の環境に戻すと言うのは難しいと思われますし、現状は対策済みで運用は出来ているとの認識ですので、いったん調査報告結果としてご認識頂ければと思います。

こちらでも再現可能な手順や条件が分かりましたらご連絡頂ければうれしく思います。
