### ISSUE TITLE
Chromeでダッシュボード機能が利用できない

### ISSUE THREAD

**Issue by tsuyoshi0501** [Implem/Implem.Pleasanter#489]
少しバージョンが古いChrome（バージョン83）でダッシュボード機能を利用しようとすると白い画面で何も読み込まれません。

「※ダッシュボード機能が実装されたver.1.3.44.0以降では、IE(EdgeのIE互換モードを含む)は動作対象外となりますのでご注意ください。」
とのことですが、Chromeのバージョンが古い（バージョン83）場合も利用できないという理解で良いでしょうか？
（サポートするバージョン等の情報を探したのでIE以外の情報は出てこなかったため）

Parameters内のファイルを見てみたのですが、対応するブラウザのバージョン情報等を管理しているファイルは見当たらず。。。

IE：ログインすらできない（htmlのbodyがhiddenになる）
古いChrome：ログインやダッシュボード以外の機能の利用は可能だが、ダッシュボード機能は利用不可？

お手数ですが、サポート外のブラウザでも、無理やり機能が使用できる設定が可能なパラメータ棟がありましたらご教授いただけますでしょうか。
もしくは、ブラウザのバージョンによる制御を行っている処理部分について、ご教授いただけると幸いです。

**Comment by nozoe** [comment]
一ユーザですが…
ソースコードを見る限り、ブラウザのAgent情報で処理を分けているのはモバイル端末かどうかだけの様です。
それ以外にプログラム内部でブラウザのバージョンにより挙動を変えている部分は無いと思います。
基本的には最新のブラウザを利用しましょうだと思います。

いろんなバージョンでの動作検証をバージョンアップの度にやっているとリリースまでのタイムラグが大きくなり、あまりよろしくないと思います。
オープンソースですから、そういうのも含めてユーザの協力が必要だと個人的には思っています。

**Comment by pierre3** [comment]
Issueありがとうございます。
ブラウザにつきましては、最新のバージョンのご利用を推奨しております。
また、無理やり機能が使用できる設定が可能なパラメータなどもございません。
ご期待に沿えず申し訳ございませんが、ご理解のほどよろしくお願いいたします。
