### ISSUE TITLE
権限設定で、エクスポート/インポートを外しても”サイトの管理”権限を付与してしまうと表示される。

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#490]
Server: Windows2022Server + MSSQ+2022
CLient; Windows10 + Chrome
Pleasanter: 1.3.46.0

権限設定で、次の様な設定をした場合、管理メニューにサイトパッケージのインポート/エクスポートの操作が表示されないことを期待しているのですが、現在表示されてエクスポート操作が行なえてしまいます。
データを含まないエクスポートは正常に出来ます。

![親フォルダ開発者権限](https://github.com/Implem/Implem.Pleasanter/assets/17542768/3016f09a-3dd2-4e72-bab3-13c0095a4646)
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/173eb704-5703-4253-b87c-6bcdba06517a)

但し、データを含める指定をすると、
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/4f78a583-907d-4fda-b328-befca5edb2f1)
になります。

何を目的としているかというと、内田様が毎月１回Youtube上で行われているプリ生のQAを社内展開するために弊社の環境内に展開して触って試せてスクリプトが読める様にするためのデモ環境を構築し積極的に活用してくれている一部のユーザに管理者権限を付与しています。(オンライ視聴者が少ないのが残念ですが、非常に役立たせて頂いています)

で、御社から提供さてているデモ用のエクスポートファイルは別途参照出来る様にしているためこのデモ環境のデータをエクスポートして利用する必要は無いと思い権限を外しています。

サイトの管理にチェックを入れると基本殆どフルアクセスになるからだと思いますが、であればデータを含めたエクスポートも出来るべきかと…
個人的には、チェックに従ってメニューから消えるのが望ましいと思います。

ご検討よろしくお願いします。

**Comment by pierre3** [comment]
こちら、バージョン1.4.0.0にて下記の様に修正いたしました。

・「データを含める」としたサイトにアクセス権が無い場合でもエラーにならずパッケージの出力が可能。
・「データを含める」と設定した場合でもアクセス権の無いデータは出力されない。

どうぞよろしくお願いいたします。
