### ISSUE TITLE
1.3.46.0 で追加されたClientIDって何処に保存されますか？

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#491]
Paramaters/Syslog.json で、ClientID にtrue を設定してもログにClientIDが表示されない。
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/13f0fc92-2a35-4b12-ab3b-8e41971fbb28)
ちゃんと、プログラム更新して**dotnet Implem.CodeDefiner.dll _rds**も実行したはずなんですが…
![systemlog](https://github.com/Implem/Implem.Pleasanter/assets/17542768/8670279a-ee8b-4e89-92d3-71e7dfc4677a)

SAMLだからだめなのかと思い、SAML連携していないシステムでも試しましたが同じでした。
![systemlog2](https://github.com/Implem/Implem.Pleasanter/assets/17542768/3f013c00-bc6a-4b4f-b67b-7d90b922e553)

一応、データベースも覗いてsyslog テーブルを見てみましたが、ClientIDが保存されるカラムが有ることは確認出来ませんでした。

**Comment by pierre3** [comment]
ClientIDはSysLogsテーブルのCommentsカラムに記録されます。
Commentsは「システムログの管理」には表示されませんので、SSMSなどのDBクライアントツールでCommentsカラムをご確認ください。

**Comment by nozoe** [comment]
Login / Logout 時に Comments カラムに保存されている事確認いたしました。

**Comment by pierre3** [comment]
ご確認ありがとうございます。
本件クローズいたします。
