### ISSUE TITLE
M2 proのMacbook Proでのコンテナ起動で失敗する（Dockerイメージのarm64対応）

### ISSUE THREAD

**Issue by it-all-playpark** [Implem/Implem.Pleasanter#493]
M2 proのMacbook Proを利用していますが、READMEの#4のコマンド実行時に下記Warningが発生します。
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

```
Dockerイメージ `implem/pleasanter` がamd64対応はしているが、arm64に対応していないことが原因と思われます。
arm64でも利用できるようにしていただきたいです。

**Comment by imp-kawano** [comment]
Issueありがとうございます。

この問題はチームでも認識しており、対応する方向ですすめる予定です。
対応までお時間頂戴いたします、しばらくお待ちください。

**Comment by imp-kawano** [comment]
@it-all-playpark 
arm64版のDockerイメージをDocker Hubに公開致しました。
ご利用の際に、一度だけイメージのpullをしてからお試しください。

```bash
docker pull implem/pleasanter:codedefiner
docker pull implem/pleasanter:latest
```

**Comment by it-all-playpark** [comment]
@imp-kawano 
無事M2 Macで起動できました。
ありがとうございます。
