### ISSUE TITLE
FAQ：メール送信APIを使用して添付ファイル付きのメールを送信したい について

### ISSUE THREAD

**Issue by ebessan** [Implem/Implem.Pleasanter#494]
いつも利用させていただいてありがとうございます。
「FAQ：メール送信APIを使用して添付ファイル付きのメールを送信したい」
について、

JSON.stringfyで複数の添付ファイルの場合にundefinedで削除されたので、サンプルコードの116～124行目を

$.ajax({
                        url: apiSendMailUrl,
                        type: 'post',
                        async: false,
                        cache: false,
                        data: JSON.stringify(postData),
                        contentType: 'application/json',
                        dataType: 'json'
})

↓

postData =JSON.stringify(postData,(k,v) => v === undefined ? 'undefined' : v );
$.ajax({
                        url: apiSendMailUrl,
                        type: 'post',
                        async: false,
                        cache: false,
                        data: postData,
                        contentType: 'application/json',
                        dataType: 'json'
})

にしたら送れるようになりました。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。またTipsの共有ありがとうございます。

ただ私の方で試したのですが再現できませんでした、
お手数をおかけして申し訳ございませんが、下記の情報を頂けますと調査を進められると思います。
とは言え、問題が解消されているとの事ですので、ご都合がつきましたらで結構です。
- 欲しい情報
  - プリザンターのバージョン
  - 「送信」ボタンを押した際のデバッグコンソールの内容（機密情報はマスクして下さい。）


こちらで試した結果を添付いたします。
- 情報
  - プリザンターのバージョン
　1.3.47.0
  - 「送信」ボタンを押した際のデバッグコンソールの内容
![image](https://github.com/Implem/Implem.Pleasanter/assets/84897126/880440c2-da12-4283-a885-a9b1dda09a15)
