### ISSUE TITLE
サマリ機能を利用した更新について

### ISSUE THREAD

**Issue by s-miyashita** [Implem/Implem.Pleasanter#498]
「親子関係のサイトAとB」において、
サマリ機能を利用して「サイトB（子）」が「サイトA（親）」の件数を更新すると、
指定した項目だけでなく、更新者（Updator）と更新日時（UpdatedTime）も
自動的に更新されてしまう問題が発生しています。

これにより、「サイトA（親）」の最終履歴が上書きされ、
正確な履歴が維持できない状況になってしまいます。

以下のいずれかにて対応いただけませんでしょうか。

１．更新者や更新日時を更新対象から除外指定可能
２．別履歴のレコードを作成する

よろしくお願いいたします。

サイトBの指定
"Links": [
  {
    "ColumnName": "ClassA",
    "SiteId": 1,
    "NoAddButton": true
  }
],
"Summaries": [
  {
    "SiteId": 1,
    "DestinationReferenceType": "Issues",
    "DestinationColumn": "NumA",
    "LinkColumn": "ClassA",
    "Type": "Count",
    "Id": 1
  }
]

**Comment by pierre3** [comment]
Issueありがとうございます。

ご指摘の通り、現在のところ親サイトの履歴も更新される仕様となっております。
ご要望いただいた内容について、今後の製品開発の参考とさせていただきます。

**Comment by s-miyashita** [comment]
ご回答ありがとうございます。

サイトの変更履歴は利用ユーザにも好評で、
実施者が特定できるのが大変助かります。

是非今後改善をお願いいたします。

本件をクローズします。
