### ISSUE TITLE
『リンクしたアイテムの作成』のアクセス制御が、呼び出し元のアクセス制御になっている

### ISSUE THREAD

**Issue by alpha21264** [Implem/Implem.Pleasanter#50]
素晴らしい ソフトウェアを提供して頂きありがとうございます。
下記の件について、ご確認をいただければ幸いです。

【条件】
フォルダ　：　新規レコード作成 ⇒ 不可
　テーブル A：親　(期限付きテーブル)　フォルダのアクセス制御を継承
　テーブル B：子　(記録テーブル)　新規レコード作成 ⇒ 許可

【手順】
１．テーブル Aの編集画面『リンクしたアイテムの作成』から [+テーブル B]ボタンで
　　新規作成を行う。
２．各データを入力後に [作成]ボタンを押下
３．『この操作を行うための権限がありません』のメッセージが表示される

【予想される不具合】
・テーブル Bのアクセス制御について、テーブル Aの定義が使用されている？

【発生環境】
Plesanter バージョン：0.46.1.25007
Chrome バージョン：64.0.3282.140

**Comment by Implem** [comment]
issueありがとうございます。下記のような設定でためしてみたのですが、現段階で再現ができていない状況です。設定したときの画面などがあれば、共有してもらえると助かります。

サイト構成
![image](https://user-images.githubusercontent.com/12204265/35891138-1de6beac-0be6-11e8-9373-ce7a10758e95.png)

親フォルダのアクセス制御（佐藤さんの作成権限を除外）
![image](https://user-images.githubusercontent.com/12204265/35891180-575ab526-0be6-11e8-8ea1-98070502cb53.png)

記録テーブルのアクセス制御（佐藤さんの作成権限を追加）
![image](https://user-images.githubusercontent.com/12204265/35891220-86b988e2-0be6-11e8-8b7e-7436fe7136f4.png)

佐藤さんでログインし「記録テーブル」ボタンを押下
![image](https://user-images.githubusercontent.com/12204265/35891263-b7f9b364-0be6-11e8-932b-8c22f4a49842.png)

レコード作成に成功
![image](https://user-images.githubusercontent.com/12204265/35891284-d0fda5d2-0be6-11e8-9267-fbbc346fdc3c.png)

**Comment by alpha21264** [comment]
ご連絡が遅くなりまして申し訳ございません。
また、現象が再現しなかったと言うことで、
お手数をおかけして大変申し訳ありませんでした。

この現象について、私の方でも検証してみました。
結論から言うとアクセス制御の問題ではありませんでした。

テーブル B内の　テーブル Aタイトル項目の
読取専用チェック有でエラーが発生するようです。
※ 読取専用のチェックを外すと、レコードは正常に作成されます。

テーブル B編集時に テーブル Aのタイトルを変更出来ない【表示のみ】様に
設定する事は出来ないのでしょうか？

【トップ画面】
![image](https://user-images.githubusercontent.com/36157550/35906298-5a504ee8-0c2d-11e8-970e-d61f14c79fc0.png)

【テーブル B編集画面】
この中の『作業オーダ』は、テーブル Aのタイトルで、
上位基幹システムの識別 IDとなっております。
![image](https://user-images.githubusercontent.com/36157550/35906383-91bfdb3c-0c2d-11e8-815b-ac4663648d78.png)

【テーブル B設定画面】
『作業オーダ』は、テーブル Aからそのまま引継ぎ、
表示のみで変更出来ないようにする為、読取専用にチェックしています。
![image](https://user-images.githubusercontent.com/36157550/35906438-dcc80dd4-0c2d-11e8-8c76-8660f6dc7a81.png)

【エラー画面】
![image](https://user-images.githubusercontent.com/36157550/35906521-30fd407c-0c2e-11e8-90e3-a9842c3b4e81.png)

**Comment by Implem** [comment]
情報ありがとうございます。読み取り専用項目に値が投入されたと判定し、権限無しのエラーを表示していました。リンク項目の場合には、このような挙動をしないように修正しました。

https://github.com/Implem/Implem.Pleasanter/commit/eac3e2e5fbfa5495614ab968d3ceaa311041e5aa

**Comment by alpha21264** [comment]
ご連絡が遅くなりまして申し訳ございません。

早速の対応ありがとうございました。
Plesanter バージョン：0.46.19.34139
上記、バージョンにて解消されている事を確認致しました。
