### ISSUE TITLE
サーバスクリプト  items.Create でレコードを作成すると、レコードを作成したユーザにアクセス権が付与されない

### ISSUE THREAD

**Issue by tomohisajp** [Implem/Implem.Pleasanter#506]
### 事象
スクリプト $p.apiCreate でテーブル1の新規レコードを作成し、「作成後」にサーバスクリプトを発火し、サーバスクリプト items.Create でテーブル2の新規レコードを作成します。とくに指定していませんが、作成されたテーブル2のレコードの作成者(Creator)、更新者(Updator)の項目にはテーブル1の新規レコードを作成するきっかけとなったユーザが入っています。ところが、作成したレコードを編集画面の[レコードのアクセス制御]で参照すると、テーブル1のレコードはユーザにアクセス権限が与えられていますが、テーブル2のレコードは空になります。
テーブル2のレコードにもサーバスクリプトを発火するきっかけになり、レコードの作成者であるユーザにアクセス権が与えられるべきだと思いますが如何でしょうか？

自身が作成したレコードのみ表示するようにしたいためFAQを参考にしましたが、上記の場合レコードのアクセス権が誰にも与えられない状態になるため、結果動作しません。
ご検討ください。

FAQ：自分が作成したレコード、または自分が所属するグループや組織が作成したレコードのみ閲覧できるようにしたい
https://pleasanter.org/manual/faq-self-records

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

[元テーブル] → [テーブル1] → [テーブル2] とサーバスクリプトを用いて[テーブル1][テーブル2]にレコードを作成しているが、[テーブル2]に作成したレコードのレコード権限に意図していない権限（権限がからとなる）が付与されている
と認識しました。

[テーブル2]に作成するレコードに対する権限付与は[テーブル2]の管理画面でのルールに従います。従いまして[テーブル2]の管理画面でレコードに付与したいルールを設定して頂ければと思います。

もし認識に間違いがございましたら、お手数をおかけして申し訳ございませんがさらにコメントを頂ければと思います。
また該当内容が再現するサイトパッケージを添付いただけますと齟齬が減ると思われますので、ご提供の検討をお願いいたします。なお、サイトパッケージを添付いただく際には機密情報が含まれないようにして頂ければと思います。
