### ISSUE TITLE
テーブルのリンク機能の表示個数制限について

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#51]
お世話になっております。

[テーブルのリンク機能](https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E6%A9%9F%E8%83%BD%EF%BC%9A%E3%83%AA%E3%83%B3%E3%82%AF)を利用した際、選択肢として表示される項目の個数制限はありますでしょうか？
ちゃんと数えてはいないのですが、100個ほどしか表示できていないような気がします。

ご確認いただけますと幸いです。
よろしくお願いします。

**Comment by Implem** [comment]
issueありがとうございます。選択肢の一覧ですが、下記のパラメータにて制限されています。値を増やすか、検索で探していただくようおねがいします。

https://github.com/Implem/Implem.Pleasanter/blob/master/Implem.Pleasanter/App_Data/Parameters/General.json
"DropDownSearchLimit": 100,

**Comment by yyuki23** [comment]
ご返信ありがとうございます。
値を調整させていただきます。

ただもう一点。
検索機能なのですが、日本語の文字列はちゃんとヒットするのですが、英数字の場合だと検索しても所望の選択肢が出てこない場合があります。
こちらも合わせてご確認いただけますと幸いです。

どうぞ、よろしくお願いいたします。

**Comment by Implem** [comment]
検索対象のテーブルの管理で検索タブを開いていただき「タイトルの前方一致」や「タイトルの部分一致」を選択すると、改善する可能性があります。こちらはタイトルに含まれる項目をLIKE検索で抽出します。フルテキスト検索を選んでいる場合は、SQL Serverの全文検索機能でワードブレイキングとインデクシングがおこなわれるため、英数字、記号などが意図した形で検索できないことがあります。

**Comment by yyuki23** [comment]
お世話になっております。closeをしておらず申し訳ありません。
本日確認したところ、該当ソースに"DropDownSearchLimit": 100,がなくなっているように見受けられました。
本設定はなくなってしまいましたでしょうか？
ご確認いただけますと幸いです。

**Comment by Implem** [comment]
DropDownSearchLimitですが、DropDownSearchPageSizeに名称が変更となりました。
