### ISSUE TITLE
サーバスクリプトで イベント発火を抑止するプロパティが欲しい

### ISSUE THREAD

**Issue by kenichi-fk** [Implem/Implem.Pleasanter#514]
現状、サーバスクリプト内で Items.Updateを行うと、それを元に更新イベントが発生します。
そのため、現在のレコードの更新後に、サーバスクリプトで別レコードを更新したいとき、再度同じスクリプトが呼び出されてしまうので、VBAでいう Application.EnableEvents みたいな抑止手段が欲しいです。

**Comment by pierre3** [comment]
Issueありがとうございます。

本件、要望として承りました。今後の製品開発の参考とさせていただきます。

**Comment by kenichi-fk** [comment]
ありがとうございます。
ご検討宜しくお願い致します。
