### ISSUE TITLE
アクション種別「ポストバック」のボタンが２回目以降正常に動作しない

### ISSUE THREAD

**Issue by atst22** [Implem/Implem.Pleasanter#515]
プロセス機能で実行種別が「追加したボタン」、アクション種別が「ポストバック」のボタンを設置しクリックすると、１回目は正常だが、２回目は項目がリセットされます。
画面種別が「新規作成」の場合は規定値に、「編集」の場合は既に入っていた値に戻ります。

**Comment by pierre3** [comment]
Issueありがとうございます。

現象確認いたしました。
解決方法を検討いたしますので今しばらくお待ちください。

**Comment by pierre3** [comment]
本件、修正を行いバージョン1.4.4.0で解消いたしました。
