### ISSUE TITLE
画像機能で登録した画像の一覧画面での表示

### ISSUE THREAD

**Issue by iis-taguchi** [Implem/Implem.Pleasanter#52]
お世話になっております。
2/5公開バージョン0.46.1.25007から追加になった画像機能で登録した画像は一覧画面でも画像表示しますが、IE（11）に限ってサムネイル表示になりません。
※Chrome、Firefoxはサムネイル表示になります。

確認したブラウザのバージョン
IE: 11.0.9600.18499
Chrome: 63.0.3239.132
Firefox: 58.0.1

ご確認いただきますようお願いいたします。

**Comment by Implem** [comment]
こちら、弊社でも認識しており、最新版ではスタイルシートを調整しておりますので、最新版「Pleasanter.0.46.15.20330」に更新していただき、ブラウザのキャッシュをクリアしてみてください。最新版は公式サイトよりダウンロード可能となっております。

https://pleasanter.org/

**Comment by iis-taguchi** [comment]
最新版でも変化ありませんでした。IEのみサムネイル表示になりません。
なお前回からの事象ですが、一覧画面に表示する画像にマウスカーソルを重ねると画像の高さが変化します。幅は変わりません。
（Chrome、Firefoxではマウスカーソル重ねても画像サイズが変化することはありません。）
また画像ライブラリでも同様にIEだとサムネイル表示になりません。

**Comment by iis-taguchi** [comment]
最近別端末で確認した結果、IEでも正常に表示していました。
その間にバージョンアップを何度も繰り返していたため正常表示になったと思われます。
お騒がせしました。
