### ISSUE TITLE
サマリ の合計値の 切り捨て が正しくない

### ISSUE THREAD

**Issue by kenichi-fk** [Implem/Implem.Pleasanter#521]
サマリの合計値について、親テーブルの項目設定において 「小数点以下切り捨て」 を指定したとき、切り捨てられておらず四捨五入をしているようです。「切り下げ」 でも同様です。

|小数点第2位まで|小数点以下切り捨て|
|:----|:----|
|6.55|7|
|2.35|2|
|1.15|1|
|146.45|146|
|0.85|1|
|24.6|25|
|59|59|
|0.25|0|
|20040|20040|

**Comment by pierre3** [comment]
Issueありがとうございます。
確認いたしますのでお待ちいただけますでしょうか。
