### ISSUE TITLE
ファイルパスの生成漏れ

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#524]
以前も別にところで発生していたかと思いますが、確かパラメータservice.json の "AbsoluteUri"を書き換えていた際にパスが/直下になるという問題が有ったかと思います。

私の環境では、Pleasanter は　https://FQDN/pleasanter/ でアクセスするようにしています。

たまたま、IISのアクセスログを見ていたところ、404エラーになっていました。
対応漏れの箇所がまだ有るようです。

具体的にはpluginのlightbox 周りだと思います。

利用している環境は次の通りです。

よろしくお願いします。

Pleasanter 1.4.1.1　(最新版の1.4.2.1では未確認です)
WindowsServer 2019 +MSSQL

[lightbox.log](https://github.com/Implem/Implem.Pleasanter/files/14611152/lightbox.log)

**Comment by pierre3** [comment]
Issueありがとうございます。
本現象につきまして、Pleasanter 1.4.2.2で解消いたしました。
お手数をおかけいたしますが、本バージョン以降にアップデートのうえ再度ご確認をお願いいたします。
