### ISSUE TITLE
AddChoiceHashと「検索機能を使う」の問題

### ISSUE THREAD

**Issue by jdai-master** [Implem/Implem.Pleasanter#526]
ClassAに選択肢を任意でセットして「検索機能を使う」と「自動ポストバック」を使用した場合で、
ClassBの選択肢をそのポストバックでセットすると、ClassBの選択肢が表示されない問題に遭遇しました。

（例）
ClassAは固定でA,B,Cとして、サーバスクリプトは、
ClassBをAddChoiceHashでセットする以下のコマンドを入力して「画面表示の前」にチェックしました。

columns.ClassB.AddChoiceHash(1,'A');
columns.ClassB.AddChoiceHash(2,'B');

ClassAを選択するとき検索文字を入力せずダイレクトに選ぶと問題は発生しませんが、
検索文字を入れてから絞り込んで選ぶと、ClassBもその検索文字でフィルターされてしまいます。
この場合、Cを入力して選ぶとClassBには何も表示されません。
ClassAの検索文字をBSキーで消してから選ぶとClassBはすべて表示されます。

なにか設定ミスがあるのでしょうか？

**Comment by pierre3** [comment]
Issueありがとうございます。
確認いたしますので今しばらくお待ちいただけますでしょうか。

**Comment by jdai-master** [comment]
確認、よろしくお願いします

**Comment by jdai-master** [comment]
この件、その後どうでしょうか？かなり致命的問題だとおもいますが。
そろそろ対応お願いします。

**Comment by nagamune-implem** [comment]
回答が遅くなり申し訳ございません。

本件不具合である事が確認できました。
現在対応を進めており次回リリースで対応した内容を含める予定でおります。

ご迷惑をお掛けしいたしますが今しばらくお待ち頂ければとおもいます。

**Comment by jdai-master** [comment]
Pleasanter_1.4.5.0で改修されているのを確認しました。たすかりました、ありがとうございます。
