### ISSUE TITLE
1.4.3.0 のデフォルトのテーマで読みづらいページが…

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#530]
Pleasanter Version: 1.4.3.0
Server: Windows11 + MSSQL2022 express

早速、1.4.3.0 をテスト環境に導入し、何人かのユーザにテストサーバにインストールして見て貰い、中々好評です。

その中で問題が。。。

デフォルトのテーマで一覧表示では読み取れますが、
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/d7a8c4a6-fa7a-463e-b4d7-6da86209fb81)
編集画面に入ると白字から黒文字に代わってしまうため可読性が落ちているようです。
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/f2f9d60b-9020-4934-91d9-41b86778c1d5)
よろしくお願いします。

以前はこんな感じでした。
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/02f1cdc5-bd44-4d80-9cc6-d93f1f5af02f)
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/37916a50-5473-414e-8fbe-c3e8c12d2f5a)

**Comment by implem-noro** [comment]
Issueを起票いただきありがとうございます。
読取専用に設定している分類項目でご報告の事象が再現することを確認しました。修正について検討いたします。

**Comment by pierre3** [comment]
本件を修正したバージョン Pleasanter_1.3.4.1 をリリースいたしました。
ご確認をお願いいたします。
