### ISSUE TITLE
テーマ「cerulean」使用時にアナウンスとロゴが重なる

### ISSUE THREAD

**Issue by jaizawa758** [Implem/Implem.Pleasanter#531]
バージョン: 1.4.3.0

テーマ「cerulean」使用時にアナウンスがロゴと重なります。
https://pleasanter.org/manual/announcement-siteid

原因は下記のコードかと思います。高さが制限され、アナウンスとロゴが重なる。
https://github.com/Implem/Implem.Pleasanter/blob/8d3ee7073d05867c8f31dd25e2751c993498212d/Implem.Pleasanter/wwwroot/styles/plugins/themes/cerulean/custom.css#L1556-L1558

**Comment by pierre3** [comment]
本件を修正したバージョン Pleasanter_1.3.4.1 をリリースいたしました。
ご確認をお願いいたします。

**Comment by jaizawa758** [comment]
ありがとうございます。

バージョン 1.4.3.1
トップ画面はアナウンスとロゴが重なることはなく正常に表示されています。
ログイン画面はpleasanterへのリンクと重なり発生しています。

![image](https://github.com/Implem/Implem.Pleasanter/assets/130111760/cb0875e5-3101-4c6b-b340-554a1794068d)

**Comment by pierre3** [comment]
お待たせいたしました。
ログイン画面のpleasanterへのリンクと重なりにつきましては、バージョン1.4.4.0で解消いたしました。

お手数をおかけいたしますが、最新のバージョンにて再度ご確認をお願いいたします。
