### ISSUE TITLE
空のデータベースImplem.PleasanterがあるとCodeDefinerが失敗する

### ISSUE THREAD

**Issue by tats-u** [Implem/Implem.Pleasanter#532]
過去のインストール手順では、

1. 空のデータベース`Implem.Pleasanter`を作成
2. ↑のDBに`pg_trgm`を設定

を手動で行っていましたが、最近のバージョンでは空のDBがある状態で`CodeDefiner.dll _Rds`を行うと、ユーザ「`Implem.Pleasanter_Owner`」でのDB認証ができなかったという例外が出て失敗します。

DB：PostgreSQL（14・16）
バージョン：1.4.3・1.3.44.0・1.3.49.0

最近の手順に従い、データベースを作成さえしなければ成功します。
過去の手順を使い回して久しぶりにインストールするとこの事象に引っかかります。

**Comment by tats-u** [comment]
多分ここの間にユーザ作成済みかどうかのチェックがないのが原因です。

https://github.com/Implem/Implem.Pleasanter/blob/8d3ee7073d05867c8f31dd25e2751c993498212d/Implem.CodeDefiner/Functions/Rds/RdsConfigurator.cs#L77-L88

**Comment by pierre3** [comment]
Issueありがとうございます。

お知らせいただいたエラーについて内容を確認させていただきます。
また、過去の手順では問題が出るケースがございますので、できるだけ最新の手順にてインストールいただきますようお願いいたします。
