### ISSUE TITLE
SAML認証時に認証クッキーが永続化されている

### ISSUE THREAD

**Issue by yohshiro-711** [Implem/Implem.Pleasanter#534]
SAML認証利用時の認証クッキーの永続化を設定ファイルで指定できるようにするか永続化しないように変更したほうがいいのではないかと思います。
永続化しているとタイミングによってはidpの属性同期が実行されないケースも出てくると考えられます。
※有効期間が24hになっているため15:00頃に認証してログイン→翌日AM9:00にプリザンターを起動するとidpの認証に行かない
セキュリティ的にどうなんだろうというのもあります。

https://github.com/Implem/Implem.Pleasanter/blob/2a4ab3dddab7a5c1a0027e03322e9e0938dc49ca/Implem.Pleasanter/Libraries/DataSources/Saml.cs#L673

**Comment by pierre3** [comment]
Issueありがとうございます。

SAML認証時の認証Cookieを永続化させない設定を追加する方向で修正を検討させていただきます。

なお、認証Cookieの有効期限につきましては、Session.jsonのRetentionPeriodにて変更することが可能です。
https://pleasanter.org/manual/session-json

**Comment by pierre3** [comment]
お待たせいたしました。

Pleasanter_1.4.8.0 にて 
SAML認証時に認証Cookieを保存しないオプション"NotCreatePersistentCookie"を追加いたしました。

https://pleasanter.org/ja/manual/authentication-json

引き続きよろしくお願いいたします。

**Comment by yohshiro-711** [comment]
設定値の追加ありがとうございます。
issueクローズします。
