### ISSUE TITLE
ビューのフィルタ条件としてチェック項目を指定すると正常にフィルタされない。

### ISSUE THREAD

**Issue by fs-kaieda** [Implem/Implem.Pleasanter#541]
「テーブルの管理」の「ビューの設定」の詳細設定でフィルタ条件として「チェック」を設定すると、
一覧画面で当該ビューを指定した際のフィルタ条件が本来

`"ColumnFilterHash":{"CheckA":"true","CheckB":"true"}`

のようになっているべきところ

`"ColumnFilterHash":{"ClassQ~3,CheckA":"true","ClassQ~3,CheckB":"true"}`

と項目名に余計な "ClassQ~3," が含まれるため、どのレコードにも合致せず常にフィルタ結果が空になります。

上記の挙動は前述の当該ビューで一覧表示させた状態で左上の「トップ」の左の鎖マークのボタンで得られるURLと、
デフォルトのビューでチェック項目でフィルタした際に左上の「トップ」の左の鎖マークのボタンで得られるURLを
比較して確認しました。

お手数ですが、ご確認頂けますでしょうか。

（本件と関係ないですが『左上の「トップ」の左の鎖マークのボタン』に何か固有名称を設定して頂けると、こういう時の説明がしやすいです）

**Comment by pmc-ko** [comment]
そのCheckA、リンク先の項目ではないですか？

**Comment by fs-kaieda** [comment]
ご指摘ありがとうございます。
ビューのフィルタ設定ではリンク先ではないCheckAを指定していましたが、リンク先のCheckAが設定されていたようです。
一旦リンクを解除して、ビューを再設定したところ想定挙動になりました。
お騒がせしてすみませんでした。
