### ISSUE TITLE
新UIでのアナウンス

### ISSUE THREAD

**Issue by ebessan** [Implem/Implem.Pleasanter#542]
新UIになって、アナウンスのフォントサイズの指定ができなくなりました。「!important」をつけても変わりません。。。
いちいち書くのが面倒なので、

ClassA・・・アナウンス内容の入力欄
ClassB・・・背景色選択のプルダウンメニュー
ClassC・・・文字色選択のプルダウンメニュー
ClassD・・・文字の大きさのプルダウンメニュー
ClassE・・・文字の太さのプルダウンメニュー

として、内容に下記のようなサーバスクリプトで記入して表示しています。

```javascript
model.Body =<div style="background-color:' + model.ClassB + ';color:' + model.ClassC + ';padding:5px;font-weight:' + model.ClassE + ';border:solid 1px white"><font size=' + model.ClassD + 'px>' + model.ClassA + '</font></div>'
``` 
class=announcementsのfontsizeが優先されているようなのですが、なぜでしょう？？？

OS Almalinux9
DB postgres16
Ver Pleasanter1.4.4.0

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

回答が遅くなり申し訳ございません。

font要素は現在非推奨ですので、span要素に置き換えてstyle属性で指定する方法をおすすめします。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/font


spanでの記載例を下記に記しますので、内容を参考に適宜書き換えて試して頂ければと思います。
``` javascript
model.Body = `<span style="background-color:${model.ClassB};color:${model.ClassC};font-size:${model.ClassD};padding:5px;font-weight:${model.ClassE};;border:solid 1px white;font-size:${model.ClassD}px">${model.ClassA}</span>`;
```

**Comment by ebessan** [comment]
ありがとうございます。
font要素は非推奨なんですね。申し訳ありませんでした。
いただいたコードを参考に下記のように書き直して望み通りの動作になりました。
※いただいたコードだと入力部分のみbackground-colorが適用されてしまったので、、、
```javascript
model.Body = `<div style="background-color:${model.ClassB};color:${model.ClassC};padding:5px;border:solid 1px white"><span style="font-weight:${model.ClassE};font-size:${model.ClassD}px">${model.ClassA}</span></div>`;
```
