### ISSUE TITLE
cerulean系のテーマを使った場合の表示崩れ

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#544]
フォルダ名や、テーブル名が長く階層が重なる場合に

cerulean系のテーマを選択した場合、それぞれの場所で行の折り返しが発生しますが、枠外に表示されます。
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/708441d2-2638-47ba-b871-8e41d7a1d988)
更に深くなると…
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/1510cefc-bdf8-4e34-8157-3c1dd4b7152e)

sunny の場合は、特に問題はなかったのですが…
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/38a9e4b7-c4f5-4745-8b61-7940ba82768d)

対応可能かどうかはわかりませんが、一応報告しておきます。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。
回答が遅くなり申し訳ございません。
本件ですは先週リリースした(Pleasanter_1.4.5.0)にて対応をいたしました。
お手数をおかけして申し訳ございませんが、意図通りかご確認頂ければと思います。

**Comment by nozoe** [comment]
先ほど、本番環境をバージョンアップしたので確認してみましたが、変わった気がしません…
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/44a493ed-121d-42da-937e-4eae4e8659cf)

**Comment by nagamune-implem** [comment]
ご連絡ありがとうございます。
申し訳ございません、貼って頂いた画面キャプチャ内の階層を再現し再度確認したところうまく行っていない部分がございました。
再度ソースコードの確認を行いたいと思います。

**Comment by nozoe** [comment]
1.4.6.0 で表示崩れが収まりました。
対応ありがとうございました。
![image](https://github.com/Implem/Implem.Pleasanter/assets/17542768/f258b30a-b216-4ce5-a4a2-c14fec0c85fa)

**Comment by pierre3** [comment]
ご確認いただきありがとうございます。
引き続きよろしくお願いいたします。
