### ISSUE TITLE
項目選択でColumnFilterNegativesが効かない

### ISSUE THREAD

**Issue by jdai-master** [Implem/Implem.Pleasanter#547]
分類AでユーザID選択を選択させるとき、以下のコードで部署のないユーザ（例：Administratorなど）を選択肢から除外しようとしましたが、部署のないユーザしか表示されません。どこか指定が間違っていますでしょうか？
（フィルタの否定フィルターを使うはチェック済みです）

[
  {
    "TableName": "Users",
    "SearchFormat": "[Dept]-[Name]",
    "View": {
        "ColumnFilterHash": {
            "DeptCode": " "
        },
        "ColumnFilterNegatives": [
            "DeptCode"
        ]
    }
  }
]

Pleasanter バージョン1.4.5.0

**Comment by pierre3** [comment]
Issueありがとうございます。

ColumnFilterNegatives を有効にするには、リンク先のテーブル（本ケースではUsersテーブル）の設定で「否定フィルタを有効」とする必要がございます。
しかし、ユーザの管理では「否定フィルタを有効」とする設定がないため、今回のケースでColumnFilterNegatives を利用することはできません。

**Comment by jdai-master** [comment]
なるほどユーザーテーブルでは否定フィルタが使えないのですね。
例えば、ユーザ一覧からAdministratorを除く方法は他にありませんか？

**Comment by pierre3** [comment]
回答遅くなり申し訳ございません。
残念ながら、今のところご要望にお応えできるような設定はございません。

ユーザテーブルでも否定フィルタを利用できるよう検討いたします。
