### ISSUE TITLE
cerulean系の編集画面で「状況」にスタイル指定が効かない

### ISSUE THREAD

**Issue by jdai-master** [Implem/Implem.Pleasanter#548]
他の方からも上がっているかもしれませんが、
ceruleanのテーマで以下のようなスタイルを「状況」に設定すると
一覧画面では白い文字なりますが、編集画面では黒になります。
この場合、背景色がダーク系だと文字が読めません。
また、ダーク系のmidnightのテーマの場合は背景色が反映されません。
どちらも一覧画面では問題ありません。

.status-wait {
     color:white;
     background: rgb(0 0 70);
}

**Comment by pierre3** [comment]
「状況」のstatus-wait の現象ですが、手元の環境 version 1.4.5.0 では再現しませんでした。
お手数をおかけしますが、発生時の状況を詳しく教えていただけますでしょうか。
・プリザンターのバージョン
・上記スタイルの他に、スタイルやスクリプトの設定は無いか
・問題発生時の画面や設定画面のキャプチャなど

> また、ダーク系のmidnightのテーマの場合は背景色が反映されません。
こちらにつきましては、現象を確認いたしました。
修正いたしますので、お待ちいただけますでしょうか。

**Comment by jdai-master** [comment]
バージョンはversion 1.4.5.0です。
もう１つ条件がありました。
「状況」のカラムが読み取り専用の場合に発生します。

**Comment by pierre3** [comment]
お待たせいたしました。
本件、バージョン1.4.8.0にて修正いたしました。
バージョンアップの上、再度ご確認をお願いいたします。

**Comment by jdai-master** [comment]
ありがとうございました。バージョンアップしたときに確認いたします。
