### ISSUE TITLE
エクスポート時にリンク項目がIDとなります

### ISSUE THREAD

**Issue by kyoto-naruto** [Implem/Implem.Pleasanter#55]
エクスポート時にリンク項目がリンク先のIDとなります。
表示と同じ内容で取得する事は可能でしょうか？

**Comment by Implem** [comment]
Issueありがとうございます。エクスポートの項目の詳細設定で、出力の設定に「値」を指定している場合はIDが出力されます。「表示名」に設定することで表示と同じ内容が出力されます。

このような設定をしていない場合には、なにか発生条件があるかもしれないので、もう少し詳しくおしえてください。

たとえば、デモサイトの、商談管理の例 - 仕入テーブルで「標準」でエクスポートを行うと、上位の商談テーブルの名前がエクスポートされます。これが名前ではなく、IDになるという不具合でよろしかったでしょうか。

**Comment by kyoto-naruto** [comment]
名前ではなく、IDになるという状況でした。
0.47.1.30740では名前でexportできました。

**Comment by Implem** [comment]
ありがとうございます。また再現するようでしたらおしえてください。
