### ISSUE TITLE
テーブルでデータをインポートするとサイトIDがカウントされる

### ISSUE THREAD

**Issue by nsd-taki** [Implem/Implem.Pleasanter#551]
**現象**
テーブルでデータをインポートするとサイトIDがカウントされる。

**環境**
- Windows 11 Home 23H2
- IIS 10.0..22621.2860
- PostgreSQL 16
- Pleasanter_1.4.5.0

**手順**
- サイトIDは22(Sitesテーブルで確認)あるとき
- テーブルのインポート機能で97168件データを取り込む
- 新規にテーブルを作成したサイトIDを見ると97168になっている(Sitesテーブルで確認)

テーブルのSiteIdの型がbigintとなっているので運用上は問題ないとは思いますが、保守観点上は少し混乱するのではと思います。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

※）手順を下記に読み替えて回答を作成しております。
・新規にテーブルを作成したサイトIDを見ると```97190```になっている
　97168 => 97190

本件はプリザンターの仕様となります。
プリザンターでは内部の管理単位で連番を付与している関係でこのようなIDとなっております。
ご理解のほどよろしくお願いいたします。

以上、よろしくお願いいたします。

**Comment by nsd-taki** [comment]
回答ありがとうございました。
データ移行(インポート)する時は留意いたします。

**Comment by nagamune-implem** [comment]
@nsd-taki 
ご確認ありがとうございます。
問題が解決されたようでしたら、お手数をおかけして申し訳ございませんが本IssueをCloseして頂けると助かります。
