### ISSUE TITLE
【続】cerulean系のテーマを使った場合の表示崩れ

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#552]
一度クローズした、cerulean での表示崩れですが、1.4.6.0 で正常に表示されるようになったと思ったのですが、
ビューの切り替え枠があると重なって表示されてしまっている様です。
キャプチャは、Version 1.4.6.3 で行いましたが、1.4.6.0 でも同様に重なっています。

よろしくお願いします。

![image](https://github.com/user-attachments/assets/4fbeb3af-3f72-45d5-a5c8-53e351e7a766)

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

状況を確認して何かしら良い対応方法が無いか検討を行いたいと思います。

**Comment by pierre3** [comment]
お待たせいたしました。
本件につきまして、バージョン1.4.8.0にて改善いたしました。

バージョンアップの上、再度ご確認をお願いいたします。
