### ISSUE TITLE
ブラウザの表示の拡大・縮小機能を使うと集計の表示が崩れる

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#554]
ブラウザで表示中に表示の拡大縮小機能を利用すると集計の表示が崩れる場合がある。
これは特定の倍率で表示されるわけではなく、個々の環境により倍率が異なっている。

Pleasanter Version: 1.4.5
Client; Windows10 Edge or Chrome 

通常
![image](https://github.com/user-attachments/assets/4f42ae19-d84d-4dc9-9a47-730c6251ce95)
縮小 90%
![image](https://github.com/user-attachments/assets/e7af067e-8371-461f-863c-f6d21c3ccec6)
縮小 80%
![image](https://github.com/user-attachments/assets/b9d8c42b-aa06-4601-837b-e84fc7583db2)
縮小 75%
![image](https://github.com/user-attachments/assets/22aa974f-8db6-4d09-8310-e1b326124c1f)

よろしくお願いします。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

状況を確認いたしました。

拡大・縮小しても、なるべくレイアウト崩れが発生しないようにしたいと考えております。
ただ拡大・縮小に関してはレイアウト上の制約やブラウザエンジンやブラウザバージョン等によって動作が変わってしまうことを考えますと、崩れが発生しない事の動作確認と動作保証は難しいと考えております。

なにとぞご理解の上、ご了承のほどよろしくお願いいたします。

**Comment by nozoe** [comment]
了解致しました。
そのうちなんとかなれば良いなぁと思って待ってます。
