### ISSUE TITLE
Edgeブラウザのオートコンプリートが有効時の動作が…

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#555]
Pleasanter Version: 1.4.6.4　(1.4.5.0でも同様)
Client: Windows10 / Edge

上記の環境で、ブラウザのオートコンプリート機能が有効な場合、特定のフィールドのデータをオートコンプリート機能を用いて入力しようとすると、関連性の無い？複数のフィールドのデータも同時変更されてしまう事象が発生しています。
添付ファイルとして操作時の動画を付けてありますのでご確認いただければと思います。
(もっと多くのフィールドが変わっています)
複数の端末で同じ様な状況になっていますので、端末依存では無いと思います。

ドキュメントを読んで確認したところ、General.json の    "DisableAutoComplete": true" に変更して再起動すれば止まる様に読めたので、今日のバージョンアップ作業と併せてパラメータを変更し再起動を行ったのですが、残念ながら止まりませんでした。

ページのソース表示で確認すると、
**DisableAutoComplet**e を **true** にすることによりPleasanter が生成するコンテンツの **Form** タグには、 **autocomplete="off"** が追加れていますが、残念ながらそれでも抑止されませんでした。

　　　　`<form id="MainForm" class="main-form confirm-unload" action="/pleasanter/items/802843/_action_" autocomplete="off">`

複数フィールドのデータが同時に書き換わらない様にする方法はなにか無いでしょうか？

https://github.com/user-attachments/assets/081a1b10-475e-45ea-9983-01b8a54fec7b

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

ご迷惑をおかけして申し訳ございません。

状況を確認いたしました。
今の所はhtmlの表記ではこのブラウザのオートコンプリートの動作を完全にコントールする事は難しいと考えております。
引き続き良い回避方法等が無いか調査をいたしますが、現状では制約事項とさせて頂きたくよろしくお願いいたします。
どうしてもこの振る舞いが許されない場合はブラウザ側のオートコンプリート機能をOffにして頂く等もご検討頂ければと思います。

**Comment by nozoe** [comment]
了解いたしました。
ブラウザ依存なので、仕方が無いと思います。
既に利用者には注意するように促していますので、大丈夫かと思います。
