### ISSUE TITLE
HttpClientでレスポンスヘッダーをハンドルしたい

### ISSUE THREAD

**Issue by Sak37** [Implem/Implem.Pleasanter#556]
やや特殊なシチュエーションかも知れませんが、サーバスクリプトで外部サービスへアクセスした後、レスポンスヘッダーを参照したいです。
（HttpClient.cs では、レスポンスヘッダーを捨ててしまっています）

`StatusCode`や`IsSuccess`と同様に、`ResponseHeaders`という名前のDictionaryをServerScriptModelHttpClientクラスへ追加できないでしょうか？

ご検討よろしくお願いします。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

ご要望頂いた件に関して、実装出来ないか等の検討を行いたいと思います。

**Comment by pierre3** [comment]
ServerScriptModelHttpClient
にResponseHeadersプロパティを追加する。

**Comment by pierre3** [comment]
バージョン1.4.8.0にてResponseHeadersプロパティを追加いたしました。

https://pleasanter.org/ja/manual/server-script-http-client

バージョンアップのうえ、ご確認をお願いいたします。
