### ISSUE TITLE
ServerScript が呼び出される要因判定

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#557]
データの更新処理等を行った場合に、サーバスクリプトの処理が何度も実行される事象があり、
原因を追求していったところデータの更新時にポストバック処理するデータが幾つかありそのために何度もサーバスクリプトが呼び出され、その副作用で処理が正常になされない状況になっています。(他の人が作ったサイトなので…)

色々調べている過程でたまたまCopilot に聞いたら、

`if (context.RequestType === 'PostBack') {
    // ポストバック時に実行される処理
}`

で出来るという回答が得られましたが、この**context.RequestType**は、Pleasanter のマニュアルには記載されていない様です。

この機能は、実装されているのでしょうか？
(Copilot で同じ回答を得られない…)

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

ご迷惑をおかけして申し訳ございません。
「その副作用で処理が正常になされない状況」に関してもう少し事象の発生するサイトパッケージの添付や事象の発生する手順等の情報をいただけませんでしょうか？

またCopilotで得た情報に関しては、思い当たる箇所がございません。
context.RequestTypeも実装しておりません。

以上、よろしくお願いいたします。

**Comment by nozoe** [comment]
サーバスクリプトの設定画面で、最初にサイト番号等の様な共通的な定数となる値をconst 定義して**共通**として設定、2番目以降にその定数を参照して動く関数を更新前、更新後等で定義すると一度のサーバスクリプトの実行で何度も共通として設定した部分が実行？されている様で、2度目にその定数定義さ参照された際にconst の2重定義となりエラーとなります。
何度も動いているのは、context.Logを挿入して確認しました。

const のエラーは、var やlet に変更すればエラーにならなくすることは分かっていますが、そもそもサーバスクリプトってどの様なタイミングでどの様に展開されて実行されているのかがイマイチ見えないのでその辺の仕組みを明らかにしてほしいというのがあります。

それと、ポストバックの時の動作やmodel.UpdateOnExit = true;の時の動作が知りたいです。
同一プロセスで実行？(同一コンテキストで実行されるパターンと別コンテキストで実行される)

質問は私が行っていますが、実際に作成しているのは私では無いので、中々説明するのが難しいのですが…

私の思いはサーバスクリプトは、それぞれのシチュエーション(作成前、後、更新前、後等で)チェックされたスクリプトが一度t展開され、それぞれ実行されるという認識でしたがその認識が今の動きを追っていると違う様に見えます。
ということで、上記の疑問になっています。

参考となるサイトパッケージの提供は、色々加工する必要があるためスグには難しいです。
