### ISSUE TITLE
タイトル項目の重複禁止の動作の件

### ISSUE THREAD

**Issue by jdai-master** [Implem/Implem.Pleasanter#558]
記録テーブルの「タイトル」に「分類A」だけを設定し、重複禁止にした場合、
「分類A」にすでに作成した重複した値を入力し、さらに新規に作成しても重複エラーは発生しません。
(「分類A」は重複不可に設定していません)

期限付きテーブルで同じようにした場合は逆に、「分類A」に重複してない値をいれても
「タイトル が重複しているため更新できません」と表示されます。
つまり、なにも新規に作成できない状態になります。

これは、正しい動きなのでしょうか？
使用バージョンはVer1.4.5.0です。
よろしくお願いします

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

状況を確認いたしました。
本件は不具合と思われます、調査対応を行いたいと思います。
