### ISSUE TITLE
タイトルの現在の設定でタイトル以外の項目を割り当てているとリンクで表示しようとすると空になる

### ISSUE THREAD

**Issue by sato-ha** [Implem/Implem.Pleasanter#559]
バージョン1.4.6.4において
エディタのタイトルの詳細設定で現在の設定にタイトル以外の項目を割り当てていると他のテーブルにリンクしたときにリンク表示される部分でタイトルを設定しても空欄になってしまう。

**Comment by nagamune-implem** [comment]
Issue1ありがとうございます。

確認してみたのですが、再現方法が分かりません。
該当箇所がどこなのかや、何か手順に漏れが無いかご指摘を頂けませんでしょうか？

・手順
1. 記録テーブル(親)を作成
2. 記録テーブル(子)を作成
3. 「記録テーブル(親)」と「記録テーブル(子)」に親子関係を持たせる。「記録テーブル(親)」「ClassA」に「記録テーブル(子)」を紐づける
4. 記録テーブル(親)のテーブル編集で「タイトル」に「タイトル」を外し「ID」と「状況」を追加
5. 記録テーブル(子)のテーブル編集で「タイトル」に「タイトル」を外し「ID」と「状況」を追加
6. 記録テーブル(親)の一覧表示に「記録テーブル(子)」の「タイトル」を追加
7. 記録テーブル(子)の一覧表示に「記録テーブル(親)」の「タイトル」を追加

上記設定後しレコードを親と子にレコードを追加し下記を確認したが、タイトルには「ID」と「状況」が格納されている
・レコード編集画面下部の「リンク」の「タイトル」
・一覧表示の「親のタイトル」
・一覧表示の「子のタイトル」

同様に「期限付きテーブル」での確認もおこなった。

念のために実験したサイトパッケージも添付いたします。
[#559_タイトルの現在の設定でタイトル以外の項目を割り当てているとリンクで表示しようとすると空になる_2024_08_13 11_51_15.json](https://github.com/user-attachments/files/16593895/559_._2024_08_13.11_51_15.json)

**Comment by sato-ha** [comment]
確認いただきありがとうございました。お手数をお掛けして申し訳ありませんでした。
こちらでも新規にテーブルを作成して検証したところ事象が再現できませんでした。
問題の出ているテーブルはスクリプトを利用してタイトルに使用している説明Aをスクリプトで書き換える処理をしていたので、それが悪さをしているようです。こちらのissueはクローズしてください。
