### ISSUE TITLE
レコード作成時のアクセス制御

### ISSUE THREAD

**Issue by takaoyama** [Implem/Implem.Pleasanter#56]
いつもお世話になっております。

レコードのアクセス制御を設定したサイトにおいて
新規作成時にファイル添付を行うと、当該レコードへ
レコードのアクセス制御が付与されないという事象がありました。

確認と対応をお願いいたします。

利用バージョン：0.46.37.35238

それ以降のバージョンで対応済でしたら申し訳ございません。

**Comment by Implem** [comment]
Issueありがとうございます。不具合がございましたので修正いたしました。

https://github.com/Implem/Implem.Pleasanter/commit/eb56c1fd2f3b8cb69da4f45da1337d8f6e9771fd

**Comment by takaoyama** [comment]
修正ありがとうございました。
