### ISSUE TITLE
カレンダーのフィルタの挙動について

### ISSUE THREAD

**Issue by sato0928** [Implem/Implem.Pleasanter#560]
カレンダーの動作についてです。
ビューの設定で[フィルター]-[フィルター条件]で未完了をチェックしていると当然完了のレコードは表示されませんが、
カレンダーのページでチェックを外して完了を表示するフィルタ設定にしていても月を切り替えると完了のレコードが表示されません。
ページを切り替えるごとにデフォルトのフィルタ設定になっている挙動のように思います。

また、現在以外の月でフィルタの設定をいじると強制的に現在の月に戻されるので、これも使いづらく感じます。

これらの挙動は月だけでなく週でも日でも同じです。
標準カレンダーでもFullCalendarでも同じです。

ご確認よろしくお願いいたします。

バージョン1.4.7.1

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

動作を確認いたしました。

●その１
○ご指摘
・前月・来月ボタン等で移動するとフィルタ条件がビュー設定の状態に戻る。
○回答
・確認させてください、「ビューの保存種別」が「保存しない」になっているかご確認いただけますでしょうか？
　テーブルの管理：ビュー | Pleasanter
　https://pleasanter.org/ja/manual/table-management-view

●その２
○ご指摘
・現在以外の月でフィルタの設定をいじると強制的に現在の月に戻される
○回答
・状況が再現出来ました。
　ご指摘の通り、使いづらいと感じました。
　修正できないか調査・検討したいと思います。

**Comment by sato0928** [comment]
ご回答ありがとうございます。

●その１
>「ビューの保存種別」が「保存しない」になっているかご確認いただけますでしょうか？

「保存しない」になっておりました。
これを「セッション」にすると月を切り替えてもフィルタの設定が保持されたまま期待通りの動作をしました。

「セッション」の状態であれば『その２』のフィルタの設定を変えると現在の月に飛ぶ症状も現れませんでした。
「ビューの保存種別」「保存しない」が悪さをしているように感じます。

ご確認よろしくお願いいたします。

**Comment by nagamune-implem** [comment]
@sato0928 
申し訳ございません。
> ●その２
○ご指摘
・現在以外の月でフィルタの設定をいじると強制的に現在の月に戻される

上記に関しても「ビューの保存種別」「セッション」にすれば、フィルター条件が保持されていました。
従って「修正の必要は無い」と認識いたしました。

お手数をおかけして申し訳ございませんが、問題が解決したようでしたら本IssueをCloseして頂ければと思います。

**Comment by sato0928** [comment]
確かに「セッション」にしておけば問題はございません。

ただ、「ビューの保存種別」というのはユーザが選択したビューをいつまで保持しておくかの機能であって、
例えば「セッション」であればセッションが切れるまでは既定のビューよりユーザの選択が優先され、
「保存しない」であれば画面の切り替えがあれば既定のビューにするという管理者の意向が優先される設定であるという認識でおります。

これがカレンダーの月/週などを切り替える度にセッションが切れたからフィルタ情報を保持しないというのは動作として正しいのでしょうか。
少なくともそのような意図で「保存しない」を選択する管理者はいないと思いますしユーザはこの現象を理解できないのではないかと思います。
現時点では「保存しない」とした場合、現在の月以外の月でフィルタを変更する方法は無いのではないかと思いますので
フィルタを変えたつもりでデータを遡った場合などはデータを読み誤る可能性が高いと感じました。

これが私の認識違いで「そういう機能ではない」という話であればクローズしようと思います。

しかしながら、これに関連して明確に不具合と呼べる部分もございますのでご確認いただけますと幸いです。
デフォルトを「未完了：チェック有り(=完了は表示しない)」にしてカレンダーで画面上部のフィルタ設定の未完了のチェックを外して完了も表示させる設定にして月を切り替える場合、
上部のフィルタ設定はチェックが外れたままにも関わらず表示される内容はデフォルトの「完了は表示しない」状態にもどっています。

分かりにくくなったので指摘内容を要約すると
カレンダー上でフィルタの設定を変えた上で月を切り替えるとフィルタ設定の変更は表示としては保持されるが
カレンダーに表示される項目はデフォルトフィルタに従うため設定と表示内容が食い違う、という事になります。

**Comment by nagamune-implem** [comment]
ご丁寧なご説明ありがとうございます。

下記の内容と認識しました。

●指摘
○指摘内容
・画面上部のフィルター設定と画面下部のデータ表示でフィルター絞り込みに差異がある。
○再現手順
・期限付きテーブル作成
・ビュー作成。「表示：カレンダー」、フィルター設定「未完了：チェックOn」、「ビューの保存種別：保存しない」設定
・レコードを２件作成
・１件は「状況：未着手」作成
・１件は「状況：完了」作成
・一覧＋作成したビュー表示に切替
　→ フィルター設定「未完了：チェックOn」とデータ「状況：未着手」が表示される
・フィルター設定「未完了：チェックOff」
　→ フィルター設定「未完了：チェックOff」とデータ「状況：未着手」と「状況：完了」が表示される
・「来月」ボタンを押下
・「先月」ボタンを押下
　→ フィルター設定「未完了：チェックOff」とデータ「状況：未着手」が表示される
　　★フィルター条件とデータ表示で不整合の状態

修正できないか調査・検討したいと思います。

**Comment by sato0928** [comment]
ご認識の通りでございます。
お手数をおかけしますがよろしくお願いいたします。
