### ISSUE TITLE
スクリプト $p.apiGet を用いた、複数選択の設定をしたリンクの親テーブルの値の取得について

### ISSUE THREAD

**Issue by yuki-itoga** [Implem/Implem.Pleasanter#562]
Issue というより質問になってしまうかもしれませんが……。

親テーブル（サイト ID: 1）、子テーブル（サイト ID: 2）をそれぞれ作成し、子テーブルの分類 A の「選択肢一覧」に `[[1]]` を設定することでリンクを作成します。

また、子テーブルに次のような HTML を追加します（挿入位置：Body script bottom、出力先：編集）：
```
<script>
  $p.apiGet({
    id: $p.id(),
    data: {
      View: {
        ApiDataType: 'KeyValues',
        GridColumns: ['ClassA~1,Title']
      }
    },
    done: function(data) {
      console.log(data);
    }
  });
</script>
```

親テーブルにいくつかレコードを作成した上で、子テーブルにレコードを作成します。このとき、子テーブルのレコードの分類 A で、親テーブルのいずれかのレコードを選択します。

この状態で子テーブルのレコードをエディタ画面で開くと、上記の `$p.apiGet` によって親テーブルの値が取得できます（意図通りの動作）。

ここから、子テーブルの分類 A の「複数選択」のチェックボックスをオンにし、親テーブルのレコードを（ひとつまたは複数）選択し直した上で、同様に子テーブルのレコードをエディタ画面で開いても、親テーブルの値が取得できていません。

`$p.apiGet` では、複数選択できる親テーブルの値は取得できないのでしょうか。

なお、バージョンは 1.4.7.2 で、IIS + SQL Server の環境です

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

動作が再現出来ました。
不具合の疑いが高いと思います、修正できないか調査・検討したいと思います。
