### ISSUE TITLE
サーバスクリプトでレコードを作成したら日付が1日前になる

### ISSUE THREAD

**Issue by jdai-master** [Implem/Implem.Pleasanter#563]
あるレコードの更新前のタイミングで、別の記録テーブルに保存したら日付カラムが1日前で保存されます。

let logSiteId = 12345;
let newitem = items.NewResult();
newitem.DateA = saved.DateA;　　　　→　2024/08/27が2024/08/26で保存される
items.Create(logSiteId, newitem);

この問題と関係がありますか？
[Implem/Implem.Pleasanter #175](https://github.com/Implem/Implem.Pleasanter)
回避方法を教えてください。

**Comment by jdai-master** [comment]
使用Verは、1.4.5.0です

**Comment by jdai-master** [comment]
9時間ずれていましたので、時差修正したらうまくいきました。
newitem.DateA = saved.DateA.toLocaleString("ja-JP",{timeZone:"JST"});
これは仕様ですか？

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

調査いたしますのでしばらくお待ち頂ければと思います。

**Comment by jdai-master** [comment]
これは、ひょっとして新アイテム変数だけに、起きる現象かもしれません。
（items.NewResult()など）
model.DateA = model.DateB を
model.DateA = model.DateB.toLocaleString("ja-JP",{timeZone:"JST"});
にするとずれました。
