### ISSUE TITLE
プロセスの一括処理とサーバースクリプトの連携について

### ISSUE THREAD

**Issue by noyome123** [Implem/Implem.Pleasanter#565]
サーバースクリプトでプロセスID:10の処理時に以下のようにすると動作しますが、

context.Log(context.Forms.ControlId());
    switch (context.Forms.ControlId()) {
        case 'Process_10': 
            context.Log('Process_10);
        case 'Process_20': 
            context.Log('Process_20);
        default:
            break;
    }

これをプロセスで「一括処理を許可」として、一覧画面から一括処理しようとすると、
context.Forms.ControlId())の値が「BulkProcessCommand」なるため条件で処理ができません。

ワークフローの一括承認機能を付けようと考えています。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。


一覧画面から一括処理の場合には「BulkProcessingItems」にプロセスIDが格納されます。
サンプルコードを添付いたしますので、参考にして頂ければと思います。

```js
try {
    context.Log('処理開始');
    context.Log(context.Forms.ControlId());
    if(context.Forms.ControlId() == 'BulkProcessCommand'
            && context.Forms.Exists('BulkProcessingItems')){
        // 一覧画面から一括処理の場合の処理
        context.Log(context.Forms.Data('BulkProcessingItems'));
        const processId = context.Forms.Int('BulkProcessingItems');
        switch (context.Forms.ControlId()) {
            case 10:
                context.Log('Process_10');
            case 20:
                context.Log('Process_20');
            default:
                break;
        }
    } else {
        // 編集画面でプロセスボタン(＋更新)押下の場合の処理
        switch (context.Forms.ControlId()) {
            case 'Process_10':
                context.Log('Process_10');
            case 'Process_20':
                context.Log('Process_20');
            default:
                break;
        }
    }
    context.Log('処理終了');
} catch(e) {
    context.Log('エラー発生');
    // エラーログ出力
    context.Log(e);    
    context.Log(e.stack);    
}
```

**Comment by nagamune-implem** [comment]
先のサンプルコードに関しまして注意事項がございます。
本サンプルコードはソースコードを解析し動くように記載した物です、もしかしたら今後仕様変更が入る場合があるかもしれません。
不明瞭な回答となり申し訳ございませんが、本注意事項も踏まえたうえでご参考にして頂ければと思います。

**Comment by noyome123** [comment]
ありがとうございます！

if(context.Forms.ControlId() == 'BulkProcessCommand'
            && context.Forms.Exists('BulkProcessingItems')){

switch (processId) {

で期待する動作になりました！！
