### ISSUE TITLE
Descriptionに変数フィルターが効かない

### ISSUE THREAD

**Issue by jdai-master** [Implem/Implem.Pleasanter#567]
分類項目のない値だけのClassAで別のテーブルのDescriptionをフィルターしたら何も反応がありません。
以下の、記載のミスがありますか？
{
  "SiteId": 12345,
  "View": {
    "ColumnFilterExpressions": {
      "DescriptionA": "[ClassA]"
    }
  }
}

以下の表記も同じでした。
      "DescriptionA": "[@ClassA]"
      "DescriptionA": "=[@ClassA]"

一方、固定値なら反応します。
      "DescriptionA": "[\"りんご\"]"

PeasanterVersion 1.4.5.0

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

頂いた内容は下記の機能の質問と推測して回答を差し上げます。
テーブルの管理：エディタ：項目の詳細設定：選択肢一覧：フィルタ（選択肢一覧を他の項目の値で絞り込む） | Pleasanter
https://pleasanter.org/ja/manual/table-management-choice-json-column-filter-expressions

こちらで確認してみたのですが動いているように見受けられます。こちらで実験に使用したサイトパッケージを添付いたしますので認識に違いが無いかご確認頂ければと思います。
サイトパッケージの使い方は各画面の「ガイド(画面上部にある記載)」に操作の説明があります。
[#567_Descriptionに変数フィルターが効かない_2024_09_09 16_00_50.json](https://github.com/user-attachments/files/16926712/567_Description._2024_09_09.16_00_50.json)


あと、お手数をおかけする事となり申し訳ございませんが、Issue起票時には下記を含めて頂けると大変助かります。
※）全てではなく可能な限りで構いません
・再現するサイトパッケージの添付
・参考にしたWEBページがあるならそのURL
・期待した動作と実際の動作の差異の説明
・問題が発生する再現手順
・プリザンターのバージョン（DBが怪し場合はSQLServer/PostgreSQLやOS等やブラウザ名や各バージョン等）

プリザンターは多機能で指摘内容の特定が速く出来るようにご協力いただけますと嬉しです。

**Comment by jdai-master** [comment]
調査ありがとうございます。
いただいたサイトパッケージは分類Cに入れた内容で分類Dがフィルターされる仕様ですね。
これで確認したところ、分類Cに半角の「1」や「A」などを入力すると絞り込まれて分類Dに表示されますが、
「分類」や「類」など漢字文字を入れると検索しません。
お手数ですが、再度ご確認お願いいたします。
よろしくお願いします。

**Comment by nagamune-implem** [comment]
返信ありがとうございます。
ちなみにDBサーバはSQLServer/PostgreSQLのどちらを使用していて、WebサーバのOSとDBサーバのOSは何を使用していますでしょうか？
私の確認した環境(WIndows11＋SQLServer)では漢字も問題なく検索できました。
一部のPostgreSQLでは検索で日本語はうまく行かない場合があるとの報告もあり、他の原因も考えられるものが無いか調べたいと考えております。

**Comment by jdai-master** [comment]
PleasanterのWEBサーバ：Windows11
DBサーバ：Windows2016 DataCenter
SQLServer Standard： Ver14.0.1000.169
照合順序：Japanese_90_CI_AS_KS
です。

**Comment by nagamune-implem** [comment]
返信ありがとうございます。

またDB等の動作環境の情報ありがとうございます。
DB関係も問題なさそうな気がします。

お手数をおかけして申し訳ございませんが、いま一度手順の確認をさせて頂きたくご協力のほどよろしくお願いします。

1, 添付のサイトパッケージをインポート
1. 「記憶テーブル」一覧画面に遷移
1. 「新規（レコード作成）」ボタン押下
1. 「分類C」カラムに"**説明**"文字列入力  （★ここは"**分類**"ではなく"**説明**"と入力しているかご確認ください）
1. 「分類D」カラム押下しプルダウン表示
　→ 「分類A-001」「分類A-002」「分類A-003」が選択肢として表示される。

以上、よろしくお願いいたします。

**Comment by jdai-master** [comment]
その通りになりました。
「説明」といれると３つとも表示され、
「分」や「類」や「分類」といれると１つもなく、
「3」といれる「分類A-003」だけが表示されます。

**Comment by nagamune-implem** [comment]
ご確認ありがとうございます、お手数をおかけしました。

また説明が不足しており申し訳ございません。

説明いたします。
1. 「参照先」テーブルの一覧画面をご覧ください。
　「説明A」カラムには「説明A-00*」が格納されております。
　「タイトル」カラムには「分類A-00*」が格納されております。
2. 「記録テーブル」テーブルの「分類D」カラムの設定を意味を説明いたします。
  ```
  [
    {
      "SiteId": 7027, ★「参照先」テーブルのSiteID
      "View": {
        "ColumnFilterExpressions": {
          "DescriptionA" ★「参照先」テーブル「説明A」カラムの内容に対し
  		: 
  		'[ClassC]' ★現レコードの「分類C」カラムの値で検索を行う。
        }
      }
    }
  ]
  ```
3. 現レコードの画面では「分類D」カラムは「参照先」テーブルの「タイトル(分類A-00*等)」が表示されます。

従いまして、「Descriptionに変数フィルターが効かない」は動作していると認識しています。

私の認識に間違いがございます場合はお手数をおかけして大変申し訳ございませんが、その内容を記載した返信を頂きたくよろしくお願いいたします。

**Comment by jdai-master** [comment]
大変失礼しました、その通り機能しています。
私のサイトでは、+アルファの余計な指示を追加していました。
それを取り除くと希望どうり動きました。

それは以下の指示でした。
これがなくても、文章のどこにキーワードがあってもヒットするようです。
これはどういうとき使うのでしょう？

      ColumnFilterSearchTypes:{
          "DescriptionA":"PartialMatchMultiple"
      },

**Comment by nagamune-implem** [comment]
@jdai-master
返信ありがとうございます。

> これがなくても、文章のどこにキーワードがあってもヒットするようです。
これはどういうとき使うのでしょう？
```json
  ColumnFilterSearchTypes:{
      "DescriptionA":"PartialMatchMultiple"
  },
```

「PartialMatchMultiple」等のキーワードは分類項目での使用を想定しており説明項目での使用は想定していません。
詳細に関しては、まずは下記マニュアルをご参考にして頂ければと思います。

開発者向け機能：サーバスクリプト：view.SearchTypes | Pleasanter
https://pleasanter.org/ja/manual/server-script-view-search-types

**Comment by jdai-master** [comment]
ありがとうございました
