### ISSUE TITLE
SendGrid利用でのメール送信について

### ISSUE THREAD

**Issue by fealart** [Implem/Implem.Pleasanter#568]
smtpサーバにsmtp.sendgrid.netを指定する場合　かつ　２５番ポートがブロックされている環境で
Sendgridとの通信が上手くいかない。

４８７ポート、５８７ポートは開放しているのでそちらを指定したいが、指定不要となっているためどうやればいいかわからない。
sendgrid扱いではなく通常のsmtpサーバと同じように指定する方法はないでしょうか

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

内容を確認いたしますので、しばらくお待ち頂きたくよろしくお願いいたします。

**Comment by pmc-ko** [comment]
SendGridですが、SendGridのライブラリを使って送信するかどうかの判定に、Hostの設定がsmtp.sendgrid.netであるかどうかを見て判定しています。

そこのロジックを追いかけてみたのですが、

```
var client = new SendGridClient(Parameters.Mail.SmtpPassword);
var response = await client.SendEmailAsync(msg).ConfigureAwait(false);
```

と、ライブラリをコールしています。

こちらのライブラリの送信部分のコードは下記で参照できるのですが、
https://github.com/sendgrid/sendgrid-csharp/blob/main/src/SendGrid/BaseClient.cs
これを見る限りはSMTPではなくHTTPでのAPIで送信しているようです。

```
public async Task<Response> SendEmailAsync(SendGridMessage msg, CancellationToken cancellationToken = default(CancellationToken))
{
    return await this.RequestAsync(
        Method.POST,
        msg.Serialize(),
        urlPath: "mail/send",
        cancellationToken: cancellationToken).ConfigureAwait(false);
}
```

なので、本来であればSMTPの25番がブロックされていたとしても問題ないとは思うのですが・・・。
当方でも25番がブロックされている環境でSendGridを使用していますが、問題にはなっていないです。

**Comment by fealart** [comment]
情報ありがとうございます。
HTTP通信ということはSMTP RelayではなくWebAPI側でSendGridを登録しないとダメそうですね。
80番の解放とWebAPIの作成で上手く行くか試してみます。

**Comment by fealart** [comment]
80番の解放とWebAPIの作成で上手く行きました。
