### ISSUE TITLE
標準カレンダの不具合

### ISSUE THREAD

**Issue by nozoe** [Implem/Implem.Pleasanter#569]
pleasanter の標準カレンダを使っていますが、幾つか不具合があるようなので報告しておきます。
弊社の環境は、
Server: Windows Server 2022
Database: SQL Server 2022
Pleasanter: Version 1.4.7.2

Client は、EdgeでもChrome でも変わりませんでした。

1. カレンダの月表示をした場合、そのカレンダに表示される最初の日(前月の最終月曜日)にその前日の情報が表示される。
今回のテストデータには、それぞれの日に期限1日のデータが全ての日に登録されています。
(本来はメンバ全員分が登録される予定)

![image](https://github.com/user-attachments/assets/4f97871f-9a61-4a27-b261-341bfaca1d1a)

3. カレンダの表示状態から歯車マークをクリックした場合、後ろにあるカレンダの表示が重なって表示される。
![image](https://github.com/user-attachments/assets/d6631be4-e780-4f76-8146-919ea4319395)

4. カレンダに大量に項目がある場合に、縦スクロールした場合に曜日タイトルと重なって表示される。
![image](https://github.com/user-attachments/assets/22067caa-a885-497e-ab9e-4b74911fe92c)

2,3 はCSSで透過率を変える事でなんとかならないかとちょっと試しましたが、現時点では成功していません。

念の為、今回検証用に作成したサイトのエクスポートデータを添付しておきます。
[標準カレンダ不具合検証.json](https://github.com/user-attachments/files/16938179/default.json)

よろしくお願いします。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

またサイトパッケージや動作環境の情報を頂き感謝いたします。
内容を確認いたしますので、しばらくお待ち頂きたくよろしくお願いいたします。

**Comment by nagamune-implem** [comment]
一部確認いたしました。

1. カレンダの月表示をした場合、そのカレンダに表示される最初の日(前月の最終月曜日)にその前日の情報が表示される。
　→ 不具合だと思われます、さらに調査いたします。

2. 「2.」自体が見当たりません。
　→ 多分3にずれていると思われます。

3. バージョン1.4.8.0で修正されております。

4. バージョン1.4.8.0で修正されております。

1.に関しては今しばらくお待ち頂きたくよろしくお願いいたします。

**Comment by nozoe** [comment]
何度か編集している内に番号が飛んでしまったようです。
3,4　に関して1.4.8.0 以降で修正されている事確認いたしました。
修正履歴になかったので次のリリースで修正されるかなぁと思っていましたが、1.4.8.1 にバージョンアップした
際になんか雰囲気が違うなぁとは思っていました。

引き続き1が修正されるのをお待ちします。

ただ、1.4.8.1 にしたら標準カレンダが重くなった様に感じるのは気の性でしょうか？
