### ISSUE TITLE
新規追加したレコードがフルテキスト検索の対象にならない？

### ISSUE THREAD

**Issue by kudarisenmon** [Implem/Implem.Pleasanter#57]
新規に追加したレコードがフルテキスト検索の対象にならなくなってしまいました。
同じテーブルの既存のレコードはフルテキスト検索の対象になっています。
SQL Serverは「SQL Server 2014 Express with Advanced Services」です。

公開された最初のバージョンから0.46.56.12125にバージョンアップしてから起きているよう？です。
バージョンアップはwikiページに従って実行し、「.\Parameters\Search.json」は事前にバックアップを取り元の状態にもどしました。
https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%97%E3%83%AA%E3%82%B6%E3%83%B3%E3%82%BF%E3%83%BC%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97

一度フルテキスト検索を無効にして、SQL Serverの2つのテーブルからインデックスを削除して最初から以下の手順を実施したところ、その時点でのすべてのレコードは対象になりましたが、以降に追加されたレコードはやはり対象外です。
https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%97%E3%83%AA%E3%82%B6%E3%83%B3%E3%82%BF%E3%83%BC%E3%81%AE%E3%83%95%E3%83%AB%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E6%A4%9C%E7%B4%A2%E6%A9%9F%E8%83%BD%E3%82%92%E6%9C%89%E5%8A%B9%E5%8C%96%E3%81%99%E3%82%8B

どこを調べたら解決のヒントがありますか？

**Comment by Implem** [comment]
Issueありがとうございます。プリザンターのフルテキスト検索は、ItemsテーブルのFullTextカラムに入っているキーワードで検索を行います。そのため、まずFullTextカラムに目的の語がはいっているか確認してみてください。入っていない場合は、Search.jsonの設定が有効化されていない可能性があります。Search.json等の設定ファイルは変更後にIISの再起動が必要です。

上記が入っていれば、次にSQL Serverがどのようにインデックスを作成しているか確認する方法があります。下記のSQLを実行してみてください。

SELECT * FROM sys.dm_fts_index_population
SELECT * FROM sys.dm_fts_index_keywords( DB_ID(), OBJECT_ID('items'))
SELECT * FROM sys.dm_fts_index_keywords_by_document ( DB_ID(), OBJECT_ID('items'))

語によっては意図しない位置でワードブレイクされることがあります。
解決のヒントになれば幸いです。
