### ISSUE TITLE
Kestrelでプリザンターを動作させる場合の同時接続パフォーマンスがとても悪い

### ISSUE THREAD

**Issue by yohshiro-711** [Implem/Implem.Pleasanter#571]
Kestrelにプリザンターをデプロイしたときの同時接続パフォーマンスがとても悪いです。
恐らくコントローラーのアクションメソッドが同期実装になっていることが原因と思わえれますが、
10人程度でプリザンターを操作しているだけでも応答が返ってくるのがとても遅いことが多々発生します。
※IISだとこの問題は発生していません。

現在はこの問題を回避するために `Implem.Pleasanter.runtimeconfig.json` を以下のように変更して
最小スレッド数を大きく設定しています。
```
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "8.0.0"
      }
    ],
    "configProperties": {
      "System.GC.Server": true,
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false,
      "System.Threading.ThreadPool.MinThreads": 50
    }
  }
}
```

これで同時接続のパフォーマンス問題は解消されますが、マニュアルにない設定を変更しているため
最小スレッド数を調整できるように設定ファイルの追加を検討していただけないでしょうか。

念のため検証した内容を記載いたいしますが、実際の本番環境はLinuxでプリザンターを動作させていますが、
検証はWindowsで実施し、同一のマシン上でKestrelで動作させたパターン、IISで動作させたパターンで確認しています。

Kestrelに20リクエストを同時にPOSTしたときに
dotnet-countersでスレッドの生成の流れを見る限り、
約500ms間隔で1つずつスレッドが生成されております。
※Kestrelの場合、キューに入った時点でアイドルスレッドは選択されないようです

IISの場合はアイドルになったスレッドがそのまま使いまわされているため
同時接続の応答パフォーマンスは問題がないことを確認しています。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

詳細な調査情報を頂き感謝いたします。
内容を確認いたしますので、しばらくお待ち頂きたくよろしくお願いいたします。
