### ISSUE TITLE
SUMIF関数を実現したい。

### ISSUE THREAD

**Issue by elevator8** [Implem/Implem.Pleasanter#573]
以下、親テーブルAと子テーブルBリンクさせ

テーブルAの在庫移動数量を表示(テーブルBから参照)させたいとき
移動元店舗からの移動数(在庫減算)はサマリ・ルックアップで反映出来たが

移動先への移動数(在庫加算)をうまく反映することが出来ず躓いています。
(サーバスクリプト：ColumnFilterHashでテーブルBの果物・移動先店舗を絞り込み、
一意のレコードを参照して値を反映出来ないか模索しています)
お知恵をお借り出来ないでしょうか。

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/10914/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/10914/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

テーブルA:在庫一覧
果物 | 店舗名 | 初期在庫 | 移動数量 | 最終在庫
-- | -- | -- | -- | --
りんご | A | 10 | -10 | 0
りんご | B | 20 | 15 | 35
りんご | C | 30 | -5 | 30

</body>

</html>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/10914/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/10914/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

テーブルB：在庫移動
果物 | 移動元店舗 | 移動先店舗 | 移動数
-- | -- | -- | --
りんご | A | B | 5
りんご | A | C | 5
りんご | C | B | 10

</body>

</html>

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

内容を確認いたしますので、しばらくお待ち頂きたくお願いいたします。
もし簡単に構成するサイトパッケージを頂けますと認識の理解が早まる場合がございますので、お手数をおかけして申し訳ございませんが、誤用いただけないかご検討宜しくお願い致します。
