### ISSUE TITLE
リマインダ設定の「範囲」と「条件」の組合せ条件について

### ISSUE THREAD

**Issue by fr-sudachi** [Implem/Implem.Pleasanter#575]
リマインダ設定の「範囲」と「条件」の組合せ条件について、マニュアルに記載が無かったため質問させていただきます。  

リマインダを、DateAを基準に1レコードにつき3回送りたいと考えています。  

- DateAの値が今日から1か月後
- DateAの値が今日から1週間後
- DateAの値が明日

DateAの値はレコードごとにバラバラのため、リマインダの起動間隔を`日`に設定し、範囲は、それぞれ`31`、`7`、`2`とします。  
上記の設定だけでは日付が範囲内に入ると毎日リマインダが送信されてしまうため、  
サーバースクリプトと組み合わせてビューを作成し、リマインダの条件として指定すればよいのではないかと考えました。  
（リマインダ設定は合計3つになります）

しかし実際に試してみたところ、ビュー絞込範囲外であるはずの、`DateA=6日後`のレコードのリマインダが送信されてしまいました。

リマインダ設定の「範囲」と「条件」では、「範囲」の方が優先になるのでしょうか。
あるいは「範囲」と「条件」はOR条件となるのでしょうか。
または、リマインダ実行時は、サーバースクリプトが動かないのでしょうか。

上記の動作バージョンは、1.4.7.2です。

**Comment by pierre3** [comment]
Issueありがとうございます。

リマインダ実行時にはサーバスクリプトは動作いたしません。

また、現在のリマインダの機能では、特定のタイミングのみリマインダを送信することはできません。
ご期待に沿えず申し訳ございません。今後の課題として検討させていただきます。

**Comment by fr-sudachi** [comment]
ご返信ありがとうございます。  
リマインダ実行時にはサーバスクリプトが動作しないこと承知しました。

**Comment by pierre3** [comment]
ありがとうございます。引き続きよろしくお願いいたします。
