### ISSUE TITLE
columnsオブジェクトのExtendedCellCssについて、一覧の説明項目に設定するとセルの内容が表示されなくなります。

### ISSUE THREAD

**Issue by hp-240** [Implem/Implem.Pleasanter#576]
#### 現象
サーバースクリプト「行表示の前」において、
Description項目にたいしてcolumnsオブジェクトのExtendedCellCssを指定したところ、セルの内容がクリアーされてしまいました。

※ 数値項目や分類項目では、このようなことはありませんでした。
※ バージョンは 1.4.8.0 です。

ご確認いただけますと大変助かります。

#### 記述内容
````
if (model.CheckE) columns.DescriptionZ.ExtendedCellCss = "web140-royalblue";
````

#### 実行結果（該当セルの状態）
````
<td></td>
````

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

こちらで「バージョンは 1.4.8.0 」で確認しましたが、再現できませんでした。
こちらで確認したサイトパッケージを添付いたしますので認識に違いが無いかご確認頂ければと思います。
サイトパッケージのガイドに説明の記載がございます。
[#576_columnsオブジェクトのExtendedCellCssについて、一覧の説明項目に設定するとセルの内容が表示されなくなります.json](https://github.com/user-attachments/files/17158775/576_columns.ExtendedCellCss.json)

お手数をおかけして申し訳ございませんが、よろしくお願いいたします。

**Comment by hp-240** [comment]
お忙しい中、確認いただきましてありがとうございました。
報告した内容が正確ではありませんでした。大変申し訳ありません。

事象としましては、
エディタで「非表示」に設定した項目にサーバスクリプト（作成前、更新前）で値をセットした後、サーバスクリプト（行表示の前）でExtendedCellCssを指定すると、セル内容が表示されなくなります。
説明項目だけでなく、分類項目や日付項目でも同じ事象となりました。

変更したサイトパッケージを添付させていただきました。
お手数をおかけいたしますが、ご確認いただけますと幸いです。

[#576_columnsオブジェクトのExtendedCellCssについて、一覧の説明項目に設定するとセルの内容が表示されなくなります（返信）_2024_09_28 22_20_51.json](https://github.com/user-attachments/files/17174529/576_columns.ExtendedCellCss._2024_09_28.22_20_51.json)

**Comment by nagamune-implem** [comment]
ご回答ありがとうございます。

ご指摘頂いた内容をこちらでも確認いたしました。
不具合と思いますので修正する方向で進めたいと思います。
ご不便をおかけして申し訳ございませんが、もうしばらくお待ち頂きたくよろしくお願いいたします。

**Comment by hp-240** [comment]
ご確認いただきありがとうございました。
また、修正いただける方向とのことで感謝いたします。

もともと報告を目的としておりましたので、これでクローズさせていただきます。
今後とも、どうぞよろしくお願いいたします。
