### ISSUE TITLE
LDAPのグループ検索用のSearchRootの追加してほしい。

### ISSUE THREAD

**Issue by hagkoh** [Implem/Implem.Pleasanter#578]
### 現象
AD環境のLDAP連携時にグループを検索するSearchRootを追加してほしい。

1. LdapSearchRootに設定したベースDNにユーザーを格納している。
2. 連携したいグループを格納しているOUがLdapSearchRootに設定したベースＤＮの外にある。

ルート：
┗OU：U_ユーザー　←現在は、ここをLdapSearchRootにしている。
┗OU：G_グループ　←そのため、ここを検索できない。

LdapSearchRootをルートにするとOUでの検索がAD環境下ではできない？

### 実現したいこと
上記の現象のため、グループを検索するベースDNを設定することで、グループ連携することができる。
また、グループもLdapExtendedAttributesような拡張項目を設定できるようになってほしい。

**Comment by nagamune-implem** [comment]
Issueありがとうございます。
また、分かりやすい内容の記載ありがとうございます。

●その１
◎指摘
・グループ用のLdapSearchRootが欲しい
◎回答
・LdapExtendedAttributesには複数個の指定ができます。
そこで、ユーザ用とグループ用の２つを記載する事で実現できないかお試しいただけませんでしょうか？

```json
"LdapExtendedAttributes": [
    {
		★ユーザ用の記載
        "Name": "DisplayName_User",
        "Pattern": null,
        "ColumnName": "DescriptionE"
    },
    {
		★グループ用の記載
        "Name": "DisplayName_Group",
        "Pattern": null,
        "ColumnName": "DescriptionE"
    },
]
```
パラメータ設定：Authentication.json | Pleasanter
https://pleasanter.org/ja/manual/authentication-json


●その２
◎指摘
・グループもLdapExtendedAttributesような拡張項目を設定できるようになってほしい。
◎回答
・実装する方向で検討を進めたいと思います。

以上、ありがとうございました。

**Comment by hagkoh** [comment]
@nagamune-implem 

> ●その１ ◎指摘 ・グループ用のLdapSearchRootが欲しい ◎回答 ・LdapExtendedAttributesには複数個の指定ができます。 

LdapExtendedAttributesは、拡張項目なので検索するベースDNに指定ではないので、こちらの要望とは異なるかと思われます。

Issueの続きですが、こちら環境ですと、
`"LdapSearchRoot": "LDAP://{サーバー名}/OU={取り込みたいユーザーOU},DC={dc},DC=local"`
としてしまっていると、グループが別のOUに入っているため、検索対象から漏れてしまいます。

`"LdapSearchRoot": "LDAP://{サーバー名}/DC={dc},DC=local"`
ベースDNを一階層上にしていると、グループが格納されているOUも含めて検索は可能にはなりますが、連携したいOU以外も対象になってしまいます。

※LdapSyncPatternsを以下のように指定しても連携したいOU以外も取得されてしまう。
```(&(objectCategory=person)(objectClass=user)(EmployeeID=*)(Department=*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))```
LdapSyncGroupPatternsも同様に取り込みたいOU以外も取り込んでしまう。
ou:dn:=の指定ができないから？

そのため、LdapSearchRootがグループ用にもう一つが指定できるとありがたいです。
```
例：
LdapGroupSearchRoot": "LDAP://{サーバー名}/OU={取り込みたいグループOU},DC={dc},DC=local
```
Groups_LdapSearchRoot.jsonがあるようなのでグループのSearchRootも想定されていたのでしょうか。

> ●その２ ◎指摘 ・グループもLdapExtendedAttributesような拡張項目を設定できるようになってほしい。 ◎回答 ・実装する方向で検討を進めたいと思います。
> 
ありがとうございます。
ご検討よろしくお願いいたします。

**Comment by nagamune-implem** [comment]
@hagkoh
記載を間違いました申し訳ございません。
LdapExtendedAttributes ではなく LdapParameters です。

LdapParametersにjsonのオブジェクトを2つ記載し、LdapSearchRootをそれぞれ指定すると意図通りになりませんでしょうか？
お手数をおかけして申し訳ございませんが、ご確認のほどよろしくお願いいたします。

```json
{
    "LdapParameters": [
        {
		★ユーザ用
            "LdapSearchRoot": null,
		// 略
        },
        {
		★グループ用
            "LdapSearchRoot": null,
		// 略
        }
    ]
}
```

**Comment by hagkoh** [comment]
@nagamune-implem 

> LdapExtendedAttributes ではなく LdapParameters です。

確かに複数台サーバとして考えればよかったんですね。
ユーザーを取得、グループの取得をLdapParametersを分ける方法で実装が出来そうです。
パラメータ設定の認識不足でお手数をお掛けしました。
ありがとうございました。

引き続き、`グループもLdapExtendedAttributesような拡張項目の追加`の件は、ご検討よろしくお願いいたします。
