### ISSUE TITLE
一覧画面上のコメントがおかしい

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#58]
一覧画面上で、ログインユーザー(自分)が記載したコメントがレコードに関係なく全て同じ内容が表示される。
異なるサイト間では発生せず、同一のサイト内でのみ発生する。

0.46.84.21821

**Comment by kazuca** [comment]
現象が発生するコメントと発生しないコメントが存在するようです。
アップデート時にImplem.CodeDefinerを実行した場合、
・実行前→ログインユーザ自身のコメントが同一サイト内の自身のコメントに表示される(indexのみでeditは正常)
・実行後のコメントが最新→再現せず

この他にも、作成した通知が編集できなくなる(削除後再作成はできる)など、アップデートを起因としてなんらかの現象が起きているようです。

**Comment by kazuca** [comment]
いろいろ操作していたところ、原因となるモノを見つけました。
コメントの編集を許可するとしていた場合のみ発生するようです。

**Comment by Implem** [comment]
Issueありがとうございます。コメントの件、再現できたので修正しました！

**Comment by kazuca** [comment]
ご対応ありがとうございます。
