### ISSUE TITLE
テンプレートから作成した、件名や顧客名に、関係しないSiteIDの選択用の吹き出し情報が表示されてしまいます

### ISSUE THREAD

**Issue by gltomix** [Implem/Implem.Pleasanter#580]
Windows10で、Community Edition の 1.9.4.2 を利用しています.
テンプレートの商談管理や、注文管理を新規に作成して、データを入れようとした際に、
件名や、顧客名に、項目の設定としていない、
サイトID＝１の情報が、選択として吹き出し表示されてしまいます。
Chrome で発生しており、Edgeでは発生していません。
この選択の吹き出しを消すことは可能でしょうか。
よろしくお願いいたします。

**Comment by pierre3** [comment]
Issueありがとうございます。

入力候補を吹き出しで表示する機能につきましては、ブラウザ（Chrome）の機能となります。
ブラウザのマニュアル等をご確認の上、無効化するなどの対応をお願いいたします。

**Comment by gltomix** [comment]
返信ありがとうございます。確かにブラウザ(Chrome)で無効化できました。お手数をおかけしました。
すばらしいソフトウェアありがとうございます。さらに使いこなしていきたいと思います。
