### ISSUE TITLE
子から親にデータを更新する時はapiUpdateを使う 　　

### ISSUE THREAD

**Issue by ObisanHT** [Implem/Implem.Pleasanter#582]
こんにちわ

Pleasanterユーザマニュアル「API機能」
についてお聞きしたいことがあります。
既出かと思い　検索したのですがうまく探せませんでした。
既出URLがあれば　ご教示いただけると幸いです。

状況：
子テーブル　営業日報　サイトID　184　リンク項目「ClassA」　　項目　案件状態「ClassB」と
親テーブル　案件　　　サイトID　199　項目　案件状態「ClassC」は　属性の内容は　最新営業日報
にて　案件状態を　常に更新
　子テーブル.営業日報.案件状態　⇒　親テーブル.案件.案件状態
したいのですが　うまく　apiupdate　スクリプトが
子テーブルに作成できません。
具体的な　サンプルがあればご教示ください。
よろしくお願いします。

**Comment by ObisanHT** [comment]
問合せしたものです。
様々なサイトを　拝見して　子テーブル　スクリプトに
出力先　新規作成・編集　を選択して
下記　スクリプトを作成　したところ　エラーは表示されないのですが
　親テーブル　案件　　　サイトID　199　項目　案件状態「ClassC」
更新されません。
記述が誤っていますでしょうか。

$p.events.after_send_Update = function (args) {
    // 対象となるサイトのID
    var hogeId = "199";

    // 対象となるレコードを全て取得し update する
    var getJson =
    {
        'id' : hogeId,
        'data' : {
            // 対象のテーブルに対して更新する権限を持つ APIKEY を利用する
            "ApiKey": "ca6cbf6・・・・・・",
            "View": {
                "ColumnFilterHash": {
                        // 「$p.id()」は現状更新しているレコードの ID を指す
                        // （レコードの ID はキーとなるものを指す）
                        "ClassA": $p.id(),
                    }
                }
            },
        'done' : function(data) {
            if (data.StatusCode == 200 && data.Response.Data.length > 0) {
                for(var i in data.Response.Data) {
                    // ColumnFilterHash 対策（部分一致のみな為）
                    if($p.id() == data.Response.Data[i].ClassA) {
                        var updateJson =
                        {
                            'id' : data.Response.Data[i].ResultId,
                            'data' : {
                                    "ClassC": $("#Results_ClassB").val(),   // 更新したいデータ1（一例）
                            },
                            'done' : function(data){
                                if (data.StatusCode == 200){
                                    // 処理なし
                                }
                            },
                            'fail' : function(){
                                alert("API Failed1 : hogehoge（update）");
                            }
                        }
                        $p.apiUpdate(updateJson);
                    }
                }
            }
        },
        'fail' : function(){
            $("body").css({ visibility: "visible" });
            alert("API Failed2 : hogehoge（select）");
        }
    }
    $p.apiGet(getJson);
}

**Comment by nagamune-implem** [comment]
Issueありがとうございます。

内容を確認いたしました。
記載頂いたコードに一部不備がありました、下記の様に書き換えると動くと思います。

●その１
修正後：
```	$p.id() == data.Response.Data[i].ClassHash.ClassA ```
修正前：
```	$p.id() == data.Response.Data[i].ClassA ```

●その２
修正後：
```
	'data' : {
		'ClassHash' : {
			"ClassC": $("#Results_ClassB").val(),   // 更新したいデータ1（一例）
		}
	},
```
修正前：
```
	'data' : {
			"ClassC": $("#Results_ClassB").val(),   // 更新したいデータ1（一例）
	},
```

また、apiに記載するjsonにはバージョンがあり、本記載方法は'ApiVersion': 1.1での記載方法となります。

動作を模倣したサイトパッケージも添付いたします。何かの参考になれば幸いです。
[p#582_sample_sitepackage.json](https://github.com/user-attachments/files/17856053/p.582_sample_sitepackage.json)
※）「データも含めて」インポートをしてください。

**Comment by nagamune-implem** [comment]
ご回答ご確認ありがとうございます。

> 子テーブル情報　から　親テーブル情報　への更新

上記に関しても特にやり方は変わりません。

javascriptとして「レコードを取得する」「レコードを更新する」等の基本的なパーツを提供しております。これら基本パーツを組み合わせる事で、頂いた課題は解決できるように思われます。

子テーブルにスクリプトを入れたサイトパッケージを添付いたします。何かの参考になれば幸いです。
[p#582_sample_sitepackage@2.json](https://github.com/user-attachments/files/17865789/p.582_sample_sitepackage%402.json)

**Comment by ObisanHT** [comment]
ご返信　ありがとうございます。
動作を模倣したサイトパッケージについて
p#582_sample_sitepackage@2.json

を参考に解決いたしました。
本当にありがとうございます。
初　Pleasanter
初　Javaスクリプト
と分からない事ばかりではありますが、
先達の方々が実践されているであろう　事柄について
検証していきたいと思います。
ありがとうございました。　Closeとさせて頂きます。

**Comment by ObisanHT** [comment]
ご回答ありがとうございます。

まだまだ　社内動作検証用ですので　精度を上げる部分はこれからとなっております。
変数定義自体がWeb参照のままであったりしますので。
承知いたしました。
今後ともよろしくお願いいたします。
