### ISSUE TITLE
既に継承されているサイトは継承の設定を変更できません。

### ISSUE THREAD

**Issue by kenichi-fk** [Implem/Implem.Pleasanter#583]
サイトの「アクセス権の継承」を   "アクセス権を継承する"  としたテスト環境から、サイトパッケージをエクスポートして、本番環境の同階層にインポートしました。（サイトのアクセス権の継承を有効にして）
すると本番環境では、設定済みの「アクセス権の継承」が  "アクセス権を継承しない"  になっていました。
そこで、「アクセス権の継承」を変更しようとしたら、「既に継承されているサイトは継承の設定を変更できません。」というエラーメッセージが出て、何を選んでも「アクセス権を継承しない」以外に変更できません。

試しに、サイトの「アクセス権の継承」を "アクセス権を継承しない" にしたテスト環境から同じ方法でインポートしたところ、こちらでも上記エラーが発生します。

サイトパッケージを他環境にインポートしたときに、サイトのアクセス権を継承したいのですが、どうしたらできますでしょうか？

**Comment by pierre3** [comment]
Issueありがとうございます。

調査いたしますので、可能でしたらサイトパッケージをご提供いただけますでしょうか。
