### ISSUE TITLE
サイトパッケージのインポートで

### ISSUE THREAD

**Issue by gltomix** [Implem/Implem.Pleasanter#584]
サイトパッケージのインポートで、なにもファイルを選択せずに、
インポートを押下すると、更新中のカーソルがぐるぐる回り続けます。

**Comment by pierre3** [comment]
Issueありがとうございます。

本件、不具合として認識しており現在対応中です。
修正版をリリースしましたらご連絡いたします。

**Comment by gltomix** [comment]
対応ありがとうございました
