### ISSUE TITLE
作成ボタンをクリックした時にイベントを実行したい

### ISSUE THREAD

**Issue by Obisan-YK** [Implem/Implem.Pleasanter#589]
お世話になっております。
新規作成　→　作成を押した際に入力した数値の大小チェックを行い、それに伴いメッセージを表示したいのですが
下記のコードではイベントが実行されません。
作成ボタンのidはCreateCommandとなっており、data-action="Create"となっております。
コードの書式に問題があるのでしょうか？

// ボタンがクリックされたときにメッセージを表示
//$('[data-action="Create"]').on('click', function (e) {
$('#CreateCommand').on('click', function () {
//$(document).on('click', '[data-action="Create"]', function (e) {
//$(document).on('click',  '#' + $p.getControl('CreateCommand').id,function (e) {
//$(document).on('click', '#CreateCommand', function () {
//$(document).on('click', '[data-action="Create"]', function () {
    var numA = $("#Results_NumA").val();
    var numB = $("#Results_NumB").val();

    var num01 = parseInt(numA);
    var num02 = parseInt(numB);

    // 条件をチェックしてメッセージを表示
    if (num01 > num02) {
        $p.setMessage('#Message', JSON.stringify({
            Css: 'alert-warning',
            Text: '始業時kmよりも入力距離数が低いです。'
        }));
        console.log('始業時kmよりも入力距離数が低いです。');
    } else {
        console.log('条件は正しいです。');
    }
});

何卒、ご教授いただければと思います。

**Comment by implem-taguchi** [comment]
ご要望は「作成ボタンをクリックした際に独自の入力検証を行いたい」と推察します。
ご要望をスクリプトで実現する場合は、以下の「$p.events.after_validate」をご利用いただくと実現できます。

開発者向け機能：スクリプト：$p.events.after_validate | Pleasanter
https://pleasanter.org/ja/manual/script-events-after-validate

**Comment by Obisan-YK** [comment]
$p.events.after_validateを利用することで再現できました。
ありがとうございます。
