### ISSUE TITLE
「コピー」「一括移動」ボタンの利用可否設定

### ISSUE THREAD

**Issue by takaoyama** [Implem/Implem.Pleasanter#59]
お世話になっております。

エディタ画面下部のコピーと一括移動ボタンですが
利用を制限するようにできますでしょうか。

レコードをコピーされたり、移動されると困るサイトがあり
制限ができるとありがたいです。

よろしくお願いいたします。

**Comment by Implem** [comment]
Issueありがとうございます。機能の制限、検討してみます。
