### ISSUE TITLE
APIで画像をPOSTできますか？

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#70]
いつもお世話になっております。

公開されているレコード作成のAPIで、画像をPOSTすることはできますでしょうか？
以下の機能がAPIから利用できるか、という意味です。
https://github.com/Implem/Implem.Pleasanter/wiki/%E5%85%B1%E9%80%9A%E6%A9%9F%E8%83%BD%EF%BC%9A%E7%94%BB%E5%83%8F

ご確認いただき、ご返信いただけますと幸いです。
以上、どうぞよろしくお願い致します。

**Comment by implem-ishizaki** [comment]
Issueありがとうございます。APIでは画像のPOSTには対応しておりません。機能追加のご希望があれば新しいIssueを頂ければと思います。
本Issueはクローズさせていただきます。
