### ISSUE TITLE
POST APIについて

### ISSUE THREAD

**Issue by yyuki23** [Implem/Implem.Pleasanter#71]
お世話になっております。

POST createのAPIを実行したところ、以下のようなresponseが得られました。
```
"result":{
	"statusCode":200,
	"body":{
		"Id":0,
		"StatusCode":500,
		"Message":"この操作を行うための権限がありません。"
	}
}
```
statusCodeが本当は500なのに200が返ってきているのはバグではないかと思うのですが、
そもそも「操作を行うための権限」とは何でしょうか？
API KeyをセットするだけでAPIは叩けるはずだと認識しているのですが。
ご教授いただけますと幸いです。

どうぞ、よろしくお願い致します。

**Comment by pierre3** [comment]
回答が遅くなり申し訳ございません。

StatusCodeにつきまして
a5e24ba45974776075ba131e5084dd9d8c30e164　にて追加いたしました新方式のAPIで、エラーの内容に一致したステータスコードを返却するように改善いたしました。

新しいAPIについては、以下をご確認ください。
https://blog.implem.co.jp/entry/2018/11/30/130642

また、「操作を行うための権限がありません」についてですが、
API Keyを作成したユーザーに、対象のサイトまたはレコードのアクセス権が付与されていない場合に、このようなエラーとなります。
