### ISSUE TITLE
ログインユーザーに合わせてサイトのフィルタを変更したい。

### ISSUE THREAD

**Issue by miyakeP** [Implem/Implem.Pleasanter#77]
ログインユーザーは自身が承認していない（自身の名前の無い）レコードを初期表示したいのですが、
ログインユーザーを識別して、ユーザーに合わせたフィルタ設定で表示を行う
といったことは可能でしょうか？
ビューのフィルタでは条件を指定できないようですし、設定してもユーザーが自身に合う
ビューを選択する操作が必要となってしまいます。

**Comment by Implem** [comment]
拡張SQLのOnSelectingWhereを使用してください。SQLで条件を指定することが可能です。
