### ISSUE TITLE
Windowsイベントビューアーへのログ出力について

### ISSUE THREAD

**Issue by koioya** [Implem/Implem.Pleasanter#78]
VirtualBOX上でPleasanterの評価を行っておりますが、
環境構築後からSQL Serverのログが多量に出力されております。
推奨スペックと比べメモリのみ3GBと満たしていない状態ですが、
スペックを満たしても同様にログが出力されるのか、お教え願います。

出力されているログは次のとおりで、
3種類1セットで出現し、最頻で1秒に1セットが出力されています。
_ソース：MSSQLSERVER
レベル：情報
タスクのカテゴリ：サーバー
　ID　　　メッセージ
　17137　データベース 'Implem.Pleasanter' を起動しています。
　49930　データベース 'Implem.Pleasnater' に対し、ワーカー プール サイズ [1]で並列再実行が started です。
　49930　データベース 'Implem.Pleasnater' に対し、ワーカー プール サイズ [1]で並列再実行が shutdown です。_

エラーや警告ではなく情報のレベルですが、あまりにも件数が多く、
他のログが埋もれることを懸念しております。

お手数ですがご回答のほどよろしくお願いいたします。

**Comment by yang-jiayi** [comment]
こんにちは。楊です。
VirtualBOXの環境に、何コアを割り当てましたか。
また、SQL Server 2016/2017は、x64 プロセッサでのみイントールできます。 X86 プロセッサではインストールできません。
その辺、SQL Serverのシステム要件を確認していただいたらいかがでしょうか。
https://www.jssug.jp

**Comment by koioya** [comment]
楊さん、回答ありがとうございます。
ご指摘の点を確認したところ、X86プロセッサで環境が構築されておりましたので、
すぐに使える環境(X64の1コア、メモリ2GB)で環境の再構築を行いました。
数時間放置した結果ですが、やはり同じようにログが出続けていますので、
SQL Serverのシステム要件が原因ではないようです。

ただ、環境構築にあたっては単純に64bit版のWindowsで良いと考えていたため、
SQL Serverのシステム要件は盲点でした。
一つ勉強になり、一つ問題の可能性をつぶすことができたこと、お礼申し上げます。

**Comment by koioya** [comment]
ここまでご覧いただいたみなさま、お手数ですがご利用の環境のスペックと、
イベントログの出力状況をお教えいただければ幸いです。

ログが膨大とは言え動いているので検証は進められます。
しかし検証が良好に終わり本格導入となった場合、
イベントログを自動で監視することとなり、膨大なログへの対処が求められます。
推奨スペックを満たした環境に導入できログが出なくなれば最善ですが、
やはりログが出てしまうのかどうかが気になっております。

お力お知恵までいかなくとも情報だけでもいただければ助かります。
よろしくお願いいたします。
![eventlog](https://user-images.githubusercontent.com/39517940/40695866-2c66167e-63fe-11e8-9cc5-cfeef87b4ee7.png)

**Comment by m-k-0123** [comment]
環境が違うので参考になるかわかりませんが・・・
windows7上にSQLServer2014をインストールしています。
そこそこの件数は出ているように思いますが
少なくとも「'Implem.Pleasanter' を起動しています。」
のログは単独で出ていますし、
「ワーカー プール サイズ [1]で並列再実行が ～」というログは１件も見当たりませんでした。
※OSのbitは64と32両方ありますが、いずれも同様でした。

**Comment by koioya** [comment]
m-k-0123さま
返信が遅くなり申し訳ございません。
「ワーカー プール サイズ～」のログが1件もないとのことなので、
他の環境がないか調整したり、OSなどプロダクトを変えるなど引き続き試行錯誤してみます。
情報を提供いただき、ありがとうございました。

**Comment by nonono321** [comment]
こんにちは。私も同じように毎日大量のログが出力される状態となりました。
※SQL Server 2017を使用しています

それで、SQL ServerのPleasanterデータベースのパラメータで「AUTO_CLOSE」をfalseにしたところ、事象が解消されました。
SQL Serverの使い方に詳しくは無いため、この対処で問題が無いかは不明ですが、ご参考ください。

**Comment by koioya** [comment]
nonono321さま
返信が遅くなり申し訳ございません。
当方の環境でも「AUTO_CLOSE」をfalseにするとログが出力されないことを確認いたしました。
この対応で何か問題があるかは当方にもわかりませんが、
ひとまず情報を提供いただいたこと、お礼申し上げます。
ご助言ありがとうございました。

**Comment by koioya** [comment]
つたない投稿へのご助言、ありがとうございました。
本件Closeとさせていただきます。
