### ISSUE TITLE
一覧のページ当たりの表示件数について

### ISSUE THREAD

**Issue by m-k-0123** [Implem/Implem.Pleasanter#79]
テーブル管理画面の一覧タブで「ページ当たりの表示件数」を設定しても
常に全てのレコードが１ページに表示されてしまうのですが、
不具合でしょうか？
この設定自体を有効or無効にするような設定があるのでしたら
ご教示いただけるとありがたいです。

バージョン：0.47.82.25734
ブラウザ：Edge、IE他で確認

**Comment by yoshiyuki-sato** [comment]
Issueありがとうございます。
プリザンターでは、ページ送り機能でレコードは表示せず、常に全てのレコードが１ページで表示される仕様となっております。
「ページ当たりの表示件数」とは一回で読み込む件数の事を指しております。
スクロールによって次のページが自動的に読み込まれるようになっております。
