### ISSUE TITLE
公開で議論できる場が欲しいです

### ISSUE THREAD

**Issue by ribbon26** [Implem/Implem.Pleasanter#8]
Microsoftのイベントでお目にかかったものです。
Pleasanter の議論ですが、Facebookのようなクローズドな場ではなく、公開された場所で議論いただけると助かります。会社によっては、Facebookやtwitterなどはアクセス禁止になっていますので。

**Comment by Implem** [comment]
コメントありがとうございます。GitHubでIssue受け付け可能です。他におすすめの議論の場がありましたら、教えていただけますと助かります。

**Comment by karoshima** [comment]
Issue というよりもアバウトな話をする場というのは、たしかにあるといいなと思います。
Facebook や twitter はたしかにアク禁の問題はありますが、便利ですよね。
Slack はクローズドですが、着手しやすいかなと思います。

**Comment by Implem** [comment]
Slackもいいですね。メンテナンス行き届くか不安ですが、まずは場をつくってみます。週末にセットアップしてご案内しますね。あとはプリザンターのクラウド版を使うという手も考えてみます。

**Comment by karoshima** [comment]
プリザンターのクラウド版！むしろその方が面白そうです。一票。

**Comment by ribbon26** [comment]
Slackも外から見えないので、プリザンダークラウド版の方が(外から見えるのであれば)良いかと思います。

**Comment by Implem** [comment]
プリザンターもログインしないと見れないので、どうしたものか悩みます。GitHubのIssueが一番いいかもしれません。追加でSlackも準備します。
