### ISSUE TITLE
インポートしたレコードの検索について

### ISSUE THREAD

**Issue by m-k-0123** [Implem/Implem.Pleasanter#80]
csvファイルでインポートしたレコードが検索対象になりません。
項目を指定した検索(フィルタ）だとヒットするのですが、
全項目対象の検索（単に「検索」と表示されている検索欄）だとヒットしません。

少し調べたところ、インポートではsearchindexesのレコードが作成されていないのが原因のようで、
レコードを一旦エディタで開いて更新をかけると検索対象になりますが
インポートした全てのレコードを一件一件更新するのは現実的ではなく、
インポート時にも検索用レコードが作られるようにしていただけたら大変助かります。

バージョン：0.47.82.25734

**Comment by NaokiShiwa** [comment]
Issueありがとうございます。
現状ではフルテキスト検索機能を有効化していない状態でcsvインポートしたレコードが検索対象にならない不具合がございます。

すでにCSVインポートにて登録されたデータにつきましては、最新版のプリザンター（Ver0.49.64）では、[テーブルの管理]-[検索]にて
「検索インデックスと再構築」というボタンが追加されており、これを押下することで現在のサイトの検索インデックスが再構築されます。
お手数ですが、最新版のプリザンターをインストールして頂いた後、上記手順をお試しください。

また、フルテキスト検索機能を有効化することでCSVインポートされたレコードも検索が可能となりますので、下記リンク先をご確認の上、設定をお願いいたします。
※Search.jsonの変更後はIISの再起動が必要となります
https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%97%E3%83%AA%E3%82%B6%E3%83%B3%E3%82%BF%E3%83%BC%E3%81%AE%E3%83%95%E3%83%AB%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E6%A4%9C%E7%B4%A2%E6%A9%9F%E8%83%BD%E3%82%92%E6%9C%89%E5%8A%B9%E5%8C%96%E3%81%99%E3%82%8B

**Comment by m-k-0123** [comment]
追加機能のインデックスの再構築、または
フルテキスト検索機能有効化で対応可能とのことで了解しました。
回答ありがとうございました。
