### ISSUE TITLE
トップでのサイト作成とグループ管理の権限設定について

### ISSUE THREAD

**Issue by m-k-0123** [Implem/Implem.Pleasanter#81]
権限設定に関わらず、全ユーザーがトップでのサイトの新規作成と、グループの管理機能が使用可能になっているようですが、これを制限する機能は未実装でしょうか？
UsersテーブルのUserSettingを手動で編集するとその2機能を非表示にできますが、これを画面から設定する箇所が見当たりません。

一般ユーザーを増やすたびにテーブルを編集するのも非効率的ですし、当方の運用ではテナント管理者の権限と連動してほしいため、とりあえずソースを改造してテナント管理者の権限を参照するように変更しましたが、できれば大元のソースで対応していただきたく、お願いいたします。

バージョン：0.47.82.25734

**Comment by Implem** [comment]
ご要望ありがとうございます。開発チームで実現可否検討いたします。
