### ISSUE TITLE
バックアップしたデータのリストア方法について

### ISSUE THREAD

**Issue by shibarin** [Implem/Implem.Pleasanter#83]
Wikiの「プリザンターのデータベースをバックアップする」について、バックアップしたデータのリストア方法を教えていただけないでしょうか。
【URL】
<https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%97%E3%83%AA%E3%82%B6%E3%83%B3%E3%82%BF%E3%83%BC%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%82%92%E3%83%90%E3%83%83%E3%82%AF%E3%82%A2%E3%83%83%E3%83%97%E3%81%99%E3%82%8B>

**Comment by m-k-0123** [comment]
私も同じ事で困ってましたので
おせっかいながら当方で作成したものを載せておきます。
※Implem.Pleasanterの他にmasterがある前提です。
リストアの場合、そのものに入ってしまうとできないので
masterに入ってImplem.Pleasanterをリストアするようにしています。
※このスクリプトでは
スクリプトファイルをDBサーバー上に置いて
バックアップしたファイルをスクリプト上にドロップするようにしています。
必要に応じて調整して下さい。

ーーーーーーーーーーーーーーーーーーーーーーーーーー
Option Explicit
Dim conn, server, db1, db2, uid, pwd, path,arges
set arges = WScript.Arguments
server =     "localhost"   ★スクリプトをローカルに置いてない時はサーバー名にして下さい
db1 =         "master"
db2 =         "Implem.Pleasanter"
uid =        "sa"
pwd =        "★saのパスワード"
path = arges(0)
Set conn =   WScript.CreateObject("ADODB.Connection")
conn.Open (  "Driver={SQL Server};" & _
             "Server=" & server & ";" & _
             "Database=" & db1 & ";" & _
             "UID=" & uid & ";" & _
             "PWD=" & pwd & ";")
conn.Execute "RESTORE DATABASE " & _
             "[" & db2 & "] " & _
             "FROM DISK=N'" & path & "' "
conn.Close
Set conn = Nothing
msgbox "完了"

**Comment by shibarin** [comment]
m-k-0123様

情報提供していただきありがとうございます。
当方の構築環境ではサーバー1台のみでの構築となるため
リストアのためにDBサーバーを別に用意することができません。
Implemに直接問い合わせてみます。

ご回答いただきありがとうございました。

**Comment by sato-ha** [comment]
こんにちわTSR佐藤です。

バックアップしたデータの復元が目的なら、SQL Server Management 
Studioからデータベースを選択して右クリックした中にあるタスクの復元からリストアできると思います。

一般的なSQLサーバの操作になりますので、「SQLサーバー　リストア」などのキーワードで検索すればさらに詳細な情報が得られると思います。

**Comment by m-k-0123** [comment]
フォローがあったのでもう不要かもしれませんが・・・
masterは別サーバーではなく
SQLサーバーをインストールしたら最初から入っていたシステムDBですので
そこは変更せずに使えると思います。
※SQLServerのバージョンは2014です。

当方ではwindows7の32bitに構築する必要があり、
SQL Server Management Studioをインストールできなかったので
スクリプトを作ったんですが
management studioが使えれば復元できたんですね＾＾；

**Comment by m-k-0123** [comment]
m-k-0123です。

TSR佐藤さま
Management Studioの32bit版の情報ありがとうございます。
今のところテーブル操作などは別の愛用ツールを使っているのですが
今後それじゃないと出来ないことが出てきましたら使ってみます。

shibarinさま
本題以外でのやりとり失礼いたしました。
問題解決できましたでしょうか。
Management Studioでの復元は
一般的な操作なのかもしれないですが
マニュアルに記載しておいて欲しいところですね。

**Comment by shibarin** [comment]
shibarinです。
ご返信が遅れてしまい申し訳ありません。

TSR佐藤様
情報のご提供ありがとうございます。
こちらの環境でもSQL Server Management Studioから
データの復元項目を確認いたしました。
こちらを利用してリストアを行おうと思います。

m-k-0123様
masterについて補足いただきありがとうございます。
SQLサーバーについて知識が浅く、大変勉強になりました。

皆さまご回答いただきありがとうございました。
本件はクローズとさせていただきます。
