### ISSUE TITLE
自動採番項目の設定について

### ISSUE THREAD

**Issue by y-kamikado** [Implem/Implem.Pleasanter#87]
お世話になっております。
自動採番項目を設定する事は可能でしょうか？

宜しくお願いします。

**Comment by yoshiyuki-sato** [comment]
issuesありがとうございます。
自動採番項目についてですが、まず、自動採番項目の用途としてはどういったものとなりますでしょうか。
現状プリザンターには自動採番項目はありません。申し訳ございませんが今のところ実装の予定等もございません。
ただ、それ以外の用途としてでしたら、プリザンターの拡張SQLの機能を使用すれば、独自に自動採番項目を追加することは可能です。

・システム機能：拡張SQL
https://github.com/Implem/Implem.Pleasanter/wiki/%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E6%A9%9F%E8%83%BD%EF%BC%9A%E6%8B%A1%E5%BC%B5SQL

**Comment by y-kamikado** [comment]
返信ありがとうございます。
自動採番項目についてですが、使用用途としてはプロジェクト毎の案件管理等で、それぞれの案件ｋ
