### ISSUE TITLE
Binariesテーブルの定義変更で転ける

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter#88]
Pleasanter.0.48.47.26325からPleasanter.0.48.54.24731にバージョンアップをおこなおうとすると、CodeDefinerがBinariesテーブルの定義変更の段階で転けます。
フルテキストインデックスが定義されているためインデックスを削除できないというメッセージを吐いて停止します。

**Comment by kazuca** [comment]
手動で変更をおこなった後に、CodeDefinerを実行して対応しました。

ALTER TABLE [Binaries_history] ALTER COLUMN [Size] BIGINT NULL
ALTER TABLE [Binaries_deleted] ALTER COLUMN [Size] BIGINT NULL
ALTER TABLE [Binaries] ALTER COLUMN [Size] BIGINT NULL

**Comment by Implem** [comment]
回答がおそくなりました。本件ですが、いただいたスクリプトの他にフルテキストインデックスを一旦削除し、CodeDefinerを実行した後に再作成する方法でも対応可能です。
