### ISSUE TITLE
Implem.CodeDefiner.exeが存在しない

### ISSUE THREAD

**Issue by barder369** [Implem/Implem.Pleasanter#89]
こんにちは。  

#20 での指示通りに項目数を増やそうとしたのですが、  
definition_Column.xlsm内のマクロで定義されている下記ファイルが存在しないためエラーとなりました。  

Const CodeDefinerPath As String = "\..\..\..\Implem.CodeDefiner\bin\Debug\Implem.CodeDefiner.exe"  

正確にはbinフォルダ自体が無い状態です。（配下のファイルが全部exe形式？）  
ビルドしたものにも含まれていないので入手手段がわかりません。  
環境は Windows7 Pro SP1 です。  

入手手段を教えてもらえると助かります。

**Comment by Implem** [comment]
CodeDefinerは、セットアップモジュールの下記のフォルダに格納されています。
こちらをコピーしてご使用ください。

\Pleasanter\CodeDefiner
