### ISSUE TITLE
インストール時に構成可能な要素を増やしてください

### ISSUE THREAD

**Issue by Hajime-Sasaki** [Implem/Implem.Pleasanter#9]
インストール時に構成可能な要素を増やしてください。
現状（バージョン0.41.1.33578）のインストーラーでは、プリザンター用のサーバーを新規に用意する分には困らないのですが、既に他のWebサイトが稼働しているサーバーにプリザンターを追加配置することを考えた場合、以下の要素をインストール時に構成できないと不都合です。
* Webサイト配置先の仮想パス
* ファイル配置先の物理パス
* プリザンターが使用するアプリケーションプール
* アプリケーションプールが使用するアカウント
* 接続先のSQLサーバー
* プリザンターが使用するデータベース名
* データベースへの認証方法

あるいは、現在の、インストーラーが全てを自動で配置・構成する方法とは別に、IIS上のファイル一式（アプリケーション）とデータベースを手動で配置した上で、その配置に合わせてプリザンターの設定を構成する手段を提供して頂けないでしょうか。
ぜひご検討をお願いします。

**Comment by Implem** [comment]
Issueありがとうございます。自動化すぐにはむずかしそうなので、手動での構成手順をつくるようにします。手順ができあがったらご案内します！

**Comment by Hajime-Sasaki** [comment]
ご検討ありがとうございます。

**Comment by Implem** [comment]
手動インストールのマニュアルを掲載しました。

## 手動インストール
- [プリザンターのモジュールを手動で配置する（高度な設定）](../wiki/プリザンターのモジュールを手動で配置する（高度な設定）)
- [プリザンターのデータベースを手動で構成する（高度な設定）](../wiki/プリザンターのデータベースを手動で構成する（高度な設定）)

**Comment by Hajime-Sasaki** [comment]
ありがとうございます。ご記載の手順で手動で配置できました。

作業中に別の問題を発見しましたので、新しいIssueを記載しました。
https://github.com/Implem/Implem.Pleasanter/issues/12
