### ISSUE TITLE
一覧表示のフィルタで「説明」項目の空欄指定をしたい

### ISSUE THREAD

**Issue by kaotaka** [Implem/Implem.Pleasanter#93]
テーブル一覧表示にて、フィルタに説明の書式設定で設定した項目について、空欄のものをフィルタしたい場合の条件指定の仕方を教えてください。

**Comment by pierre3** [comment]
申し訳ございませんが、テキスト入力の項目（「説明」、「分類」）について、空欄を指定してフィルタすることはできません。

**Comment by kaotaka** [comment]
ありがとうございます。技術的には可能なのでしょうか？仕様にないだけなのか、また、今後実装予定があれば教えてください。

**Comment by pierre3** [comment]
技術的には可能ではありますが、今のところ実装の予定は御座いません。
ご希望に添えず申し訳ありません。
