### ISSUE TITLE
APIによりファイルの添付について

### ISSUE THREAD

**Issue by chanrai** [Implem/Implem.Pleasanter#94]
ＡＰＩによりファイルの添付機能が実現したいですが、AttachmentsA　にnameとcontentの情報が書いて、リクエストしてみましたが、なかなか登録できません。

可能であれば、Attachmentsに登録するためのAPI仕様が教えて頂けますでしょうか？

よろしくお願いします。

**Comment by Implem** [comment]
回答がおそくなり申し訳ございません。現在のプリザンターにはAPI経由で添付ファイルを登録する仕組みがございません。現時点では対応する予定がございませんので、本件はクローズといたします。
