### ISSUE TITLE
AD連携の状況がわかるようにしたい

### ISSUE THREAD

**Issue by yh113** [Implem/Implem.Pleasanter#97]
お世話になります。プリザンターの機能を試すべくインストール後はＡＤ連携を最初に設定していますが、うまくいっていません。json の構文はチェック済みです。
　設定のどの部分に問題があるか、エラーが確認できるようにならないでしょうか。ユーザーを同期するメソッドを呼び出すＵＲＬを参照しても何の画面も表示されないため状況がよくわからないため設定の修正ができないでおりました。

**Comment by pierre3** [comment]
Issueありがとうございます。

AD連携の設定内容をテストするツールを作成いたしました。
Authentication.jsonの設定内容を用いてADのアカウントを検索し、取得できたアカウントの一覧を表示します。

使用方法等は以下のマニュアルをご確認ください。
https://github.com/Implem/Implem.Pleasanter/wiki/サポートツール

また、AD連携に関する不具合（ https://github.com/Implem/Implem.Pleasanter/issues/98 ）を修正しております。最新のバージョンにアップデートの上、ご確認くださいますよう、お願いいたします。
