### ISSUE TITLE
ＬＤＡＰ連携時にログインできずに、ログイン画面に戻される

### ISSUE THREAD

**Issue by mb543084** [Implem/Implem.Pleasanter#98]
お世話になります。
プリザンターの機能検証でLDAP連携を試しています。
AutoEnableはTrueにしているのですが、LDAP認証のユーザでログインしようとすると、
ログインしています表示のあとにTOP画面すら表示されすにログイン画面に戻されてしまいます。
また、Usersテーブルを直接確認すると作られるはずの連携ユーザーが作られていません。
デフォルトのAuthentication.jsonファイルでログインを試すと通常通りログインできるため、
データベースへの書き込み権限には問題ないと考えていますが、
LDAP連携でのユーザ作成に失敗している為ログイン自体も失敗しているのではないかと推測しています。
考えられる原因がありましたら、教えていただけますでしょうか。

**Comment by pierre3** [comment]
プリザンターの不具合により、LDAP連携時のユーザー作成に失敗するケースがございました。
ご不便をお掛けして申し訳ございません。

バージョン0.49.85にて修正いたしましたので、最新バージョンにアップデートの上、もう一度お試しいただけますでしょうか。

**Comment by mb543084** [comment]
ご対応ありがとうございます。
LDAP連携でのユーザー新規作成ができること確認致しました。
