### ISSUE TITLE
レコード更新の競合時の動作（排他制御）について

### ISSUE THREAD

**Issue by tomoakikatano** [Implem/Implem.Pleasanter#99]
お世話になります。
複数人で同じレコードを更新する時の動作についての質問です。

レコードを同時に更新しようとすると、編集内容の送信を後から実行した側に下記のメッセージが表示され画面を再読み込みしないと更新ができません。
「ｘｘｘユーザ さんが先に更新したため更新できません。再読み込みしてください。」

画面を再読み込みしてしまうとそれまで書いていた内容が消えてしまうので、変更内容をメモ帳などに退避し、ページを再読み込みした後でレコードを編集し直す方法をとっていますが、これ以外に何か回避方法はありますでしょうか？

また、下記の様な機能追加の予定はありませんでしょうか？
・レコードが「編集中」のときは、他のユーザはそのレコードに対して「閲覧」のみにできる。
・編集内容の送信を後から実行した側に競合内容のdiffが表示され、マージができる

**Comment by yoshiyuki-sato** [comment]
Issueありがとうございます。
まず、編集内容の退避について何か別の方法はないかとの事ですが、申し訳ございませんが、現在の仕様では有効な回避方法は御座いません。
次に、ご提案頂いた上記の機能追加ですが、以下1点ずつ回答させていただきます。

・レコードが「編集中」のときは、他のユーザはそのレコードに対して「閲覧」のみにできる。
→例えば、上記の機能を実装した場合、編集中のユーザがブラウザを閉じた場合等、編集中の状態のまま終了された場合を考慮しますと、実装は難しいかと思われます。
今のところ実装予定は御座いません。


・編集内容の送信を後から実行した側に競合内容のdiffが表示され、マージができる。
→今のところDiff機能の実装予定は御座いません。
